### ISSUE TITLE
[Documentation] Examples in Lua API docs reference incorrect functions

### ISSUE THREAD

**Issue by BrunoBieri** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#1]
In the Lua [API documentation](https://www.teardowngame.com/modding/api.html) for Teardown 0.6.2 there are some minor issues

---

**For "SetString"**

The example API shows
`SetBool("level.name", "foo")`

Actual Result:
Note that it says `SetBool`.

Expected Result:
I think it should be `SetString` instead.

Link:
https://www.teardowngame.com/modding/api.html#SetString

---

**For "FindJoint" and "FindJoints"**

Both examples API use
`FindLocation` instead of `FindJoint` and `FindJoints`

Links:
https://www.teardowngame.com/modding/api.html#FindJoint
https://www.teardowngame.com/modding/api.html#FindJoints

---

**For "FindShape"**

The example API shows
```
--Search for a shape tagged "mybox" in script scope
local target = FindShape("mybox")

--Search for a shape tagged "laserturret" in entire scene
local escape = FindBody("laserturret", true)

```
Actual Result:
Note that in the second line of code it says `FindBody`.

Expected Result:
I think it should be `FindShape` instead.

https://www.teardowngame.com/modding/api.html#FindShape

---

**For "GetShapeLocalTransform"**

The example API shows
```
--Shape transform in body local space
local shapeTransform = GetShapeLocalTransform(shape)

--Body transform in world space
local bodyTransforn = GetBodyTransform(GetShapeBody(shape))

--Shape transform in world space
local worldTranform = TransformToParentTransform(bodyTransform, shapeTransform)
```

Actual Result:
Note the variable name `bodyTransforn`.

Expected Result:
Should actually be `bodyTransform` instead with an "m" at the end.

https://www.teardowngame.com/modding/api.html#GetShapeLocalTransform

---

**For "GetShapeWorldTransform"**

The example API shows
```
local worldTransform = GetShapeWorldTransform(shape)

--This is equivalent to
local shapeTransform = GetShapeLocalTransform(shape)
local bodyTransforn = GetBodyTransform(GetShapeBody(shape))
worldTranform = TransformToParentTransform(bodyTransform, shapeTransform)
```

Actual Result:
Note the variable name `bodyTransforn`.

Expected Result:
Should actually be `bodyTransform` instead with an "m" at the end.

https://www.teardowngame.com/modding/api.html#GetShapeWorldTransform

**Comment by tuxedolabs** [comment]
All fixed in 0.7.0. Thanks for reporting!
