### ISSUE TITLE
[Feature] Give modders the ability to write to an image buffer

### ISSUE THREAD

**Issue by ss-gnalvesteffer** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#10]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
I've noticed recent mods such as the [Minimap mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2426790031), and the [Portal Gun mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2421609769) are using sprites and UiRects as a workaround to draw many pixels to form a cohesive image. This is very clever, but non-performant when needing to draw a higher resolution image.

**Describe the solution you'd like**
The ability for modders to write to an image buffer which can then be displayed as a sprite or UI image would be ideal, as there would only be a single element to draw, instead of hundreds or thousands. Being able to create an image buffer like so: `local image_buffer = CreateImageBuffer(width, height)`, and then being able to write individual pixels `SetPixel(image_buffer, x, y, r, g, b, a)`, and being able to use this image buffer like a sprite or as a UI image would hopefully let modders pull off these cool conceptual projects with optimal performance.

**Describe alternatives you've considered**
Alternatively there could be a way to render to a texture, by being able to create a new camera that can be controlled by scripting, and having its view output to a texture (whose dimensions must be specified) that can be displayed as either a sprite or a UiImage. A possible usage example could be:
```lua
function init()
  render_texture = CreateTexture(width, height)
  camera = CreateCamera(transform)
end

function tick() -- alternatively, this could be used on draw() instead
  -- ... code to move around the camera and stuff

  RenderCameraToTexture(camera, render_texture, quality_setting) -- this would get called per tick. quality settings could be a table of various rendering quality parameters, or an enum of rendering presets

  -- ... code to draw the camera render texture as either a sprite or UiImage
end
```

**Additional context**
See how these mods draw the resulting images:
Minimap mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2426790031 -- uses multiple UiRects to represent pixels
Portal Gun mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2421609769 -- uses multiple sprites to represent pixels

**Comment by MisterSirCode** [comment]
Good idea, but there is one issue... Well, here, let me put it into an example situation..
Say you want to create a security camera system, and have working screens that render the texture taken from those custom cameras.
This wouldnt be much of an issue, if it wasnt for the fact that you must, for one, fire more rays to get equal to or similar fidelity to that of the player's camera. After those rays are received, it also has to filter AND composite that frame, same as the player's camera.
This would cause major overhead on slower devices, rendering an entirely separate screen and camera.
Now, dont get me wrong, on a more powerful device with a GPU that supports parallel processing, it might actually work pretty well.

It all depends on optimization and implementation. I do think itd be a neat feature, but it just may not be very feasible for a game such as this one, with such high fidelity graphics that require a lot of graphical processing power.

**Comment by tuxedolabs** [comment]
I've thought about this a bit and I think it's beyond the scope of the modding API
