### ISSUE TITLE
[Bug] Test Reults

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#100]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/150714882-8bef3ecb-87f4-460e-98f3-2bff53fdee07.png)
why do i remember this bug?

### Steps to reproduce the behavior

1. Go to Lee chem
2. Go to the big factory building's 2nd floor office
3. find this note

### Expected behavior

Test Results

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

### Additional context

i believe this has been reported on discord?

**Comment by tuxedolabs** [comment]
Fixed. Thanks
