### ISSUE TITLE
[Feature] Convert VoxBox to Voxagon

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#101]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

i'm currently working on a shop and i've decided to make the walls a little cooler by rotating a part of the wall, but now i have to recreate the flooring and ceiling into voxagons because it doesn't look good

### Describe the solution you'd like

have the voxbox be turned into a voxagon

### Describe alternatives you've considered

manually redo it but it's a slower process

**Comment by tuxedolabs** [comment]
Not sure this would work very well since voxagons are 2D, so it might not map the axis you had in mind to height. I think it's better to leave as is.
