### ISSUE TITLE
[Feature] Configurable Instance

### ISSUE THREAD

**Issue by 349767970** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#102]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Currently the only legit way to have the same instance (lets say a light) to have slightly different properties (lets say warm color, cold color), is to have different instances for different variations, which is painful to look at, and straight up doesn't work if you want even slightly more freedom

### Describe the solution you'd like

having a properties for instance like the prop for groups, or make it smarter so it know what are some configurable stuff that is available for this instance by probably setting smth up when making the instance, and it just shows all of them below like the voxscript
might even be able to use that function in the new coming runtime spawning, allow people to config the stuff they gonna spawn

### Describe alternatives you've considered

put the instance inside of a group, then put value in the prop properties, its still more complicated to setup, which also clutters the editor structure as you might have a lot of group that only contains a single instance, and painful you if you want to swap instance
(in fact, im currently using this setup for my customizable color vehicles)

**Comment by Please-Pick-a-Name** [comment]
and i logged into the wrong acc again, ahhh

**Comment by tuxedolabs** [comment]
This would be neat and we have talked about it, but it is unlikely to be implemented at this point.
