### ISSUE TITLE
[Feature] Ability to add in original Teardown props

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#103]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

instead of having to copy in props from the assetpack and other built-in addons, have it so we can add in the original props from the original game to mods, which could also be useful to optimise mod size, it can be without having to give the vox models, they can be .tde'd like the songs etc, it'll also allow us to make a bigger vanilla prop library

### Describe the solution you'd like

^

### Describe alternatives you've considered

^

**Comment by tuxedolabs** [comment]
We might release more/bigger assets packs in the future, but the original file structure is not likely to be released since the game levels ship in binary form. There might be asset import from other mods in the future, but not sure when.
