### ISSUE TITLE
[Bug] IsHandleValid() returns true on shapes/bodies deleted by explosions/holes

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#104]
### Describe the bug

What I was expecting was that `IsHandleValid()` would return false for a shape or a body that was completely destroyed in term of voxel (after an explosion for example). 

This forces the addition of extra check like `GetBodyMass()==0` on a body or `GetShapeVoxelCount()==0` on a shape to check if the body no longer exists, which feels more like a hack than a proper way to test for entity existence.

Is there no such thing as garbage collection for very small shapes? Is it not supposed to happen for shapes of size 0?

### Steps to reproduce the behavior

1. Store the handle to a body in a variable
2. Fully destroy that body ingame using explosions or holes
3. Call IsHandleValid() on the saved body handle
4. Notice that the function still returns true

### Expected behavior

1. Store the handle to a body in a variable
2. Fully destroy that body ingame using explosions or holes
3. Call IsHandleValid() on the saved body handle
4. Notice that the function now returns false

### Environment

- Teardown Version:  0.9.2 (patch 1)
- OS: Windows 10
- GPU: NVIDIA GeForce GTX 960M
- Graphics driver version: 511.23
- CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz

**Comment by tuxedolabs** [comment]
This is by design. Debris that is created by the engine is cleaned up automatically, but original bodies and shapes are not, since scripts may rely on their handles to function correctly.
