### ISSUE TITLE
[Question] Debugging a crash

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#105]
**Question**
Is there a way to get additional infos from the game (like a stack trace) when the game crashes when using a mod?

So far I tried to debug using DebugPrint() all over the code but it didn't help much... All I could tell is that the crash seems to happen between the tick() and the draw() function...

NB: I am using the modified winmm.dll to get a console when I run the game, but no additional infos did appear in that console.

**Comment by tuxedolabs** [comment]
Not sure a stack trace would give that much useful information.

**Comment by FlorentP42** [comment]
Well if the stack end out of the code of my mods then it probably won't help much yeah, but if it's inside the code I wrote then it will certainly help a lot :)
