### ISSUE TITLE
[Bug] Game crashes when i add a negative number for the size of a voxbox

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#106]
### Describe the bug

It was by accident

### Steps to reproduce the behavior

1. set voxbox size to a negative number

### Expected behavior

not crash,

### Environment

.

**Comment by tuxedolabs** [comment]
Fixed in dev version. Thanks for reporting!
