### ISSUE TITLE
[Feature] Access for mods to open workshop page

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#107]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

This could be a helpful enhancement for modders. There's already several dependency or sample mod released on workshop (e.g.: AVF by elboydo, Tagz by ONSVEG, YLVF from me). Reason for these mods to exist is obvious: modders may not talented in making contents while content makers could have no idea on modding. However there's no direct link in game between these mods and other maps using them. Additionally most players would ignore all "**Read Description**" stuff and some of them even ignore a pop out notification says: "**You Need XXX Mod to Play!**", which can largely reduce playability.

### Describe the solution you'd like

I took a look at Teardown's data folder and found the `Command()` function which can open links, however we can't use them due to security. A workaround such as `SteamLink()` which only allows steam urls could be a good solution and make a menu similar to this to actually work, such as clicking on a picture to open workshop page of the item
(screenshot of my YLVF mod, currently this is just a list of maps)

![image](https://user-images.githubusercontent.com/70589524/151733278-94905a0e-f925-4814-8431-26bfe80c125d.png)

### Describe alternatives you've considered

I don't really considered an alternative for this, but applying further limitations to links is accessible, such as only workshop items is allowed therefore the function would be something like this: `ItemLink( id )`

**Comment by tuxedolabs** [comment]
I see the problem, but this will likely not be implemented. You can already go to mod page on steam by right-clicking it in mod list.

**Comment by YuLun-bili** [comment]
That's true, but just remind you how many people asking 'multiplayer' and 'spawning' on discord before you archived the 'suggestion' channel.

I'd say not may people will actually sit and find the mod he needs, or read description of a mod, which sometimes makes modders really pain since we have to answer them, or they would start complain you not replying (Jesus...)

**Comment by YuLun-bili** [comment]
What about a simple function branched from `Command()` functions? like this:
`function OpenSteamItem( id )
  Command("game.openurl", "https://steamcommunity.com/sharedfiles/filedetails/?id="..id)
end`

it's defiantly not perfect, and it's fine to reject since this is just an idea : )
