### ISSUE TITLE
[Bug] skybox="LEVEL/day.dds" carsh game

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#108]
### Describe the bug

Putting level/day.dds in environment will crash game

### Steps to reproduce the behavior

1. Go to 'editor'
2. Input in environment 'skybox="LEVEL/day.dds"'
3. See error

### Expected behavior

Game crashes, but not everytime... Maybe with restaring game it can crash again.

### Environment

- Teardown Version [e.g. 0.9.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: Windows 10
- GPU: 2080 ti
- Graphics driver version:
- CPU: 12900K

### Additional context

if skybox="LEVEL/day.dds" change to skybox="day.dds" it should work fine...

**Comment by tuxedolabs** [comment]
Thanks, I now default to cloudy.dds if provided cubemap is not found. Fixed in 0.9.3
