### ISSUE TITLE
[Feature] Add crash log

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#109]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Please add special folder or smth so when game crash it can put crash log file there.

### Describe the solution you'd like

Adding ability to check wich is caused game crash, is it a empty vox, or incorrect prameters in editor.

### Describe alternatives you've considered

- add ability to open crash folder or crash log file.

**Comment by Thomasims** [comment]
Duplicate of #51
