### ISSUE TITLE
[Documentation] Categories for different types of tools

### ISSUE THREAD

**Issue by GGProGaming** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#11]
**Document to improve**
https://www.teardowngame.com/modding/api.htm

**Enhancement**
Add categories listed as the base teardown tools for weapon modding. Such as a section for things related to guns like particles and fire rate or gravity. Others would be like rocket and would have explosions, particles, bullet drop, bullet color... Things like that

**Comment by tuxedolabs** [comment]
Not sure I understand the suggestion. There are a number of tool mod examples already that explains how to make a tool. I think it is better showcased as an example mod rather than documentation.
