### ISSUE TITLE
[Bug] UiSlider() not working for vertical axix

### ISSUE THREAD

**Issue by TTFH** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#110]
### Describe the bug

No matter what drag axis value you use on UiSlider(), the slider will be always horizontal.
`value = UiSlider("ui/common/dot.png", "y", value, 0, 100)`
Will create an horizontal slider instead of a vertical one.

**Relevant documentation:**
value, done = UiSlider(path, axis, current, min, max)
axis (string) – Drag axis, must be "x" or "y"

### Steps to reproduce the behavior

Example code:
```lua
scroll_value = 0

function draw()
	UiPush()
		UiMakeInteractive()
		--scroll_value = clamp(scroll_value - InputValue("mousewheel") * 20, 0, 500)
		UiTranslate(400, UiHeight() / 2)
		UiAlign("center middle")
		UiColor(0, 0, 0, 0.5)
		UiImageBox("ui/common/box-solid-6.png", 13, 500, 6, 6)
		UiTranslate(0, -250)
		UiColor(1, 1, 0.5, 1)
		--UiRotate(-90)
		scroll_value = UiSlider("ui/common/dot.png", "y", scroll_value, 0, 500)
	UiPop()
end
```

### Expected behavior

The slider to be vertical when using axis = "y"

**Workaround:**
Rotate the slider 90 degrees
```lua
UiRotate(-90)
value = UiSlider("ui/common/dot.png", "x", value, 0, 100)
```

### Environment

- Teardown Version 0.9.2 (patch 1)

**Comment by tuxedolabs** [comment]
Thanks for reporting. Vertical sliders should now work according to documentation, starting with 0.9.3
