### ISSUE TITLE
[Bug] Smoke coming out from the back instead of from the sides on the Crownzygot

### ISSUE THREAD

**Issue by Tresquel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#113]
### Describe the bug

![image](https://user-images.githubusercontent.com/43729305/152656298-210da072-b26c-4876-8aa1-b7235b8580fa.png)

The smoke isnt coming out of the sides where the exhaust(s) are.

### Steps to reproduce the behavior

1. Get in a Crownzygot
2. Drive it
4. Look on the back

### Expected behavior

The smoke coming out of the sides or the exhaust being in the back

### Environment

- Teardown Version 0.9.2 (patch 1)
- OS: Windows 10 20H2 (build: 19042.1503)
- GPU: 3050ti mobile
- Graphics driver version: 511.65
- CPU: i7 11800H

**Comment by tuxedolabs** [comment]
By design. Thing on side is not exhaust
