### ISSUE TITLE
[Feature] allow Voxbox Color value to be tweaked through scripts

### ISSUE THREAD

**Issue by lazyRares** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#115]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

This feature would allow you to add true randomization of props, for example. If you had a container prop, instead of making four versions for different colors, you can make a parent prop that is White, and then color it at runtime using a random script that chooses between multiple color values.

### Describe the solution you'd like

The solution i'd like to see is just a API function being added to be able to achieve this, that's about it.

### Describe alternatives you've considered

Not many alternatives i've considered.

**Comment by tuxedolabs** [comment]
Thanks, it's a good suggestion, I'll keep it for later.

**Comment by YuLun-bili** [comment]
1.4.0 update introduced several functions allowing scripts to modify any shape's voxel model at runtime. So I think it's good enough to mark this one as implemented and close.
