### ISSUE TITLE
[Feature] Customizable Loading Screen (or entire in-game UI)

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#116]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

There's a parameter in `StartLevel()` called `passThrough` which allows music to keep playing during loading, so I wonder if it's possible to add another parameter to enable custom loading screen

### Describe the solution you'd like

Introduce a new function called `loading` and treat it similar to `draw` function, but the function could have a switch case function which allows multiple loading screen layout being used. Obviously this function is only called when using `StartLevel()` with an optional layout parameter

### Describe alternatives you've considered

specific lua scripts such as `loading.lua` to read loading screen layouts could be a better approach, layers can be achieved via numbers in script name like `loading8.lua` represents 8th layout.(or maybe `loading08.lua`, `loading-8.lua`, etc.) This method won't introduce special functions

### Additional context

All these might be very tricky since I have no idea on how this could be properly done. Replacing somehow hardcored game UI is not a good idea, at any time, although it's nice if we can find a way to achieve it.

I also mentioned this could be extended to all base game UI system (mainly hud.lua and map.lua) since for now we can replace hud.lua by introducing a new one in mods, but that have lots of side effects such as broken pause menu.

I can understand the difficulties since you need to clean up lots of codes and even restructure several parts (which is definitely pain lol). It's nice to have it, but also nice to maintain the status

**Comment by tuxedolabs** [comment]
I think this is a bit out of scope for the modding API, but thanks for the suggestions.
