### ISSUE TITLE
[Bug] Tools attached on objectives is glitched

### ISSUE THREAD

**Issue by Litttlefish** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#118]
### Describe the bug

In the Motivational Reminder mission, you can complete it without breaking the propane tank by attaching a thruster on it and breaking the thruster with a blowtorch.

And in the Droid Abduction mission, if you attach nitroglycerin to the vault door, it will become totally unbreakable.

### Steps to reproduce the behavior

1. Go to the mission mentioned above
2. Put thruster/nitroglycerin on them
3. Break it
4. Nothing will happen for nitroglycerin or objective is completed for the thruster.

### Expected behavior

Nothing but thruster breaks or nitroglycerin explodes.

### Environment

- Teardown Version 0.9.2 (patch 1)
- OS: Windows 11
- GPU: RTX 3060 Lapotp
- Graphics driver version: 511.65
- CPU: Intel Core i7 11800H

**Comment by tuxedolabs** [comment]
The nitroglycerin issue should have been already fixed in 0.9.2
Adding a fix for the booster in 0.9.4. Thanks for reporting!
