### ISSUE TITLE
[Bug] "Too much of a good thing" when updating certain steam mod id's

### ISSUE THREAD

**Issue by elboydo** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#119]
### Describe the bug

Attempting to update an old mod will result in being provided the message "too much of a good thing". Even when provided with a version of the mod that steam previously accepted. 

When using a new steam ID, or updating another mod with that mods code + files, then the upload happens without issue.

The issue seems exclusively linked to a small subset of steam workshop id's. 

### Steps to reproduce the behavior

1. Go to effected mod in mod menu
2. Click on publish update
3. see error message 

### Expected behavior

1. Go to effected mod in mod menu
2. Click on publish update
3. see mod updated successfully 

### Environment

- Teardown Version [0.9.2 patch 1]
- OS: [Windows]
- GPU: Nvidia 2060 RTX
- Graphics driver version: 511.65
- CPU: intel I7 9700

### Additional context

Mod tested with old versions, files removed, new images, content of other smaller mods. 

Also found current version uploads with new id, no files changed.

Believed to be an issue relating to steams handling of specific mod ID's.

**Comment by Hallonduell** [comment]
From discord:

"Oh BTW, made some progress with working out the scope of the "too much of a good thing" bug. It seems to have started after cloud saves were added and affects every mod I submitted prior to September 2021.

No idea how though but saw somebody mention cloud saves in relation to another game when I was googling the error code. Tried disabling them but no fix. But at least it provides a weird time frame, even if only for me and possibly Ngnt"

**Comment by elboydo** [comment]
building on this, I noticed the teardown cloud save limit is <1mb. Some games where I saw a similar error occur referenced the cloud save limit. 

Do the devs have control over cloud save limit and if so are there implications to increasing it? 

As I have seen a couple of the games where this bug was mentioned have a cloud save limit ranging in the tens of mb to hundreds of mb. 

Potentially it could be due to some strange mix of mod size vs assumed cloud limit while uploading. Long shot i know, but worth trying. 

Otherwise I'm still trying user end fixes and will update if any provide joy

**Comment by elboydo** [comment]
Update:

It also appears to have impacted other users, I have a feeling it may link to the size of historical uploads and cloud data, but not sure. 

here is relevant discord:
https://discord.com/channels/760105076755922996/768940642767208468/943673110148808734

their fix was to add another user as contrib and get them to update the mod, which suggests this is a user related issue with certain mods rather than the mod itself.

**Comment by tuxedolabs** [comment]
It seems to be related to the cloud save quota. I have upped it to 10 Gb, so hopefully the problem is solved.
