### ISSUE TITLE
[Feature] Hotkeys for campaign and/or maps

### ISSUE THREAD

**Issue by GGProGaming** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#12]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
No, it is not
**Describe the solution you'd like**
Have the same hotkeys found in the editor like ctrl + s to quick save, ctrl + q to quit, and have ctrl + l to quick load.
**Describe alternatives you've considered**
Using other keys like ctrl + shift + * Or customizable hotkeys.
**Additional context**
None

**Comment by tuxedolabs** [comment]
We will probably not add these, or we would have problems with people accidentally overwriting their quicksave.
