### ISSUE TITLE
[Feature] Add a way to change particle velocity after spawn

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#120]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Right now the only thing you cannot do with a particle is to set a variable velocity for its motion.

### Describe the solution you'd like

Add a ParticleVelocity(v0, [v1], [interpolation], [fadein], [fadeout]) function
Where v0 and v1 are velocity vectors, allowing for an interpolation between those vectors during the particle lifespan the same way it is done for other particle characteristics.

Another way to obtain this behaviour would be to return a handle to the particle when you spawn it, allowing the user to update the velocity himself later.

### Describe alternatives you've considered

Complex trajectories for particles could maybe be achieved by spawning particles with a very limited lifetime over and over again with a different velocity each time, but this sounds like a painful solution...

**Comment by tuxedolabs** [comment]
I think this is too specific. Trajectories can already be implemented in script with a bit of math :)

**Comment by FlorentP42** [comment]
![image](https://user-images.githubusercontent.com/45787476/155370709-ddde67b2-f8e8-4b21-a530-3c632934de69.png)
