### ISSUE TITLE
[Bug] Photo Mode - DOF gets sort of ignored behind smoke

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#122]
### Describe the bug

In Photo Mode - DOF gets sort of ignored behind smoke, at the edges
![Screenshot from 2022-02-14 16-09-02](https://user-images.githubusercontent.com/1898194/153890947-0468c958-f3b0-464b-80fb-85ac36c46bc1.png)

### Steps to reproduce the behavior

-

### Expected behavior

Background should not get focus

### Environment

- Teardown Version 0.9.3
- OS: Linux

**Comment by tuxedolabs** [comment]
Technical limitation / expected artefact :-/
