### ISSUE TITLE
[Feature] Camera see through effect

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#123]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Option to enable or somehow get this "see through" effect, other then only by using in a vehicle
![image](https://user-images.githubusercontent.com/1898194/153931013-00181b48-d6c9-4b09-b9f6-cc37bef3544a.png)

### Describe the solution you'd like

Maybe an additional camera option, after DOF.

### Describe alternatives you've considered

There are no alternatives.

**Comment by tuxedolabs** [comment]
I think this is beyond the scope of teardown scripting.
