### ISSUE TITLE
[Bug] Weak leaf blower

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#124]
### Describe the bug

weird blowing behavior from leaf blower, hard to explain, but the force dont seems to be applied correctly
vid here
https://discord.com/channels/760105076755922996/768940642767208468/942902257576464407

### Steps to reproduce the behavior

1. Get leaf blower
2. blow
3. feels weird

### Expected behavior

blow nice and far

### Environment

- Teardown Version 0.9.3
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Found the issue and fixed it. Thanks!

**Comment by Super-Wimp** [comment]
I have a problem where the indicator lines for the leaf blower go of the screen

![image_2025-01-03_134045900](https://github.com/user-attachments/assets/3618ee2c-6bb4-4850-9813-87eddb75218f)

**Comment by YuLun-bili** [comment]
@Super-Wimp disable other mods before reporting as a bug. This doesn't happen in vanilla game thus not a bug.

**Comment by Super-Wimp** [comment]
disabled all mods 

https://github.com/user-attachments/assets/da61361c-d275-4733-8354-c8986a7394ed
Result
https://github.com/user-attachments/assets/dea8e8df-31dc-4d5a-ba3c-7f9b7a3d14e7

**Comment by YuLun-bili** [comment]
Oh I forgot to mention that the tools in vanilla campaign saves their data in savegame thus disabling mods would have no/minor difference. Best way to test is to have a fresh new savegame profile and check them with unlock all in options.

But as I said, it doesn't happen in vanilla game thus not a bug.

**Comment by Super-Wimp** [comment]
I cant even edit my save game so is my save game corrupted

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Super-Wimp** [comment]
Well and I have get all tools and unlock all sandbox maps enabled even though I did the champagne and extensions and the new releases

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Super-Wimp** [comment]
I have a question about the max Score what is the max score you can get in teardown because i cant gett any higher than 204 and in the wiki it say the max is 211
 and do the challenges ad score
