### ISSUE TITLE
[Bug] Using Spawn many times will hide your weapon

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#125]
### Describe the bug

Using Spawn many times will hide your weapon/tool.

### Steps to reproduce the behavior

1. Use spawn
2. Many times
3. 2-3 its ok
4. but more than 10 maybe
5. will hide your curent tool and will show only dot in the center

### Expected behavior

Tool should be visible all the time

### Environment

- Teardown Version [e.g. 0.9.3) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows]
- GPU: 2080 ti
- Graphics driver version:
- CPU: Intel 12900k

**Comment by tuxedolabs** [comment]
Found the problem and fixed it. Thanks!
