### ISSUE TITLE
[Feature] 1. Ability to "spawn" in scripts in sandbox and music player for sandbox. 2. Group (nont-content mod) menus like weather, spawning, and modded menus from the pause menu inside it's own menu menu called "mod menu" (that's a lot of menus)

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#126]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

1. fun!
2. Makes pause menu more tidy, and witch mods some buttons might go offscreen and it doesn't look good

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by lazyRares** [comment]
You can download mods (or make one) with a spawnable radio that plays custom music, that way you can bring it wherever you want and it can play music thats custom.

**Comment by tuxedolabs** [comment]
1) You can already do this. Just create a prefab with the music player script and it should work
2) I don't think this is a big issue, but we might want to improve the navigation a bit in the pause menu bar when there are a lot of mods adding stuff there (currently only scrolling with mouse wheel is supported)
