### ISSUE TITLE
Movement key stuck when rotating spawn object

### ISSUE THREAD

**Issue by RoverBot-Dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#127]
### Describe the bug

If you move, and then hold RMB to rotate the object, that movement key will be stuck until you release RMB.

### Steps to reproduce the behavior

1. Go to the spawn menu
2. Spawn anything
3. While spawning, move forward or any other direction
4. Keep moving forward, then hold RMB
5. Release the movement key and hold RMB
6. See the player still move.

### Expected behavior

Rotating should Either stop the player from moving, or not make the keys stuck

### Environment

- Teardown Version 0.9.3
- OS: Linux
- GPU: GeForce 920MX
- Graphics driver version: 495.46
- CPU:Intel i3-7100U
-

**Comment by tuxedolabs** [comment]
Fixed in 0.9.4. Thanks!
