### ISSUE TITLE
[Feature] Add ability to rotate while spawning not only Y axis (z in all 3d programs) but in X axis 

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#128]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Add ability to rotate whyle spawning not only Y axis (z in all 3d programs) but in X axis 
like rotate changing angle... 

### Describe the solution you'd like

Whyle holding RMB move mouse Up or Down to change angle of spawned object... 
![изображение_2022-02-17_125640](https://user-images.githubusercontent.com/98832021/154451308-fe92a080-ae60-4731-a486-e6151f20eecd.png)

### Describe alternatives you've considered

no alternatives)

**Comment by tuxedolabs** [comment]
I tried this but it got very confusing, so the current approach is by design.

**Comment by Zagdima** [comment]
maybe you can try smth from Spawn Revisited V1.1 mod, which has roation, fixed last item in list not fully visible, if not choosing item window not closing etc?
