### ISSUE TITLE
[Bug] Sledgehammer swings can be stored by swapping weapons.

### ISSUE THREAD

**Issue by TheGibusGuy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#13]
Description:
By swapping weapons hammer swings can be stored.

Reproducing:
1. Start a sledgehammer swing
2. Swap to any weapon partway through the swing
3. Swap back to the sledgehammer

Expected behavior:
I expected the sledgehammer to be in an idle state when I swapped back to it.

Screenshots:
https://user-images.githubusercontent.com/77648657/111432645-6064af80-86a1-11eb-839f-301cf4e0d3ac.mp4

Environment:
 - Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
 - OS: Windows
 - GPU: GPU 0 NVIDIA GeForce GTX 1660
 - CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz, 2904 Mhz, 6 Core(s), 6 Logical Processor(s)

Additional context:
This isn't too significant but I've blown myself up by hitting propane tanks because of this.

**Comment by tuxedolabs** [comment]
Thsi is fixed in 0.7.0
