### ISSUE TITLE
[Bug] Player 1st person vehicle camera shake doesnt respect with headbob settings in options

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#130]
### Describe the bug

i believe the 1st person vehicle camera shake is smth new, i like it, but i think theres some oversight
when the player is doing a LOT of aggresive driving, the shake can became very... violent? and headbob which is supposed to reduce camera shake doesnt effect that new feature

### Steps to reproduce the behavior

1. Lower headbob in option to 0
2. drive car aggressively
3. change to 1st person cam
4. camera shift violently

### Expected behavior

no or very little camera shift

### Environment

- Teardown Version 0.9.3
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

### Additional context

(by the way what is the ummm the area a camera now need to makesure that the view wont clip into seats or the roof when its shifting around?)

**Comment by tuxedolabs** [comment]
Very good point. I have changed it to scale with headbob setting. I also reduced maximum bob distance to one voxel.
