### ISSUE TITLE
Trying to spawn a vox script crashes the game.

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#131]
### Describe the bug

Attempting to **spawn** a prefab containing a **voxscript** not being parented by a body result in a game **crash**.

### Steps to reproduce the behavior

1. Open the game on the experimental **version 9.3**.
2. Unzip [Bug-Report.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/8099758/Bug-Report.zip) in your mods folder.
5. Enter a level.
6. Open the spawn menu.
7. Find the section "**Bug**" and the object "**Vox Script**".
8. Spawn the object.

### Expected behavior

- An invisible object spawns.
- The object generated by the voxscript spawns.

### Environment

- Teardown Version : **9.3 Experimental**
- OS : **Windows**
- GPU : **Radeon RX 570 Series**
- Graphics driver version : **22.1.1**
- CPU : **i5-3570**

**Comment by nooitaf** [comment]
Voxscript works. 
You just have to put it inside a body.

**Comment by Xless-Qu-dev** [comment]
> Voxscript works. You just have to put it inside a body.
> 
> ```
> <prefab version="0.9.3">
> 	<group>
> 		<body dynamic="true">
> 			<voxscript file="MOD/voxscript.lua">
> 			</voxscript>
> 		</body>
> 	</group>
> </prefab>
> ```

Thank! I will add that to the description.

**Comment by tuxedolabs** [comment]
This was actually a bug in the parser, not creating an intermediate body for voxscripts during spawn. Fixed in 0.9.4. Thanks for reporting!
