### ISSUE TITLE
[Feature] Post-Processing filters

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#133]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

this should be more useful mod-wise, and it could be useful to make for example
- jpeg compression filter
- noise filter
- color abberation filter
- blur filter
- pixel filter
i know it might be a stupid request but again : for mods trying to do something else than destruction, it might be very useful

### Describe the solution you'd like

.

### Describe alternatives you've considered

ui overlay but it doesn't look good

**Comment by tuxedolabs** [comment]
I think this is beyond the scope of teardown modding. There is already some post processing effects you can apple (add post processing node in editor, and also available through scripting)
