### ISSUE TITLE
[Bug] "Apply properties" does not work

### ISSUE THREAD

**Issue by Smart-Fella** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#134]
### Describe the bug

Instead of an appropriate window, a blank window titled "Debug" without content appears. (see image below)
![Screenshot 2022-02-19 161850](https://user-images.githubusercontent.com/96347680/154809260-71eb70d1-6078-43b5-a0f0-57ed250d406b.png)

### Steps to reproduce the behavior

1. Open the editor on any level
2. Right click on any object
3. Select "Apply properties..."

### Expected behavior

A window with 2 text boxes, a check box and other items will appear.

### Environment

- Teardown Version: 0.7.3 experimental
- OS: Windows 10 21H2
- GPU: NVIDIA GeForce GTX 1660 Ti
- Graphics driver version:
- CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz

**Comment by tuxedolabs** [comment]
I can not reproduce this on 0.9.
