### ISSUE TITLE
[Feature] Get true system time

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#135]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I want to be able to compute true FPS and to be able to benchmark some code sections I wrote.

### Describe the solution you'd like

Add another API function that would return actual system time with high enough precision, so that we can compute actual FPS even when the game runs slow. I am aware this function could return aberrant results in case the game is paused and alt+tabbed, so maybe add some keyword like "debug" in the function name to make it clear that this should be used with caution.

### Describe alternatives you've considered

No workaround I could find

### Additional context

Follow up on ticket #83

**Comment by tuxedolabs** [comment]
This has been requested in the past and I can see the need for it. I'm planning to add a script profiler at some point so you can see how much time is being spent in the various scripts. Would that solve the issue?

**Comment by FlorentP42** [comment]
So is this abandoned then with the new profiling tool ):
Or do we have a super secret API function to finally get that time and enable self-balancing-FPS scripts? :p

**Comment by squarebracket-s** [comment]
> So is this abandoned then with the new profiling tool ): Or do we have a super secret API function to finally get that time and enable self-balancing-FPS scripts? :p

Didn't know there was one. How do I even open it?

**Comment by FlorentP42** [comment]
According to Discord it's F3 when playing a map from the editor and Alt+Shift+F3 on any map ingame.

**Comment by FlorentP42** [comment]
I think the combination of #83 and #384 would properly solve this ticket so I will close it for now :)
