### ISSUE TITLE
[Question] Is there an efficient way to get the closest point that in not unbreakable?

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#136]
**Question**
I am aware of the GetBodyClosestPoint(), GetShapeClosestPoint() and QueryClosestPoint() function that can get the closest point of any particular object.

So I can query all bodies in an area and then ignore entire objects if they have the "unbreakable" tag which solves half of the issue...

Then what about unbreakable materials? What if an object is composed of both breakable and unbreakable materials (eg: a car), how am I supposed to get the closest point that is NOT unbreakable?

Please don't answer by browsing every single voxel of the shape one by one, that would definitely take forever on very large shapes (eg: the world map main shape).

Follow-up on ticket #80

**Comment by tuxedolabs** [comment]
The answer is to browse every single voxel :) I'm not sure about the use case here, but you would typically want some maximum radius anyway, and browsing voxels within that radius shouldn't be that slow. Compute proper bounds and use GetShapeMaterialAtIndex.

**Comment by FlorentP42** [comment]
I think I am missing something really obvious here and I will feel stupid when I finally figure it out...

But is there a way to compute the list of voxel indexes that are inside a given radius from a point without testing every single possible voxel position in the shape one by one?

In example below:
![image](https://user-images.githubusercontent.com/45787476/155372228-dc25f12d-17cd-4fcd-a265-85e9582c1d70.png)
Is there a way to get the list of voxels painted in yellow without testing every single position in the green square (bbox) to see if it's in the blue cirecle or not?
