### ISSUE TITLE
[Feature] API function IsBodyJointedToBody()

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#137]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

We already have `IsBodyJointedToStatic()` function so I think it could worth to add another similar function

### Describe the solution you'd like

`IsBodyJointedToBody()` function would check if two bodies are connected in any form, this would be very handy to make something like a detached mechanical arm non-functional while the arm itself is not broken.

Parameters would be handles of bodies and returns a boolean

### Describe alternatives you've considered

No alternative ideas

**Comment by TTFH** [comment]
You can use something like this as a workaround, it'll not work for ropes, and it's not really efficient since it has to iterate over every attached body.
```lua
function HasValue(tab, value)
  for _, val in ipairs(tab) do
    if val == value then
      return true
    end
  end
  return false
end

function IsBodyJointedToBody(body1, body2)
  local jointed_bodies = GetJointedBodies(body1)
  return HasValue(jointed_bodies, body2)
end
```

**Comment by tuxedolabs** [comment]
I think this is a rather specific request that can be implemented in script as noted above.
