### ISSUE TITLE
[Bug] Last Item in spawn menu not display properly

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#138]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/154900585-d1c98fc0-51f6-4826-b314-230589e2d042.png)
when you have subscribed to quite some mods

### Steps to reproduce the behavior

0. Have lots of mods with lots of category with lots of items
1. Go to spawn menu
2. scroll to bottom
3. SEE ONLY UPPER

### Expected behavior

also see lower

### Environment

- Teardown Version: 0.9.3
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Fixed in 0.9.4. Thanks!
