### ISSUE TITLE
[Documentation] Read sowly, mate, sow and steady

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#139]
### Document to improve

https://teardowngame.com/experimental/api.html#ParticleDrag
https://teardowngame.com/modding/api.html#ParticleDrag

### Enhancement

slow

**Comment by tuxedolabs** [comment]
Fixed in 0.9.4. Thanks!
