### ISSUE TITLE
[Bug] Bombs float in air when blowing up while connected to the main computer in the campaign 

### ISSUE THREAD

**Issue by GGProGaming** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#14]
**Describe the bug**
Bombs will float in midair and become indestructible. 

**To Reproduce**
1. Go into the campaign 
2. equip the bomb tool
3. put a bomb on the computer
4. spam more bombs on that first one.

**Expected behavior**
The bombs will float in midair stuck and unbreakable after blowing up.

**Screenshots**

**Environment**
 - Teardown Version [e.g. 0.6.2 (patch 1)
 - OS: N/A
 - GPU: N/A
 - Graphics driver version: N/A
 - CPU: N/A

**Additional context**

**Comment by tuxedolabs** [comment]
Should be fixed in 0.7.0
