### ISSUE TITLE
[Question] Locations on vehicles

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#140]
For now, all locations inside any vehicle are deleted and cannot be accessed by lua scripts, is there any technical limitations of making locations accessible or even move along with vehicles?

**Comment by nooitaf** [comment]
Locations never move with their parent. You can also not set location transforms. 
I assume the location offsets to the body get saved in global variables and then deleted once the vehicle is initiated.  

You can get the driver position though...
```lua
pos = GetVehicleDriverPos(vehicle)
```

**Comment by tuxedolabs** [comment]
Vehicle locations are read at vehicle load time and then removed, so they cannot be queried. If you want to access custom locations, place them outside the vehicle (but bear in mind that they won't move with the vehicle as nooitaf points out, so you have to transform them into vehicle space and then back)

**Comment by CrazyFluffyPony** [comment]
@tuxedolabs could you add this to the "help" section inside the editor please?

I also don't really understand why <locations> cannot move with their parents (they show exactly that behaviour inside the editor). The only nice alternative i have now is using a <vox> of size 1x1x1 (which is missing the nice yellow direction indicator)?
