### ISSUE TITLE
Villa Gordon Bed Issue [Pieces Scattered][Bug] ISSUE TITLE HERE

### ISSUE THREAD

**Issue by catcooltr** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#141]
### Describe the bug

In the villa gordon map there is a bed on the second floor - for some reason the patterned pieces are scattered all over
![Screenshot 2022-02-22 184049](https://user-images.githubusercontent.com/60992655/155238354-ea059cd0-71da-490a-98d7-545d729e0536.png)
Not sure if someone got really involved in the sheets, or if this just an odd bug.

It seems to happen every time I load in the map - I tried hitting the restart button once to see if it was a onetime thing, that did not fix it.

### Steps to reproduce the behavior

It happens every time I load in the map.

### Expected behavior

I would expect the bed to load in normally without pieces scattered across the room.

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1)]: 0.9.2 (patch 1)
- OS: [e.g. Windows/Linux] Windows 11
- GPU: GeForce GTX 1660 Ti
- Graphics driver version: 471.35
- CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz

**Comment by nooitaf** [comment]
LoL.. this is just a messy room. It's pieces of clothing. Nothing wrong with it ;)

**Comment by Please-Pick-a-Name** [comment]
its just... clothes... bruh

**Comment by tuxedolabs** [comment]
Freyas dirty laundry!
