### ISSUE TITLE
[Feature] returns voxel pbr for GetShapeMaterialAtPosition, GetShapeMaterialAtIndex

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#142]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

i feels like this is just again another oversight, cause this would allow lets say laser reflects with just normal high reflective material, or for when you try to copy a vox shape, you dont want the shape you copied to end up all diffuse material

### Describe the solution you'd like

let these function also returns the Reflectivity, Shininess, Metalness, Emissive property

### Describe alternatives you've considered

no

**Comment by nooitaf** [comment]
Also a texture getter would be nice, as those change how the shape looks like in game too.

**Comment by Thomasims** [comment]
`GetShapeMaterial` added in 1.4.0 returns PBR values, you can get the entry for it with the 6th return value of `GetShapeMaterialAtPosition/Index`
