### ISSUE TITLE
[Bug] Opening an empty xml file would crash editor

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#143]
### Describe the bug

If you manually create an empty `main.xml` (or any name but empty `.xml` file) then trying to edit it, editor will crash.

### Steps to reproduce the behavior

1. Create an empty `.xml` file manually
2. Start game and use editor to open it
3. Game crashes

### Expected behavior

Actually I have two solutions

1. Notify user that this file is completely empty and reject to open it.
2. Automatically fill in this file with a `<scene>` to prevent crashing before loading it, then load this file normally.

I'm not sure which one is better so leave it to you :D.

### Environment

- Teardown [experimental] 0.9.3
- OS: Windows 11 (updated from Win 10)
- GPU: NVIDIA GeForce MX250
- Graphics driver version: 511.79
- CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz

**Comment by tuxedolabs** [comment]
Thanks, I've fixed this in 0.9.6
