### ISSUE TITLE
[Feature] Extend 'static' spawning to all bodies

### ISSUE THREAD

**Issue by Thomasims** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#144]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Currently, the new `Spawn()` function allows you to add entities to the world body using its `allowStatic` argument, it's quite useful by itself for certain use-cases but this implementation seems unnecessarily limited.
Why is it that we're allowed to "attach" things to the world and only the world when bombs and other such tools show us there's no engine limitation there?

### Describe the solution you'd like

I see two main ways to do this:
- Modify `Spawn()` to take in an optional body entity handle, for instance turning `allowStatic` into a handle argument while still handling 'true' as meaning the world body.
- Splitting off this functionality into its own function, such as a `MergeBody(bodyA, bodyB)` which would simply take everything under `bodyB` and move it to `bodyA` while keeping world-space positions consistent.

### Describe alternatives you've considered

There's a few workarounds that result in varying amounts of success depending on the use-case (Scripted constraints, Manual repeated positioning, Creating joints, ...) but in some use-cases none of these are able to reach a satisfactory end result.

### Additional context

This video shows one of the short-comings of the alternatives in my current use-case:

https://user-images.githubusercontent.com/3007463/155431503-9cdc7fc3-6862-4a0c-9566-4e72a0e60aca.mp4

EDIT: To clarify, the video above is showing an attempt at making the screen entity follow the tool body.

**Comment by tuxedolabs** [comment]
It's a good idea, I can see how that would be useful, but this is probably post 1.0

**Comment by LaBe92** [comment]
I would add that it would be useful if this could work backward eg if you do BodyC = MergeBody(bodyA, bodyB), then I would also like bodylist = Split(BodyC). (would return an array of 2 bodies each according to the shapes that were originally merged into C, would return BodyC if it was never merged in the first place)

**Comment by Thomasims** [comment]
Yes splitting shapes into bodies would be nice to have although in that case I'd rather have a way to extract a given shape rather than always splitting the body into all its constituent shapes.
That said I did not include that feature in this request since I wanted to keep it minimal as I (perhaps wrongly?) assumed extending the static spawning to other bodies wouldn't be too difficult.
