### ISSUE TITLE
[Feature] XML Dependency Support... Again

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#145]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

its not exactly a problem im facing rightnow, but i can see how its needed already
the well known mega prop pack that everyone loves have a massive size of 68mb, for all the assets it contains, if its just one map uses this assets, then you will store one of those 68mb
but subbing to only 1 map is boring and naive, you subed to 10 maps, and now it becames a problem, cause you have over half GB of space wasted for repeated content. and if the assets received an update to fix numerus broken stuff, you have to repaste the entire folder again, which isnt exactly bad on itself, but the fact of knowing that there was an update, and the ability to push out update anytime is pain

not just that, say you want to spawn an instance that is from another mod, you can do that now already, yes? now what if you want to package the entire instance inside a group so you can apply a texture over it? no, cause all we get for XML is MOD/ and LEVEL/

### Describe the solution you'd like

some sort of ways for xml to use files from other mod, by using the steam item id, maybe like mod_id_number/folder1/folder2/voxel.vox, idk, as long as its documented

### Describe alternatives you've considered

copy paste folder, horrible large, update is painful

### Additional context

i know theres a long chain of discussion of this before, i feel like now we can talk about this more with how the game is now able to handle getting files from another mod for the spawning menu

**Comment by YuLun-bili** [comment]
I think this can be extended to `.lua` files as well since only few people can make amazing assets while write fantastic scripts for them. And recently MrRare released a light spawner mod which is designed to help those who are less experienced in lua and you have to copy it's file to use it, which means you have to manually check for updates.

Although in lua we can use something tricky like `#include "../MOD_ID/someFile.lua"`, it's still a helpful thing to implement

**Comment by tuxedolabs** [comment]
This has been discussed at length and my opinion still stands - mod dependencies is a bad idea. The download dependency itself is not a big problem (but still a problem). The real headaches start when the dependency mods update and old mods stop working correctly. In a modding community, people come and go and not everyone is interested in updating old mods to work again, and soon enough, half of the mods in workshop will be non-functional.
