### ISSUE TITLE
[Bug] floating building in hollow rock

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#146]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/155909116-071557f5-5f12-432c-8236-89122f7a6b3a.png)
i wonder how and when did this happened

### Steps to reproduce the behavior

1. Go to hollow rock
2. Go to the big white lab building
3. see error

### Expected behavior

no gap

### Environment

- Teardown Version: 0.9.4 (patch 1)
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

repost from discord
https://discord.com/channels/760105076755922996/766578005942206466/947575808128594020

**Comment by tuxedolabs** [comment]
Fixed in 0.9.5. Thanks for reporting!
