### ISSUE TITLE
[Bug] UiWordWrap  A nill value

### ISSUE THREAD

**Issue by elboydo** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#148]
### Describe the bug

Function when used in UI provides above response. 

(this could be bad usage but is seen based on ingame response

### Steps to reproduce the behavior

create text in ui, use above function, see error message

### Expected behavior

ui would fit text vertically when broken without error message

### Environment

experimental teardown branch (as of 20220228)

**Comment by TTFH** [comment]
Did you type the name of the function correctly? This code works on 0.9.4 (patch 1) for me
```lua
function draw()
	UiTranslate(120, UiHeight() - 150)
	UiFont("bold.ttf", 30)
	UiWordWrap(200)
	UiText("Some really long text that will get wrapped into several lines")
end
```

**Comment by elboydo** [comment]
User error
