### ISSUE TITLE
[Bug] Invisible textures on mission "ROBORAZZI"

### ISSUE THREAD

**Issue by nngv** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#149]
### Describe the bug

After opening the 'ROBORAZZI' mission, half of the textures on the map disappear. After the exit, all textures are returned. On other missions / maps this is not observed.

![teardown_KXHi802dFP](https://user-images.githubusercontent.com/100778645/156375257-0b1fc277-7d11-4d03-aace-cf91bc8ee66f.png)
![teardown_07aFnazMx1](https://user-images.githubusercontent.com/100778645/156375323-0edd3c3a-30b6-45cb-8c80-36e61dc4ea71.png)
![teardown_jML60NalHM](https://user-images.githubusercontent.com/100778645/156375331-2e08ebe4-22e9-417e-89d8-4c6eccbe6c4f.png)
![teardown_ewsjIoKpmx](https://user-images.githubusercontent.com/100778645/156375357-f97a5015-0940-40c2-9b35-ef9d002e9081.png)

### Steps to reproduce the behavior

1. Go to 'Campaign'
2. Click on 'mission ROBORAZZI'
3. See error

### Expected behavior

I was expecting full visibility of the textures and a full experience from the game.

### Environment

- Teardown Version 0.9.5
- OS: win 10
- GPU: NVIDIA GeForce GT 630
- Graphics driver version: NVidia GeForce GT 640 Game Ready Driver v.472.98
- CPU:AMD Phenom(tm) II X2 545 Processor   3.00 GHz

### Additional context

It can't be due to the specs as any other maps load smoothly and have all the textures.

**Comment by tuxedolabs** [comment]
Quilez is the largest maps and this is very likely due to your machine being below minimum specs :-(
