### ISSUE TITLE
[Feature] Create joints at runtime

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#151]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Basically, a way to make your own modded ropes, as well as sticking shapes together easily.

### Describe the solution you'd like

`joint = JointShapes(shape1, shape2, type, ???)`
Lets you create a joint between two shapes, extra parameters may be required depending on the joint type.

### Describe alternatives you've considered

It is possible to emulate connection between two shapes through other functions already, but it's not as easy as using a joint handle, nor does it provide the whole "breaking" options if too much force is applies to a joint for example as well as the motor behaviors.

**Comment by nooitaf** [comment]
Can't you just Spawn() a joint and enable the jointExisting property?

**Comment by FlorentP42** [comment]
You are right, for some resons I thought joint would require the name of the shape they stick to in order to work, but aparently they don't, so spawning them works fine :)
