### ISSUE TITLE
[Bug] Clipping disorder when using UiWindow inside another UiWindow and contents overlap with edges

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#153]
### Describe the bug

use a second `UiWindow` function inside a `UiWindow` function would cause clipping issues, the second window doesn't follow first window's clipping setup.

### Steps to reproduce the behavior

1. Write two simple functions using `UiWindow`
2. Cut and paste one window into the other one
3. Change translation of inner window and let it overlaps with outer window's edges
4. See error: Contents inside second window showing up outside outer window edges

for an easier understanding of what would happen see this pic below:

![屏幕截图 2022-03-04 084650](https://user-images.githubusercontent.com/70589524/156730075-4f3a844f-942b-47b6-a43f-4eb402262aac.png)

### Expected behavior

Inner window should be clipped by outer window

### Environment

- Teardown 0.9.5
- OS: Windows 11 (updated from Win 10)
- GPU: NVIDIA GeForce MX250
- Graphics driver version: 511.79
- CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 1.80 GHz

### Additional context

I have to say it might be uncommon to use more than two layers of windows therefore having windows clipping with each other is extremely rare, I discovered this bug only by accident when adjusting my mod UI, so compared to potential difficulties of fixing I can accept this bug

**Comment by tuxedolabs** [comment]
It's an engine limitation to only have one clip-rect and I see very few cases where this cannot be worked around fairly easily, so closing this.
