### ISSUE TITLE
[Feature] please add autosave

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#155]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

i just lost all my progress on a thing i made because my computer froze, and i don't have the habit of saving when i'm concentrated on something so i lost it all, PLEASE add an autosave option because this is super annoying

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by YuLun-bili** [comment]
the editor have something similar to autosave feature, the `temp.xml` is the copy of last edit of map before last F5 play, this file is saved same place with your `savegame.xml`

Autosave is good indeed, but I can't think of any good methods of implementing it, save a copy into mod folder? Just remember to `Ctrl+S` :D

**Comment by tuxedolabs** [comment]
Auto-save in the game would unfortunately cause very significant stuttering because of how the save system works, so not an option. Auto-save in the editor would be possible, but I'm not sure it's necessary since as mentioned above, it already does that every time you preview the level.
