### ISSUE TITLE
[Bug] You can enable/disable 2 mods at the same time

### ISSUE THREAD

**Issue by Tresquel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#156]
### Describe the bug

It's in a very precise spot and very hard to get but it happens anyway:

https://user-images.githubusercontent.com/43729305/156885038-8cff2b2f-f422-47c5-a40f-71fb86d00d81.mp4

### Steps to reproduce the behavior

1. Go into the mods tab
2. Click in a very precise spot
3. Observe how 2 mods get enabled or disabled

### Expected behavior

One mod gets enabled or disabled

### Environment

- Teardown Version 0.9.5
- OS: Windows 10 21H2 (build: 19044.1566)
- GPU: 3050ti mobile
- Graphics driver version: 511.79
- CPU: i7 11800H

**Comment by Please-Pick-a-Name** [comment]
nolonger possible with the new ui revamp
@Thomasims close this issue ig
