### ISSUE TITLE
[Bug] HUD box not fully white

### ISSUE THREAD

**Issue by ponei** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#158]
### Describe the bug

`box-solid-10` has some transparent black pixels around the box.
This is visible in-game whenever the texture is used. You can see it more clearly with white backgrounds.
Example of cash counter:
![Code_ZxJ4NfJYVq-1](https://user-images.githubusercontent.com/28790957/156966727-633feb21-613e-4e4e-9ad6-22a1f9bedd86.png)
Black pixels:
https://user-images.githubusercontent.com/28790957/156966735-7f05567f-ab76-4ee4-879b-f7f559974676.mp4

### Steps to reproduce the behavior

1. See any component using the asset. (Cash counter, level counter, etc.)

### Expected behavior

Fully white box :^)

### Environment

- Teardown Version: 0.9.5

**Comment by YuLun-bili** [comment]
I'd say it's resolved in 1.5.4 (maybe earlier)
*filled fully transparent pixels with orange
<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/018e559e-fa6b-4d41-8b77-94bc546e679d" width="450px">
