### ISSUE TITLE
[Bug] "The login devices"  fence gate noclip

### ISSUE THREAD

**Issue by AstelXD** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#160]
### Describe the bug

I found a glitch where in the fence gate on "The login devices" mission where if you pull the fence gate towards you and walk, you will noclip through it

### Steps to reproduce the behavior

1. Enter "The login devices" mission
2. Go to the main gate
3. Grab the gate with RMB and bring it towards you while walking forward
4. You succesfully no-clipped trough the fence gate

https://user-images.githubusercontent.com/89225840/157142075-101ec8e7-fa45-4c50-ac14-a1c1e1beaba7.mp4

### Expected behavior

The fence gate should be completely solid and you shouldn't be able to walk through it

### Environment

- Teardown Version 0.9.5
- OS: Windows 11
- GPU: GTX 1650 Max-Q
- Graphics driver version: NVIDIA 511.79
- CPU: Intel Core i7-9750H

**Comment by tuxedolabs** [comment]
This is an engine limitation. Hard to get right and a fine balance between clipping through objects and prevent prop flying.
