### ISSUE TITLE
[Feature] Add AMD FidelityFX Super Resolution

### ISSUE THREAD

**Issue by AstelXD** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#161]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Teardown has very poor performance, and making the resolution lower makes fps a lot better, and that is good, but it makes the game look a lot worse.

### Describe the solution you'd like

Add AMD FidelityFX Super Resolution.
FidelityFX Super Resolution (AKA. FSR) upscales a game from a lower res to a higher res without losing FPS or image quality (Just like Nvidia's DLSS). It works on almost any gpu and it could get added pretty easily to the game, making FPS a lot better.

### Describe alternatives you've considered

Nvidia's Deep Learning Super Sampling (DLSS)

It's even better than FSR, But it only works on Nvidia 20 and 30 series, which are pretty hard and expensive to get.

### Additional context

I used an external app (Lossless Scaling) to upscale Teardown from 1280x720 to 1920x1080 and gained a lot of performance without any image quality loss, and thus, i would love to see it implemented natively on Teardown.

**Comment by tuxedolabs** [comment]
Not available for OpenGL, but I'd like to look into my own implementation at some point.
