### ISSUE TITLE
[Bug] Mod menu glitches and inconsistencies

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#162]
### Describe the bug

1. **Built-in** mods **names** and **descriptions** are **inconsistent** between each other.
2. **Built-in** mods list has the enabled indication(the circle next to a mod) cut.
3. **Local Global** mods have the publish button floating.
4. **Built-in**, **Local** and **Subscribed** mods are sticking out of the container(grey box) on both sides(Subscribed only stick out on bottom).
5. The scroll bar automatically moves down a little if clicked.

### Steps to reproduce the behavior

1. While in the main menu press the **"Play"** button.
6. Next, press the **"Mods"** button.
7. Finally, click one by one on every built-in mod and compare the name and description.

### Expected behavior

The following mods name or/and description has to be changed to maintain consistency

1. **Banana Bomb**
    - [ ] Description missing **"."** at the end.
2. **Basic**
    - [ ] Description missing **"."** at the end.
3. **Castle**
    - [ ] Description missing **"."** at the end.
8. **Debug info**
    - [ ] Description missing **"."** at the end.
    - [ ] Name not in **uppercase**.
9. **Drive to survive**
    - [ ] Name not in **uppercase**.
10. **Jetpack**
    - [ ] Description missing **"."** at the end.
11. **Laser Gun**
    - [ ] Description is cut at the end.
12. **Simple house**
    - [ ] Description missing **"."** at the end.
    - [ ] Name not in **uppercase**.
13. **Slow-motion**
    - [ ] Description missing **"."** at the end.
14. **Speedometer**
    - [ ] Description missing **"."** at the end.
15. **Vehicle booster**
    - [ ] Description missing **"."** at the end.
    - [ ] Name not in **uppercase**.

The Built-in mods circle indicator shoudn't be cut

**Glitches :**
![Capture d’écran (658) - Copie](https://user-images.githubusercontent.com/52052170/157521677-b08e0298-9306-4aca-ab20-dd6d4eb3f6de.png)
![Capture d’écran (659) - Copie](https://user-images.githubusercontent.com/52052170/157521747-41827cfc-f8be-4694-80ad-4fc398c6c93a.png)
### Environment

- Teardown Version: **0.9.5**

**Comment by tuxedolabs** [comment]
Thanks, I really appreciate this. I have cleaned up the mess for 0.9.6
