### ISSUE TITLE
[Bug] [Editor] Paste in place on instance actually pastes into the instance

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#164]
### Describe the bug

"Paste in place" on [instance] actually pastes into the instance object. 

### Steps to reproduce the behavior

1. Go to Editor
2. Create an [instance]
3. Create something else
4. Copy something else
5. Select [instance]
6. Past in place
7. Pasted stuff is now inside the [instance]
8. Create Group from [instance] to see it's there

### Expected behavior

Paste into hierachy below [instance] or not have that option at all?

### Environment

- Teardown Version 0.9.5
- OS: Linux

**Comment by tuxedolabs** [comment]
Good find, the correct behavior would be to not allow pasting on an instance without first converting it to a group. I'll make the change for 0.9.6.
