### ISSUE TITLE
[Bug] [Editor] Default value screen size includes comma

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#166]
### Describe the bug

The default value of [screen] in the editor includes a comma.

![image](https://user-images.githubusercontent.com/1898194/158095477-0f59b29a-b40f-403a-bed5-ddbedcd247c6.png)

### Expected behavior

no comma

### Environment

- Teardown Version 0.9.5

**Comment by tuxedolabs** [comment]
You are absolutely right. Thanks! I'll fix it for 0.9.6
