### ISSUE TITLE
[Bug] Infinite velocity/position with "bhopping" 

### ISSUE THREAD

**Issue by Tresquel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#167]
### Describe the bug

By having a long flat map you can get a *lot* of speed by bhopping and if you hit a wall with that velocity [this](https://youtu.be/AOvFFoD9b68) might happen.

### Steps to reproduce the behavior

1. Get a long flat map
2. Get a bit of speed for example from a noclip mod
(bhop bug) 3. Observe how you gain speed when you're in the air

(the velocity bug) 3. Hit a wall at an angle
4. Get stuck(?) on the border
5. Observe how the game gives you speed until you shoot up and eventually crashing

### Expected behavior

Not gaining a lot of speed.

### Environment

- Teardown Version 0.9.5
- OS: Windows 10 21H2 (build: 19044.1566)
- GPU: 3050ti mobile
- Graphics driver version: 511.79
- CPU: i7 11800H

### Additional context

Here's the map that I made where the bug happened
[Basic Copy.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/8256319/Basic.Copy.zip)

I also had a macro in my mouse that just spammed space bar cuz its hard to hit it at the exact time to bhop

**Comment by tuxedolabs** [comment]
I think this is a bit outside the scope for bugfixing. I tried this map at regular speed and verified that there is no forward speed increase at all when jumping.
