### ISSUE TITLE
[Feature] Better swiming and ability to climb.

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#168]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I imagine that it could give more **depth** and **possibilities** to the game by upgrading a core mechanic; movement.

### Describe the solution you'd like

A **review** to the movement in water; **swiming**. The ability to **dive** underwater and **swim faster**.

The ability to **grip** to an object and **move relatively**.
Ex : Gripping to the top edge of a box and climbing it up by dragging the mouse.

### Describe alternatives you've considered

Climbing up an object simply by going close to an edge and pressing a key.

**Comment by tuxedolabs** [comment]
This has been discussed at length at the beginning of the project, but we decided to not include it. I think I have seen a parkour mod do similar things though.
