### ISSUE TITLE
[Documentation] Xml prefab documentation

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#169]
### Document to improve

Does this exist somewhere already?

### Enhancement

If not can we please get a full documentation of the xml structure used to store prefabs? What are the available tags and properties for each of them, what do they do, which ones can be nested, what effect does it have when spawning the instance, etc...

**Comment by tuxedolabs** [comment]
Prefabs use the exact same format as the scene XML, there is no difference, just that the top level tag i prefab instead of scene. There are no properties or tags for prefabs, so there is nothing to document.

**Comment by FlorentP42** [comment]
Yes, my point is: I am not really familiar with the editor so I do not know how to do what I want with bodies and shapes in it, and even if I did it would take a lot of time to actually build what I want, then export it, then look at the code to figure out how it's saved in XML format...

Having a dedicated documentation would make this process way more efficient by simply using Ctrl+F in the doc, and way less painful of trial and error to attempt to get something that might not even be possible to happen in the editor ^^

So please reconsider this request 🙏

PS: Is there any doc for scene XML already that I am not aware of?
