### ISSUE TITLE
[Bug] Emissive materials don't work on newly created vox files

### ISSUE THREAD

**Issue by Thomasims** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#17]
**Describe the bug**
Creating a new Vox file in MagicaVoxel leads to emissive materials not appearing as emissive in game.

**To Reproduce**
1. Open a new blank MagicaVoxel Project.
2. Create a simple material with emissive properties (Emission > 50 and Power >= 3) and assign it to a few voxels.
3. Import the Vox file into a Teardown level.
4. The imported model will not have any emissive voxels.

**Expected behavior**
The voxels using the emissive material should glow in the dark as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/3007463/111656036-73df5a00-880a-11eb-80fd-74372db995ab.png)

**Environment**
 - Teardown 0.6.2 [patch 1]
 - OS: Windows

**Analysis**
After investigating the problem myself, I found the issue is tied to the fact that MagicaVoxel does not create the `_g` property in the MATL dictionary associated with the emissive palette index.
![image](https://user-images.githubusercontent.com/3007463/111656784-21eb0400-880b-11eb-9571-853ce73601f8.png)
Upon modifying the entry to contain a `_g` value of 0.41 (making sure of course that the file stays coherent), the new file starts behaving as expected, with its emissive material now glowing.
![image](https://user-images.githubusercontent.com/3007463/111657174-7aba9c80-880b-11eb-93e1-f9b6da89e30a.png)

I don't know the purpose of this `_g` key and why it is necessary for the game to recognize the material as emissive, but it seems to be the only thing causing this bug.

**Comment by tuxedolabs** [comment]
Thanks for the informative description. This is fixed in 0.7.0.
