### ISSUE TITLE
[Bug] Light sprites do not update in photo mode

### ISSUE THREAD

**Issue by gitburned** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#171]
### Describe the bug

Lighting sprites don't update in photo mode, meaning they do not rotate to face the camera when it's moved in photo mode, and in the case of the sun lens flare, it ends up misaligning with the skybox sun. Probably related to the update allowing lines and sprites to be seen in photo mode. Preview pics of the sun glare misaligned.
![image](https://user-images.githubusercontent.com/94071450/159201539-d579f629-8718-4f7c-9fbf-1fd84220a111.png)
![image](https://user-images.githubusercontent.com/94071450/159201545-7e9deab5-21bd-4180-bcdd-7fd03a239f5c.png)

### Steps to reproduce the behavior

1. Have lights in player's view so they render glare, maybe the sun too if there
2. Pause and go to photo mode
3. Move camera and watch as light sprites don't rotate to face camera and sun glare falls out of alignment

### Expected behavior

Light sprites should rotate to face camera in photo mode and sun glare sprite aligned with the sun even when the photo mode camera moves.

### Environment

- Teardown Version 0.9.6
- OS: Windows 11
- GPU: GTX 2060 Laptop GPU
- Graphics driver version: 511.23
- CPU: Intel i7-11800H @2.30 GHz

### Additional context

Teardown had an update alongside object spawning to render sprites in Photo mode, aimed at the lua DrawSprites, it may have had some side effects.

**Comment by Please-Pick-a-Name** [comment]
this had been fixed in 1.5.0
@Thomasims
