### ISSUE TITLE
[Feature] Make <vehicle tags="dumptruck"> hinge joints require a tag to be used

### ISSUE THREAD

**Issue by CrazyFluffyPony** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#172]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Right now, if you make a vehicle a dumptruck (via tag "dumptruck") it will take every joint of type `hinge` and use it to simulate the movable bed of a dumptruck (rotating up and down).

The problem is, it takes EVERY hinge. So it prevents me from adding any other hinge to implement my own feature. Please implement it like on the crane, where the joint that is responsible for the turning of the crane must be tagged with "turn".

Also: cranetop seems to have the same problem (whith untagged hinge joints used for the lowering/raising of the boom)

### Describe the solution you'd like

Require joints to have a special tag in order to be used as hinges for the movement of the dumptruck bed

### Describe alternatives you've considered

Do nothing

**Comment by YuLun-bili** [comment]
Just make a script your self then

**Comment by Please-Pick-a-Name** [comment]
might want the other way around instead, a tag that tell the game to ignore the joint, for backward compatibility sake

**Comment by CrazyFluffyPony** [comment]
Would be acceptable. But i still prefer to cleanup this mess before 1.0
it's EA, stuff is allowed to not be backwards compatible

**Comment by YuLun-bili** [comment]
All vanilla vehicles with special functions are designed very simple: tag to vehicle, control all joints, done. Because all vanilla vehicles just have one main body without other fancy stuff so they don't need to care about other cases

Like PPAN said, tag to ignore is a workaround for backwards compatibility, and easier to achieve so we don't have to fix every vehicle already made.

I said to 'write scripts yourself' is I think devs are very likely to reject thinking of game's relatively easy modding approach

**Comment by CrazyFluffyPony** [comment]
The fact is, that they do care about it in e.g. the crane (rotating the turret).

Is the game relatively easy to "mod"? yes
Is it easy to create a vehicle on your own? no

The ingame help includes no information about stuff like the dumptruck tag. I could not even find any website or steam guide that contains information  about those tags, how they work, what parts they require to function. You are forced to look at vehicles already existing in the game, ultimately vehicles that have been created by the devs. This is NOT simple. I am a webdev, i can figure it out, sure. But please, don't call it simple.

The other thing is, that requiring this tag would break existing creations (reminder: this is Early Access) but the only thing you have to do to fix it, is load the mod/xml file and assign the new tag to all of the hinge joints. Upload, done. No brain power required.
If this change would affect behavior (e.g. change they physics of springs) which cannot be simply fixed within 1 minute, or not all, then i would say it is problematic.

But:
The manual work mentioned above would not even be required. Every vehicle and every prefab has a version number.
A bunch of code lines and a new version, and all that manual work mentioned above happens automatically. Full backwards compatible. No problems AT ALL.



Inconsistencies in software are bad, and fixing them requires a lot of mental effort (exactly because of this backwards compatibility and "breaks existing creations" problem). But the sooner you make it consistent, the better.

**Comment by tuxedolabs** [comment]
This is something I would like to change as well, but there is too much legacy at this point and too much content using the old system. Please don't use the dumptruck tag (or other similar tags) when making your own vehicles. If you want to make a vehicle with animated parts, write a script for it. Make sure to use the "vehicleraise" and "vehiclelower" and it will work with controllers as well. You can achieve the same level of control with scripting but in a much more flexible way.
