### ISSUE TITLE
[Feature] Option to extend screen recording to more then 10k frames

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#176]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

At the moment the screen recording is limited to 10.000 frames.

### Describe the solution you'd like

Option to extend the limit, maybe even unlimited if possible.

```lua
-- change img name to 000000.jpg
-- adding max_frames (default 10k or -1 for max of 1000000) 
-- 277 Minutes should be enough for anyone (99.999%)
Command("game.screenrecord", hide_ui, max_frames)
```

### Describe alternatives you've considered

No real alternative. I could imagine doing some induced pause once the recording is done and manually moving the files away, but it's not ideal and doing that every 2.7 minutes makes it very unpractical.

**Comment by tuxedolabs** [comment]
It was designed this way to not fill up the harddrive with gigabytes of image files. I think it's unlikely to change. We're hoping to record directly to an mp4 file at some point.
