### ISSUE TITLE
[Bug] Deletion of script entity = crash

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#178]
### Describe the bug

I was trying to make a script disappear, so i scanned the Spawn items for the script entity and on `Delete(script_handle)` it crashes. That might be intended or some limitation.

The main reason for deleting that script was to stop it from receiving `handleCommand` calls. "Dead scripts" still seem to call that function and i thought that might be an issue after lots of those scripts have been spawned. Even though it does a simple boolean check to avoid doing anything with it, it's still some work that could be avoided. 

Maybe there is another way to "un-hook" a script from that call (or all calls)? Or make it die/stop in some other way.

### Steps to reproduce the behavior

1. Spawn something which is inside a script entity
2. Delete script
3. Crash

### Expected behavior

Remove script and all it's children from the tree and stop/unhook the script (after tick/update is finished)

### Environment

- Teardown Version 0.9.5

**Comment by Please-Pick-a-Name** [comment]
what crashes the game is a script deleting itself im pretty sure, since i have been utilizing a separate script that receives the scripts to delete via a registry key, and it doesnt crash the game
yes, the explanation that come almost 2 years late, sry

**Comment by Please-Pick-a-Name** [comment]
unless you want the ability to self delete, then ig reopen this, you have the perm anyways
