### ISSUE TITLE
[Bug] [Editor] Negative value in shadow volume = crash

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#179]
### Describe the bug

Negative value in shadow volume produces crash

### Steps to reproduce the behavior

1. Go to scene
2. Set any shadow volume value to negative
3. Start the map

### Expected behavior

Some sanity check for negative numbers ;)

### Environment

- Teardown Version 0.9.5

**Comment by Please-Pick-a-Name** [comment]
lmao, guess we just gonna start putting negative number in everything and see what dies lul

**Comment by tuxedolabs** [comment]
Made it at least 1 in each direction at load
