### ISSUE TITLE
[Feature] Better Support for multi-body vehicles that allow locations to follow their respective body

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#183]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I'm currently working on a articulated bus example, and i know someone who is also working on it, mainly the type that have engine and drive wheel on the rear section and the driver sits at the front section
i noticed that the exhaust and vital locations follows the main body of the vehicle instead of the body that i placed the instance in, and its weird that theres a floating smoke in midair when the bus is even just slightly turned

### Describe the solution you'd like

locations that follow their respective body instead of just main body

### Describe alternatives you've considered

keep track of the locations myself via script
doesnt work with drivevehicle function (vital/exhaust)
breaks vanilla HUD screen (player/camera)
unnatural camera behaviour (player/camera/exit)
not vanilla (all)
yes, not vanilla can be an issue aswell
if the vanilla game adds features about it, say exhaust can now have backfire, then i have to add the new backfire myself, which sometime can be painful to figure out how its done with no reference

**Comment by tuxedolabs** [comment]
I think the feature request is a bit too specific to justify implmentation. Most of it can be done with custom locations/script.

**Comment by Please-Pick-a-Name** [comment]
> I think the feature request is a bit too specific to justify implmentation. Most of it can be done with custom locations/script.

didnt i explain why script wont work already? 
but still, i can see your reasoning as those are small anyways, then i might aswell stick with vanilla location markers, cause no one gonna care about it anyways
(oh also, all locations parented under the vehicle is deleted upon level load, remember?)

**Comment by UwQ-Official** [comment]
This should be added 🥹
