### ISSUE TITLE
[Bug] Able to drag custom UI elements to another monitor

### ISSUE THREAD

**Issue by daniel-w0** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#184]
### Describe the bug

I dragged a UI Window on my other monitor and now it's gone.

### Steps to reproduce the behavior

1. Make a UI that's draggable.
2. Move the UI outside of the game window.

### Expected behavior

I would expect it to not let me drag it past the window size.

### Environment

- Teardown Version: 0.9.5
- OS: Windows
- GPU: RTX 2080 Super
- Graphics driver version: 512.15
- CPU: I7-9700K

**Comment by nooitaf** [comment]
You are lucky it resets when you restart the game :P

**Comment by daniel-w0** [comment]
> 

It doesn't though as I save the position in the mod 🤔

**Comment by nooitaf** [comment]
So it's a bug in your mod and you report it here?

**Comment by daniel-w0** [comment]
No, UI elements in general shouldn't be able to go outside the bounds but I've realised it's actually a good thing to have if you want to hide things easily. There's UiWindow that can clip but just sticking it outside the window also works.
