### ISSUE TITLE
[Feature] More music/sound control

### ISSUE THREAD

**Issue by DimasVoxel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#185]
Currently the there is a lack of fine control for music only being able to pretty much start and stop it at the moment.

Here are some ideas that would enable the modding scene to do more complex actions:

> Being able to start a loop at a specific point in the track _PlayLoop(handle, [pos], [volume], timeInSconds)_

> Being able to detect how far music has progressed with some kind of  _ProgressInSeconds = MusicStatus(handle)_ function

> Changing music volume/loudness 

I would love to hear if that's something that could become reality someday? 

Thank you very much in advance.

**Comment by MyCresta** [comment]
I hundred percent agree with this, Me and RavMahov have also requested this a while back but was ignored.

**Comment by tuxedolabs** [comment]
I'd say this is beyond the scope of Teardown :-/

**Comment by hotcocoadotcom** [comment]
> I'd say this is beyond the scope of Teardown :-/

😂
