### ISSUE TITLE
[Feature] Disable Audio When Unfocused

### ISSUE THREAD

**Issue by daniel-w0** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#187]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

When you tab out without the game being paused, the game's audio still plays.

### Describe the solution you'd like

Disable audio when tabbed out.

### Describe alternatives you've considered

None.

**Comment by tuxedolabs** [comment]
Fixed in 1.1.0
