### ISSUE TITLE
[Feature] Reload Mod / Reset Lua State

### ISSUE THREAD

**Issue by daniel-w0** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#188]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

In all of the mods I've made for other games, I've always made a way to reload the mod. I've mainly done this by checking the last update time of each file and then re-requiring that module but it's not possible in Teardown.

### Describe the solution you'd like

If a mod has been updated, reload the Lua state.

### Describe alternatives you've considered

Have a function for getting the last time a file has been modified and re-include that file.
We'll also need an include function as `#include` can be rough at times, examples;

- Syntax errors
- No errors in-game if it's a bad file
- Can't include an empty file (I do this for placeholders as I'll add code to the file later on)
- Can't include a file in a function (I'm making a modular library and I use `HasFile` but I can't include it if it exists, I just have to include it no matter what).
- `#include` doesn't work if there's a space or a tab in front of it. I was really confused why it wasn't working before so I removed the tab and it worked. There was a tab because I put the `#include` in a comment to remove the syntax errors.

**Comment by YuLun-bili** [comment]
since 1.5.4, profiler panel allows user to click select a script then either reload or reinit it, and the list got expanded so that user could select any script in scene

**Comment by daniel-w0** [comment]
> since 1.5.4, profiler panel allows user to click select a script then either reload or reinit it, and the list got expanded so that user could select any script in scene

But the profiler panel only works in the map editor, right? If so, what if you were working on a mod that had to be tested on multiple maps? You wouldn't be able to easily reload it.

**Comment by YuLun-bili** [comment]
no you can bring it out in any map with `Alt`+`Shift`+`F3`
