### ISSUE TITLE
[Bug] Weird lighting change when using spray can on the HUB beam/that's not physics. 

### ISSUE THREAD

**Issue by nathangur** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#189]
### Describe the bug

Some weird lighting changes when spray painting a beam on the hub.

https://discord.com/channels/760105076755922996/768940684199329793/959316036656705616
0:30 for the first vid

### Steps to reproduce the behavior

1. Go to 'the first view of the hub... part 1 opening'
2. Look at vids for reference of what to do.

### Expected behavior

Weird stuff

### Environment

- Teardown Version [9.5.2]
- OS: [Windows]
- GPU: 3060
- Graphics driver version: Latest
- CPU: i9

**Comment by tuxedolabs** [comment]
Too minor too fix, but thanks for reporting!
