### ISSUE TITLE
[Bug] Folding the Snap window will result in constant Debug window for Snap

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#19]
**Describe the bug**
If you fold the Snap window in the Editor it will change into Debug and no way to go back

**To Reproduce**
1. Go to Editor
2. Click on Windows > Snap
3. Fold the Window with the arrow top left
4. Changes into Debug and permanently
5. Now every time you open the Snap window it will show Debug
6. Restarting the game / verifying files doesn't remove the Debug

**Expected behavior**
Show Snap Window

**Screenshots**
![Screenshot from 2021-03-19 16-14-54](https://user-images.githubusercontent.com/1898194/111802470-4f4cb600-88ce-11eb-966c-7b7664dfe051.png)

**Environment**
 - Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
 - OS: Windows + Linux

**Comment by nooitaf** [comment]
Quick Fix:
---
Change ```Collapsed``` value to 0 in ```imgui.ini```
```ini
[Window][Snap]
Pos=400,30
Size=350,100
Collapsed=0
```

**Comment by tuxedolabs** [comment]
Fixed in 0.7.0
