### ISSUE TITLE
[Bug] Lets start with new particle effects, with some sledge

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#191]
### Describe the bug

hit particle effect should probably depends on the material getting hit also
![image](https://user-images.githubusercontent.com/81009804/161838622-aa9297bb-a701-41a0-ba85-1a1c876ad8c1.png)
maybe no sparks when sledge hits rock?
![image](https://user-images.githubusercontent.com/81009804/161837455-1777a33f-10d6-4d26-8a13-677b4a2bcdc1.png)
and maybe no smoke when sledge hits metal?

speaking of hit effect, theres also particle effect when breaking voxel
![image](https://user-images.githubusercontent.com/81009804/161837747-01420512-008d-4b73-8545-a8cea875ab91.png)
maybe the particle effect should be the color of the voxel that are been broken instead of what the player is looking at? and a little touch would be have it spawn at where the voxel is broken instead of where the player is looking at
is there expected coding limitation? yes
am i still going to post this? also yes :D

### Steps to reproduce the behavior

1. Go to any map
2. hit stuff around
3. do i even need to write this?

### Expected behavior

maybe no sparks when sledge hits rock?
and maybe no smoke when sledge hits metal?

and maybe the particle effect should be the color of the voxel that are been broken instead of what the player is looking at? and a little touch would be have it spawn at where the voxel is broken instead of where the player is looking at

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
also, that only appears for destructions directly from players. So u driving a vehicle and hit something wont show that effect

**Comment by tuxedolabs** [comment]
Sledge made of steel :)
