### ISSUE TITLE
[Bug] Small objects disapear when shot.

### ISSUE THREAD

**Issue by nathangur** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#192]
### Describe the bug

https://user-images.githubusercontent.com/84688324/161871826-57db5374-5bba-4587-9393-8a0c4e952f66.mp4

The example video shows a few Isla Estocastica on the gated part of the map disappearing even when some of the body should have been left intact.

### Steps to reproduce the behavior

1. Go to Isla Estocastica
2. Click on Shoot small props on bookshelf at security section.

### Expected behavior

Prop should disappear even when some should be left intact.

### Environment

- Teardown Version 0.9.6
- OS: Windows 11
- GPU: 3060 Laptop
- Graphics driver version: Latest
- CPU: i9 11th gen

**Comment by tuxedolabs** [comment]
By design for small objects.
