### ISSUE TITLE
Crash on entering campaing in experiemental branch.

### ISSUE THREAD

**Issue by GmrFox** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#193]
### Describe the bug

Clicking the "Campaign" option sends you to the loading screen, then the game crashes after half a second

### Steps to reproduce the behavior

Start Teardown
Click "Play"
Choose "Campaign"
Then Teardown closes instantly

### Expected behavior

Was expecting it to be loaded into the campaign menu.

### Environment

OS: Windows 10
Teardown version: 0.9.6
CPU: AMD Ryzen 5 3600 6-Core
GPU: Radeon RX 580
Graphics driver version: Driver Version
21.30.23.04-211216a-376209C

**Comment by GmrFox** [comment]
Adding that this happens on every official map

**Comment by nooitaf** [comment]
Could it be a mod issue? Did you try without any mods enabled?

**Comment by YuLun-bili** [comment]
I suggest to verify game file first bc it's more like some files went missing or broken during update

**Comment by GmrFox** [comment]
Ima try without mods

**Comment by GmrFox** [comment]
Seems like reverting back to normal and back fixed it

**Comment by nooitaf** [comment]
Then you can close this issue. (button below)
