### ISSUE TITLE
[Bug] Few little issues

### ISSUE THREAD

**Issue by Tresquel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#195]
### Describe the bug

1. A heightmap (i think) issue on Lee Chemicals
![](https://media.discordapp.net/attachments/918221095436427297/961287973742186496/unknown.png)

2. Throwing snowballs at a screen will make it move
![](https://media.discordapp.net/attachments/918221095436427297/961307583027769374/unknown.png)

3. Drinking BlueTide then interacting with a screen then waiting for the effect to dissapear will make the fov bigger than normally
![](https://media.discordapp.net/attachments/918221095436427297/961309011679006740/unknown.png)

### Steps to reproduce the behavior

Explained above, if unclear I can give more info

### Expected behavior

Those issues not being there

### Environment

- Teardown Version 0.9.6
- OS: Windows 10
- GPU: 3050ti
- Graphics driver version: 512.15
- CPU: i711800H

**Comment by Tresquel** [comment]
Also found this on Hollowrock:
![image](https://user-images.githubusercontent.com/43729305/163588745-74cfe5e1-ea8f-4d78-8c71-ebb3026e3e28.png)
![image](https://user-images.githubusercontent.com/43729305/163588765-0796197f-56d8-40a0-a8b2-a08f874a5712.png)
It's under the vent leading to the bunker.
After destroying the grass you can see into the underside of the island

**Comment by tuxedolabs** [comment]
Snowball issue was fixed in 1.0
Will probably not address the others, but thanks for reporting
