### ISSUE TITLE
[Bug] Vehicle Outline for Cargo Vehicles

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#196]
### Describe the bug

If you're driving a cargo vehicle, like a rigid body van, objects inside the rigid body are regarded as barriers to camera vision so outline is shown

### Steps to reproduce the behavior

watch this video since it explains better (discord message)

https://discord.com/channels/760105076755922996/768940642767208468/961644049150918696

### Expected behavior

no outline drawn

### Environment

- Teardown 0.9.6 experimental

**Comment by tuxedolabs** [comment]
Too minor to fix
