### ISSUE TITLE
[Bug] weird culling in cullinton

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#199]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/162367763-2f2c819b-93d4-461f-9532-e89387e64f4e.png)
![image](https://user-images.githubusercontent.com/81009804/162367849-b832c708-6869-4372-8388-eea70f1310aa.png)
the parking lot markings should probably be in the same shape as the ground, or atleast give it a nocull tag perhaps
![image](https://user-images.githubusercontent.com/81009804/162367930-7734a160-c7d9-4f67-afd5-47ce645cfe92.png)
![image](https://user-images.githubusercontent.com/81009804/162367940-2e6b8290-5ce0-499a-a6ee-093d0609dfa3.png)
the ground near this house have a line

### Steps to reproduce the behavior

1. you know how to recreate this right

### Expected behavior

no cull

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by Hallonduell** [comment]
The line near the house is a mystery but the others have been solved.
