### ISSUE TITLE
[Bug] Large vox parts disappear when damaged but still spawn debris

### ISSUE THREAD

**Issue by patStar** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#20]
**Describe the bug**
On a huge map with lots of individual models, the ground plane disappears when damaged. It is still in the game since spraying with the spraycan wont show in the game until the part that was sprayed is shooted at. (See the videos below). This is most likely issued by the amount of models on the map.

**To Reproduce**
1. Build a huge map (The one in the example is about 85MB) with lots of models
2. add a huge planar voxbox as ground
3. go in game and shoot it
4. the plane disappears but when shooting at the invisible plane it still spawns debris
(here is a map: https://discord.com/channels/760105076755922996/768940642767208468/822739333446238218)

**Expected behavior**
When shooting the plane it should stay visible like it normally does.

**Screenshots**
https://cdn.discordapp.com/attachments/768940642767208468/822735727371616266/Teardown_2021-03-20_03-35-07.mp4
https://cdn.discordapp.com/attachments/768940642767208468/822736100782243880/Teardown_2021-03-20_03-38-24.mp4

**Environment**
 - Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
 - OS: win10 home 64bit
 - GPU: GTX 1050 (Driver: 27.21.14.5167) Date 7/5/2020
 - CPU: intel I5 9300h, 8g RAM
 - teardown version..... experimental branch
**Additional context**
Could be related to the problem, that huge voxbox models wont show up in game or in editor.

**Comment by tuxedolabs** [comment]
This might be a volume texture size limitation on certain graphics cards. Don't make huge voxboxes. Split up into several smaller.
