### ISSUE TITLE
[Bug] weird CoM for the new 3 wheeler in frustrum

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#201]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/162369728-7ef9a3ee-d69b-4d31-81e1-4a90e7a6fd70.png)
when sitting still, the vehicle is tilting toward one side

the only reason i can confirm that this is a CoM error is that the handling feels weirdly smooth, not a single bit of body roll happened despite this kind of vehicle is expect to flip pretty easily

### Steps to reproduce the behavior

1. Go to frustrum sandbox
2. find 3 wheeler
3. ... honestly go check it in the editor, and check where the body node of the 3 wheeler is at relative to the vehicle, its probably off by quite a bit

### Expected behavior

stay flat when sitting still, flip when turning fast?

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
track in #278
