### ISSUE TITLE
[Documentation] Missing function descriptions in Scripting API XML

### ISSUE THREAD

**Issue by CrazyFluffyPony** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#202]
### Document to improve

https://www.teardowngame.com/modding/api.xml

The XML is missing all the descriptions of what each function doesin https://www.teardowngame.com/modding/api.html

### api.html

![image](https://user-images.githubusercontent.com/80415579/162442642-c05a013f-f1b9-4ba6-ae94-10c2d7c6881d.png)

### api.xml
```xml
<function name="GetTime">
	<output name="time" type="number" desc="The time in seconds since level was started"/>
</function>
```

api.xml is missing the whole description `Returns running time of this script. If called from update, this returns the simulated time, otherwise it returns wall time. `

### Enhancement

Include function descriptions in api.xml

**Comment by tuxedolabs** [comment]
The description can contain tables and other things that wouldn't map well to XML. The XMl is intended for editor highlighting and completion purposes and not full documentation.

**Comment by CrazyFluffyPony** [comment]
@tuxedolabs so what is the point of having autocompletion, if you always have to look at the website to read the full description (which is required to understand it)? :(
