### ISSUE TITLE
[Feature] New Rope Code Request

### ISSUE THREAD

**Issue by EVGSTORE** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#203]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

request not related to a problem in the game. I think this feature should be added to the game to increase the possibilitie sand usses of in game editor parts. Such as the rope. I feel the rope has many other uses it could be used but cant be due to its code limitations. This new code could be used to increase the possibilitie on winches, better cranes, lifts, better doors (idk), and much more!

### Describe the solution you'd like

new code such as:
`setRopeSlack(tag, +-#)` - used to increase and  decrease rope size (winch feature to make rope longer/shorter)
`setRopeStrength(tag, +-#)` used to make stronger/weaker or increase/decrease tention
`tag = findRope("tag")` - find rope to change vars

### Describe alternatives you've considered

i did not think of many changes for the code because its as simple as it could get i feel. this is a new feature request.

### Additional context

used to make winches work simple with new code be used to make rope be able to be changed length and Strength simply.

**Comment by tuxedolabs** [comment]
I'd suggest using the constraint API functions instead and visualize the rope with lines. That gives you better control of custom rope behavior. The built-in rope is not designed to change in length.
