### ISSUE TITLE
[Bug] Snowballed Computer

### ISSUE THREAD

**Issue by Binekrasik** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#204]
### Describe the bug

When you throw a snowball at a computer, its screen pops up
![20220410090717_1](https://user-images.githubusercontent.com/66784259/162607180-f7921ae0-4ef9-4b72-b95b-fdf631caab6c.jpg)
.

### Steps to reproduce the behavior

1. Go to hub
2. Get some snowballs
3. Go to the computer
4. Throw a snowball to the computer screen
5. The screen pops up.

### Expected behavior

The snowball doesn't cause the screen to pop up, it just sticks to the screen.

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10 Home
- GPU: AMD Radeon RX 5500 XT
- Graphics driver version: 30.0.15021.1001
- CPU: AMD Ryzen 5 3600 6-Core Processor

**Comment by YuLun-bili** [comment]
Included in [this issue](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/195)
