### ISSUE TITLE
[Bug] Non Broken But Detached Vox Remains Emissive on Vehicles

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#205]
### Describe the bug

When an emissive vox detaches (not breaks off, just simply detached) from vehicle it remains emissive, along with it's lights.

For the pic below: the braking light is a standalone vox to avoid voxboxes mess around with light effects, so it's possible to detach without getting broken

![image](https://user-images.githubusercontent.com/70589524/162851749-ee8e189e-edcd-4f63-a7ce-42263c8cd8a0.png)

### Steps to reproduce the behavior

Simply find any vehicle with **standalone** emissive voxels and try to detach it without breaking the voxel

### Expected behavior

Remove the emissive property when detached

### Environment

- Teardown 0.9.6 experimental

### Additional context

Although this could be somehow implemented via scripts (delete the vox) but I don't think that's a very good option, at least visually. Personally I would expect a game engine side solution like what we got on vehicles: emissive vox could become non-emissive

**Comment by tuxedolabs** [comment]
Vehicle lights are not designed to be separate shapes, use special indices and it should work.
