### ISSUE TITLE
[Bug] ISSUE TITLE HERE

### ISSUE THREAD

**Issue by daniel020208** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#209]
### Describe the bug

i dont have the new spawn menu

### Steps to reproduce the behavior

when i luanch the game and enter any map the spawn menu doesnt apear

### Expected behavior

it was suppose to show the spawn menu in the leave game menu 
![image](https://user-images.githubusercontent.com/92738592/163707224-c648f03b-594d-4ab1-b8c4-07158f1a4fc4.png)

### Environment

- Teardown Version 0/9/5-- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows

- GPU:rtx 2060 super
- Graphics driver version:512.15
- CPU:CPU

	Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz

**Comment by nooitaf** [comment]
The spawn menu is in the bottom part of the pause menu in sandbox levels.  
For campain levels you need to enable spawning in `options > game > allow spawn`

![image](https://user-images.githubusercontent.com/1898194/163707587-8734f5b1-c3c6-4450-a0a2-3beb2ed71aa4.png)

**Comment by daniel020208** [comment]
i eneabled it and it is still doesnt showing
is there any mod or something that cancling it?

**Comment by nooitaf** [comment]
You don't see anything at the bottom? 
Photo-mode should definetly be there. 
Otherwise it's very likely a mod breaking it.

Make sure you test by opening a default Sandbox map, not a mod, as mod-maps can have sandbox disabled.

**Comment by daniel020208** [comment]
i opened a in a sandbox map i will try diabling the mod

**Comment by daniel020208** [comment]
i fixed it thank you for helping

**Comment by nooitaf** [comment]
no problem..
If you know which mod it was, let us know.
You can also hit "comment & close" when this issue is resolved.

**Comment by daniel020208** [comment]
idk the mod
