### ISSUE TITLE
[Feature] Lua API - IsLightEnabled function and GetShapeEmissiveScale

### ISSUE THREAD

**Issue by patStar** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#21]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
In a mod that enables and disables single light sources with a tool the initial state of a light source is of interest. Also one could build a stealth game like "thief" by knowing if a light source is active and what's the emissive scale so one can trigger an alarm if the player is to far out into the light.

**Describe the solution you'd like**
- function IsLightEnabled(lightHandle) returning a boolean true if the light is enabled and false otherwise
- function GetShapeEmissiveScale(shapeHandle) returning a number that represents the current emissive scale

**Describe alternatives you've considered**
To know beforehand if a light is off or on one can dissable or enable all lightsources on a map by scanning and setting them on or off but this kind of breaks the initial map atmosphere. For the emission its the same.

**Additional context**
Nothing to add here

**Comment by nooitaf** [comment]
I might add that the following functions would also be very nice in that context..
```lua
local r, g, b = GetLightColor(light)
local intensity = GetLightIntensity(light)
```

**Comment by tuxedolabs** [comment]
There is a new function IsLightActive in 0.7 that covers most of this. There might be a generic API introduced later for querying editor properties like color and intensity (scale), so I won't add these functions for light specifically now, since it will pollute the API

**Comment by nooitaf** [comment]
Nice to know that querying editor properties is more or less on the roadmap :)
