### ISSUE TITLE
[Bug] Snowballs thrown at windows leave snow voxels on the other side of the window

### ISSUE THREAD

**Issue by MarkEScheidker** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#212]
### Describe the bug

Snowballs thrown at thin surfaces like windows spawn voxels on the opposite side of the window as well as on the correct side
![2022-04-21-23-39-22](https://user-images.githubusercontent.com/83242911/164609207-b76cac1c-f254-4c46-821d-097888a6b90c.png)

### Steps to reproduce the behavior

1. Throw a snowball at a window
2. Wait for it to hit the window
3. Look for snow on the wrong side of the window

### Expected behavior

snow should only appear on the side of the window that the snow was thrown from

### Environment

- Teardown Version [full release 1.0]
- OS: Windows 11
- GPU: RTX 2070
- Graphics driver version: latest nvidia driver
- CPU: i5 - 8600k

**Comment by tuxedolabs** [comment]
Too small to fix
