### ISSUE TITLE
[Bug] Bridges in Frustrum starts unpowered untill button hit

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#213]
### Describe the bug

it seems that the joints for the bridges that starts at the lower level were actually unpowered, they will move slightly downward when it "wakes up", and free float up and downs

### Steps to reproduce the behavior

1. Go to Frustrum (sandbox in my case)
2. find bridges that starts off lowered
3. stand on it
4. bridge drops slightly
5. get physics gun, grab bridge, notice its doesnt stay inplace
6. grab the bridge that starts off lifted, stay in place

### Expected behavior

maybe lock the joints? with settarget? idk

### Environment

- Teardown Version 1.0.0
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Does not seem very problematic, I think the lower position is just slightly unaligned with start position.
