### ISSUE TITLE
[Feature] Increase length of rocket despawn

### ISSUE THREAD

**Issue by Ollie1101** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#215]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

this feature should be added for long range precise rocket hitting, also cool for acting like a MLRS.

### Describe the solution you'd like

increasing the despawn length of rockets so they can actually hit the ground when fired in the sky

### Describe alternatives you've considered

i have considered using a mod to change the length 

### Additional context

https://streamable.com/bnlwcz

**Comment by tuxedolabs** [comment]
Has been increased in the past, will probably not change again.
