### ISSUE TITLE
[Bug] Can't see mouse when starting the game ("front page", the menu)

### ISSUE THREAD

**Issue by tekeroth-snapcode** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#217]
### Describe the bug

The mouse is not shown on screen, but it is there and working, if you manage to point on any clickable item.

### Steps to reproduce the behavior

1. I updated to latest version as of today
2. Start the game
3. Get past the disclaimer about blinking etc
4. On main screen/menu, mouse is not shown

### Expected behavior

The mouse marker should be shown.

### Environment

- Teardown Version: 1.0.0
- OS: Win 10
- GPU: Nvidia GeForce RTX 2070 Super
- Graphics driver version: 511.23 (DirextX 12.0)
- CPU: AMD Ryzen 9 3900X 12C

**Comment by tuxedolabs** [comment]
Could be mouse pointer trails, see homepage FAQ
