### ISSUE TITLE
[Bug] Cut, Copy, Delete or Duplicate of Main Scene = Crash

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#22]
**Describe the bug**
InstaCrash if selecting Cut, Copy, Delete or Duplicate on Main Scene 

**To Reproduce**
1. Go to Editor
2. Right Click on main scene
3. Select Cut, Copy, Delete or Duplicate

**Expected behavior**
Either disable the options or no crash 

**Screenshots**
![copy](https://user-images.githubusercontent.com/1898194/113249383-ddf20780-92be-11eb-8c84-5029935928ec.png)

**Environment**
 - Teardown Version 0.6.2 (patch 1) 
 - OS: Linux
 - GPU: gtx970
 - CPU: i5-4590

**Comment by tuxedolabs** [comment]
Fixed in 0.7.0

**Comment by nooitaf** [comment]
"Delete" still seems to work and crashes the game.
