### ISSUE TITLE
[Documentation] UiTextInput() has undocumented parameters

### ISSUE THREAD

**Issue by carsakiller** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#220]
### Document to improve

https://teardowngame.com/modding/api.html#UiTextInput
https://teardowngame.com/modding/api.xml

### Enhancement

The example on the page shows that a width(?) and height(?) can be passed to `UiTextInput()`:
```lua
name = UiTextInput(name, 200, 14)
```
However, the documentation above it, as well as the XML documentation, do not list any parameter other than `text`.

**Comment by tuxedolabs** [comment]
There are many problems with this function. I removed API docs until it is fixed and implemented properly.
