### ISSUE TITLE
[Bug] Robots can walk on air using cables

### ISSUE THREAD

**Issue by Auriosi** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#221]
### Describe the bug

I was in sandbox messing around, spawned a robot to see what it did, and got the idea to attach cables to its feet. Before I had attached the other end to something, it started walking in the air, like it was walking on the preview of the cable.

### Steps to reproduce the behavior

1. Go to a sandbox and spawn a robot
2. Select the cable tool
3. Attach a cable to the robot's foot
4. It should start climbing into the air and trying to walk

### Expected behavior

The robot's foot is attached to something via cable without issue.

### Environment

- Teardown Version: 1.0.0
- OS: Windows 10
- GPU: GTX 1050Ti
- Graphics driver version: 511.79
- CPU: AMD FX 8350

**Comment by tuxedolabs** [comment]
Can not reproduce, please attach video if still an issue
