### ISSUE TITLE
[Bug] Fantastic Wheels

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#222]
### Describe the bug

If you put a vehicle upside-down and the vehicle's wheels can touch ground, the wheels rotate in the exactly opposite direction it should be rotating.

### Steps to reproduce the behavior

1. Make a simple vehicle which is possible to let wheels to touch ground when vehicle is upside-down
2. Turn over the vehicle
3. Try to move the vehicle

This video explains this situation (Discord message):
https://discord.com/channels/760105076755922996/768940642767208468/968657579628716043

### Expected behavior

rotate in the correct direction

### Environment

- Teardown Version 1.0.0
- Windows 11

**Comment by tuxedolabs** [comment]
Wheels are not physical bodies and not intended to work upside down. Maybe there will be more physical wheels in a later iteration of the engine
