### ISSUE TITLE
TV scan lines perspective

### ISSUE THREAD

**Issue by AdrianTheFrog** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#223]
### Describe the bug

The scan lines on the TV are based on the view direction and not the TV direction. This makes it look like the TV has diagonal scan lines when viewed at an angle.
![20220426231035_1](https://user-images.githubusercontent.com/69091728/165432168-3188e388-0ab4-40a1-bd6b-f0082aaaf558.jpg)

### Steps to reproduce the behavior

1. Go to the television in the campaign
2. Walk over to the side so the screen is at an angle
3. The scan lines on the TV look wrong

### Expected behavior

The scan lines on the TV should stay with the perspective of the TV screen, and not be projected from the player's perspective.

### Environment

- Teardown Version 1.0.0
- OS: Windows 11
- GPU: RTX 3060
- Graphics driver version: 512.59 (latest release)
- CPU: i7 11700k

**Comment by tuxedolabs** [comment]
Known issue / engine limitation
