### ISSUE TITLE
[Bug] Editor doesn't save layers, _id and _open anymore

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#224]
### Describe the bug

Editor doesn't save `<layers>`, `_id` and `_open` anymore.
Everything has to be reopened/selected when re-opening the map.

### Steps to reproduce the behavior

1. Go to Mods
2. Create Content Mod
3. Create group and give it a layer
4. Select layer
5. Save
6. Quit
7. Open
8. See everything closed and no `layers`, `_id` or `_open` in the xml

### Expected behavior

Save it :| ... at least `_open` and `<layers>`

### Environment

- Teardown Version 1.0.0
- OS: Windows/Linux

**Comment by nooitaf** [comment]
As reference. This is how my development setup looks like for dust2. I would have to remember and re-select all of those (plus 5 more outside of view) to have a functioning map on `F5`, every time i re-open it.

![image](https://user-images.githubusercontent.com/1898194/165640010-b98cf688-48af-4033-a095-d161d7a64eac.png)

--- 

Also, where does this get saved? 
![image](https://user-images.githubusercontent.com/1898194/165643158-dfcd1e79-5c44-4c8b-a6d4-345287c488a7.png)
As it seems to change if the map opens with layers or not, but there is nothing in the xml??

### Layers Checked:
1. Save (not needed)
2. Exit
3. Hit play
4. Nothing shows (no layers loaded)

### Layers Un-checked:
1. Save (not needed)
2. Exit
3. Hit play
4. Everything shows (all layers loaded)

**Comment by nooitaf** [comment]
Other situations where it's discouraging to exit out of the map:
- enabling/disabling a gun-mod or other mods 
- copy pasting from other mods
- changing display resolutions
- closing the game for a while

You start thinking "Do i reallly need to exit out now and lose my state?" ... feels so weird

A crash will have the same result. So if you setup a vehicle incorrectly for example and it crashes, you would have to reopen everything again. Till it's' fixed it could take 10x clicks more then normally. Adds to the irritation of fixing and might make people give up way earlier then before.

**Comment by Please-Pick-a-Name** [comment]
i do perfer not having some of them tho, i guess you can have them as a configurable options for the editor, so you can choose to save with those stuff or not to

**Comment by nooitaf** [comment]
As there are no configurable editor options, the quickest way to solve this would be adding an extra point here.. 

![image](https://user-images.githubusercontent.com/1898194/168301040-f28335c0-86b7-42e9-99d8-5a4e798ad4f0.png)

..maybe "Save clean" (F2) .. for saving without `_open` and `<layers>`

It's a small "inconveniece" for the few who need the removal, but a major timesaver for everyone else.

**Comment by tuxedolabs** [comment]
This was changed in order to merge/diff better with source control tool and will probably not be changed back.
