### ISSUE TITLE
[Bug] Puddles are applyin to boats flat surfaces 

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#227]
### Describe the bug

On marina map maybe others too, if yoiu have puddles on ground, and if you drive boat (didn't test on cars) the puddles appeared on flat surfaces yacht can have it... The problem is whrn you drive yacht the paddles stays in place and it looks like you driving through a layer of puddles.

### Steps to reproduce the behavior

1. Go to marina map
2. Drive yacht
3. See puddles
4. DO not change default weather.

### Expected behavior

Puddle texture should not appear on vehicles, or not moving...

### Environment

- Teardown Version [e.g. 1.0.0
- OS: Windows 10
- GPU: 2080ti
- Graphics driver version:
- CPU: iNtel 1200k
![Teardown Screenshot 2022 05 03 - 18 48 58 15](https://user-images.githubusercontent.com/98832021/166488496-ad0bc985-df2e-4b41-90b1-04dc4586d26f.png)
![Teardown Screenshot 2022 05 03 - 18 48 50 05](https://user-images.githubusercontent.com/98832021/166488507-bd221165-5a36-4102-8f0c-bb10a0820280.png)

**Comment by AdrianTheFrog** [comment]
As far as I understand it this is more of a limitation of the current puddle system, as it is also visible on other large objects like roofs when using the physgun. I'm guessing it uses a world space texture to define the puddle locations, which means you couldn't fix it with the current system.

**Comment by tuxedolabs** [comment]
By design. This is a limitation of the screen-space effect used for puddles.
