### ISSUE TITLE
Bomb Crashes Game

### ISSUE THREAD

**Issue by OllieIOW** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#228]
### Describe the bug

Upon placing bomb, game freezes then crashes.
Note, I Disabled all mods and it still crashed

### Steps to reproduce the behavior

1. Go to any map
2. Go along to the placeable bomb
3. Place it down somewhere

### Expected behavior

Bomb places, beeps, then explodes

### Environment

- 1.0.0 [Experimental]
- Windows 11
- Rtx 2060
- AMD fx8210

**Comment by YuLun-bili** [comment]
Seems more likely to broken files, I would suggest to verify local file (in steam library -> right click game -> properties -> local files -> verify)

**Comment by tuxedolabs** [comment]
Cannot reproduce
