### ISSUE TITLE
[Bug] Fence Gitch

### ISSUE THREAD

**Issue by Nemiix1** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#229]
### Describe the bug

I was in campaign and I was trying to see if I could go over a metal fence using a broken part of a sign and instead i glitched through the gate.

### Steps to reproduce the behavior

1. Go to Any automatic gate with the red and white sign on it.
2. Destroy more than half of the sign leaving a small grabbable bit attached still
3. Run grab it then face camera down or grab then jump and camera down again

Video for better explanation:
https://user-images.githubusercontent.com/105553571/168430226-1ae01c01-7944-4d2e-8830-9b3a0ecaca7c.mp4

### Expected behavior

I thought it would just pull me over or pull the sign off.

### Environment

- Teardown Version: 1.0.0
- OS: Windows
- GPU: Geforce GTX 1650 (idk brand/company)
- Graphics driver version: 
- CPU: AMD Athlon 3000
![specs](https://user-images.githubusercontent.com/105553571/168430606-90167f50-8c03-43e4-9de4-3b0626052740.PNG)

### Additional context

if anyone is fixing this or anything could you please tell me so I know its been seen on discord thanks!

Discord: Corbit#8552

**Comment by tuxedolabs** [comment]
Known issue due to anti-plank fly feature added in 0.9
