### ISSUE TITLE
[Bug] Crash when loading invalid .vox as voxbox brush

### ISSUE THREAD

**Issue by metarmask** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#23]
## To reproduce
1. Create an empty file with a ".vox" extension in a mod folder.
2. In the editor, choose it as a voxbox brush.
3. Play the level.

## Expected behavior
That no crash follows, like how no crash follows when choosing an invalid vox file for a vox object. That the level doesn't load, or that the level loads but without the voxbox, or that it loads with the voxbox that would have appeared if no brush was selected.

## Environment
 - Teardown version: 0.6.2 (patch 1)
 - OS: Linux (Proton experimental-6.3-20210402b)
 - GPU: NVIDIA GeForce GTX 1070
 - Graphics driver version: 460.32.03
 - CPU: AMD Ryzen 5 1600

**Comment by tuxedolabs** [comment]
Fixed in 0.7.0. Thanks!
