### ISSUE TITLE
[bug] Sign wont turn off when power source disconnected

### ISSUE THREAD

**Issue by sherbetknowz** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#230]
### Describe the bug

in the driveway of evertides there is a neon sign that has a wire attached to a generator implying it powers the sign, when breaking the wire the sign remains on.

### Steps to reproduce the behavior

1. Go to this area in evertides mall
![image](https://user-images.githubusercontent.com/105812218/169103521-c59651e4-dcc3-4e79-aa36-861981e53766.png)
2. shoot the wire connecting the generator to the sign
![image](https://user-images.githubusercontent.com/105812218/169103684-212d2f09-3d76-4072-890b-3646142bbe69.png)
3. observe
![image](https://user-images.githubusercontent.com/105812218/169103754-8dfe8464-9df6-48ed-909f-7db44f56ad3d.png)

### Expected behavior

sign turns off

### Environment

- Teardown Version: 1.0.0
- OS: Windows 10
- GPU: gtx 1650 super
- Graphics driver version: 511.23
- CPU: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.29 GHz

### Additional context

i dont know if the sign is supposed to turn off or not i just think it would be cool if it did

**Comment by North-dev** [comment]
Pretty sure this isn't a bug

**Comment by YuLun-bili** [comment]
It's rather a new feature than a bug to me

**Comment by tuxedolabs** [comment]
Not a bug, just how it works :-/
