### ISSUE TITLE
Graphics issues with shadows

### ISSUE THREAD

**Issue by ParkingMeter30** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#231]
### Describe the bug

I recently got a Nvidia GeForce RTX 3070 to replace my AMD RX580. After complete installation of hardware and software, I started Teardown to see that Certain light levels and environments, usually dark, cause the shading to form thick, fuzzy, cartoon-like outlines around objects. I initially thought that it was the driver, so I ran ddu which, in the end, did not solve the issue. I also tried reinstalling the driver, which didn't help either.
I am thinking it's the card itself, or there is something going on with the game, but I have absolutely no clue.

Here are some screenshots:
![Capture](https://user-images.githubusercontent.com/78761860/169417439-99ed49f3-57a4-475b-b496-be56ac9f22f6.PNG)
![1](https://user-images.githubusercontent.com/78761860/169417446-60bfed19-bc68-436e-9ff0-011e2da37106.PNG)
![2](https://user-images.githubusercontent.com/78761860/169417449-9e713179-d4c7-4418-8945-a602b21690d5.PNG)

Thanks,
-Parking Meter

### Steps to reproduce the behavior

1. Load level (One that has an environment that's from dark to pitch-black)
2. See error

### Expected behavior

No graphical errors:
![none](https://user-images.githubusercontent.com/78761860/169417899-1de83367-0700-4ea5-8ac0-d00d9a1506ac.PNG)

### Environment

- Teardown Version: **10.0**
- OS: **Windows 10**
- GPU: **NVIDIA GeForce RTX 3070**
- Graphics driver version: **30.0.15.1215** (See Below)
- CPU: **Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz   3.70 GHz**

(Originally had the current driver- (ver. 512.77), which had the error, so I had switched back to older driver to see if that would fix it, which it didn't).

### Additional context

Before change:
![none](https://user-images.githubusercontent.com/78761860/169418807-c5ef5670-2383-42b8-96c0-5aae898a1d82.PNG)

After change:
![Capture](https://user-images.githubusercontent.com/78761860/169418838-1080ef05-3d45-4034-a198-4a60d453a442.PNG)

**Comment by Please-Pick-a-Name** [comment]
remove any of your reshade, they do not work

**Comment by Please-Pick-a-Name** [comment]
oh btw, this issue is fixed by setting the ambientexponent to smth NOT 0

**Comment by tuxedolabs** [comment]
Duplicate #234
