### ISSUE TITLE
[Bug] ISSUE TITLE HERE

### ISSUE THREAD

**Issue by PowerProo** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#232]
### Describe the bug

Tried to play any challenges on Lee Chemicals, but it send me to a black void. Same happens with credits maps. 

### Steps to reproduce the behavior

1. Go to Play
2. Click on 'Challenges'
3. Click on any Challenges that are under Lee Chemicals
4. See a Map without anything 

![20220524114933_1](https://user-images.githubusercontent.com/106150817/170003709-bc93f2f4-e013-4e95-832e-cbe93cc2553e.jpg)
![20220524114941_1](https://user-images.githubusercontent.com/106150817/170003713-8125928b-7673-4b84-ba15-820ea7769592.jpg)

### Expected behavior

I was expecting to play the challenges

### Environment

- Teardown Version 1.0.0
- OS: Windows 10
- GPU: Vega11
- Graphics driver version: 27.20.11044.7
- CPU: Ryzen 5 3400G

**Comment by Tresquel** [comment]
This looks like the map files are corrupted and unreadable for the game.

Try to verify the game files on Steam:
1. Look for Teardown in your Steam library
![image](https://user-images.githubusercontent.com/43729305/170047430-8e52cb17-ce45-4d48-b274-488f785c9d72.png)
2. Right click it and go to properties
![image](https://user-images.githubusercontent.com/43729305/170047618-87c93b55-2631-4ca2-9a0e-ce135e745dd3.png)
3. Go to local files and verify the game files.
![image](https://user-images.githubusercontent.com/43729305/170047856-c0121459-9d49-4018-86ef-e28c089b3a24.png)


If the problem has been solved: Great! You can close this issue.
If not try to get support in the [Discord server](https://discord.com/invite/teardown)'s #game-tech-support channel.

**Comment by PowerProo** [comment]
Thanks! It works now.
