### ISSUE TITLE
i'm getting launched into the air

### ISSUE THREAD

**Issue by Beneryz** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#233]
### Describe the bug

This would happen with breaking windows and walking into them would launch me. Some of the launches even clipped me through the map for some reason.
MAP: Quilez Security

### Steps to reproduce the behavior

I have no idea how to reproduce it. 
But you might be able to with specific mods (idk which ones) and going on Quilez Security and mess around a lot while restarting a lot. Not sure if this is correct.

### Expected behavior

It's supposed to just break and fall like a wall would.

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows/Linux]
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
u already said _might be able to with specific mods_ so don't expect devs to deal with that, very likely to caused by mods

**Comment by tuxedolabs** [comment]
Unable to reproduce
