### ISSUE TITLE
[Bug/Suggedtion?] ambientexponent of 0 breaks rendering

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#234]
### Describe the bug

putting 0 inside the ambientexponent of the envroment will break the rendering, making fuzzy black balls everywhere

### Steps to reproduce the behavior

i dont think i need to explain how to recreate this

### Expected behavior

i mean i dont expect it to work, but i do however expect the game to probably not allow 0 to be typed in that field

### Environment

- Teardown Version: 1.0.0
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Added clamping 0.1 to 10.0
