### ISSUE TITLE
[Feature] bindind of unconventional keys eg crouch, interact key

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#235]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

a way to bind some unconventional keys
For one, If someone don't have a scroll wheel so they can try to bind the zoom to other buttons, and lets say bind crouch to Caps locks key, etc

### Describe the solution you'd like

allow binding of those keys

### Describe alternatives you've considered

nah

### Additional context

idea copied from https://discord.com/channels/760105076755922996/766578005942206466/980341749287362570

**Comment by Marcus-Dawson** [comment]
Will probably not be added.

**Comment by YuLun-bili** [comment]
track in #449
