### ISSUE TITLE
[Bug] If UiFont isn't provided with a size or a font, the game crashes

### ISSUE THREAD

**Issue by Tresquel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#236]
### Describe the bug

It's in the title, if the UiFont option isn't provided with a text size or a font, the game crashes.

### Steps to reproduce the behavior

1. Call UiFont without a size or with a font that doesn't exist.
Code:
```lua
function draw()
	UiFont("regular.ttf")
end
```
```lua
function draw()
	UiFont("thisfontdoesntexist.ttf", 32)
end
```

### Expected behavior

A error or something

### Environment

- Teardown Version: 1.0

### Additional context
-

**Comment by tuxedolabs** [comment]
Cannot reproduce. Above example runs fine in our tests.
