### ISSUE TITLE
Broken alarm box

### ISSUE THREAD

**Issue by ahs3n** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#239]
### Describe the bug

On the level "The pawn shop", the alarm box for the fax machine does not trigger an alarm when you pick up the object.  There's clearly a wired alarm box there but it doesn't trigger.

### Steps to reproduce the behavior

1. Open up the level "The pawn shop", in Part 2.
2. Go to the fax machine
3. Press E to pick it up
4. Alarm does not activate.

### Expected behavior

The alarm _should_ activate

### Environment

- Teardown Version 1.0.0
- OS: Windows
- GPU: Not sure
- Graphics driver version: Not sure
- CPU: Ryzen 4700

**Comment by 01000001-01101011** [comment]
![image](https://user-images.githubusercontent.com/68795918/173203404-aee49900-1b48-4beb-a281-2767d34f9801.png)
Here's proof

**Comment by ahs3n** [comment]
![20220611161240_1](https://user-images.githubusercontent.com/68795918/173203458-8409e593-f8f7-4b7e-9085-bd0027baedbe.jpg)
Here is a screenshot of proof.  This is an easily reproducible issue, even after relaunching the game.

**Comment by Please-Pick-a-Name** [comment]
why do i remember this bug?
