### ISSUE TITLE
Crash if .vox model has metal ground

### ISSUE THREAD

**Issue by DimasVoxel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#24]
**Metal ground material for .vox model**
If the .vox model has metal set as its ground material (in magicavoxel render mode), the game will crash.

**To Reproduce**
1. Make .vox model
2. In render mode (magicavoxel) alt + left click on ground -> apply metal material
3. Load in .vox model in game and try to play level
4. Crash

**Expected behavior**
The ground material shouldn't have any effect on the 
game as it's not something visible in game.

`**Screenshots**`
Model with metal ground
https://imgur.com/a/0PFh7zi

**Environment**
 - Teardown Version [ 0.6.2 (patch 1)
 - OS: Windows 10 Pro, 64 Bit
 - GPU: RTX 2060 6GB 
 - Graphics driver version: 456.71
 - CPU: Ryzen 7 3700X

**Comment by tuxedolabs** [comment]
I didn't even know you could do that :)
Fixed in 0.7.0
