### ISSUE TITLE
[Bug] Wheels with no shape crash game

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#245]
### Describe the bug

when a [wheel] inside of the [vehicle] [body] doesnt have any [shape] in it, game crash

### Steps to reproduce the behavior

1. Go to any existing [vehicle] in editor (faster to test)
2. remove the [shape] inside the [wheel]
3. load level
4. crash

### Expected behavior

no wheels at all, some default wheel model, error message, just no crashing the game perhaps?
yes people needs some way to be aware that they missing a shape in the wheel, but this way should probably not be a game crash

### Environment

- Teardown Version: 1.0.0 
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

this is one of the oldest consistent crashing issue ppl found out in the game, probably, its time to say goodbye

**Comment by UwQ-Official** [comment]
It's been more than a year and this still hasn't been fixed 😔😔😔

**Comment by Please-Pick-a-Name** [comment]
this had been fixed in 1.5.0 experimental branch, i will see if the fix stays

**Comment by Please-Pick-a-Name** [comment]
fix stays
