### ISSUE TITLE
[Feature] SetPlayerRotation

### ISSUE THREAD

**Issue by Malar10** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#249]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Currently there is no way to change the direction the player is facing without also affecting the player's movement.

Using SetPlayerTransform with the values gotten from GetPlayerTransform will cause the players movement to be slowed down to unplayable levels. (Same happens with every other SetXTransform functions, though it's usually less noticeable) 

I believe this is caused by the GetXTransform functions giving values from before they were updated for the frame.

### Describe the solution you'd like

I suggest adding a new API function: SetPlayerRotation
This function would take a quaternion as an argument, and set the player's rotation to that value without affecting the player's position at all. Instead using the current, updated position value.

### Describe alternatives you've considered

The ultimate solution would be for all of the GetXTransform functions to give up-to-date values, but that might be too difficult to change.

Alternatively you could make it so leaving the position or rotation of a transform blank in a SetXTransform function would simply use the current values for the object. Though this might mess with existing mods.

The easiest solution would therefore be adding a new function solely for changing the rotation without affecting the position value.

### Additional context

this code should affect the player in no way, but it slows the player's movements and makes jumping impossible.
This makes it near unusable for modifying the player's movements dynamically.

```lua
function update()
	SetPlayerTransform(GetPlayerTransform(true), true)
end
```

https://user-images.githubusercontent.com/83091887/177399398-10398f47-b06b-4167-aaf1-e57faed91cd2.mp4

here is the mod used in the video above:
[example.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/9048938/example.zip)

**Comment by Please-Pick-a-Name** [comment]
setting transform removes velocity, get the velocity first and then set the transform, and then set the velocity back

**Comment by Malar10** [comment]
I am actually so stupid it even says that in the api docs
goodbye
