### ISSUE TITLE
[Bug] No Audio in the Game while play with two screens in extended mode

### ISSUE THREAD

**Issue by raxitocl** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#252]
### Describe the bug

The game stop playing audio unexpectedly, while other audio sources still playing audio without being affected by the game, using Screen 1 for Teardown in Fullscreen Mode and Screen 2 for Edge Chromium playing a video.

### Steps to reproduce the behavior

1. Use two monitors in extended mode (Screen 1 and Screen 2 are independent)
2. Execute any audio source in 2nd Screen (Youtube, Soundcloud, Spotify, etc.)
3. Convert the 1st screen in main screen in Settings (Settings -> Screen/Display -> Various Monitors (or the hidden menu under the buttons for "Identify screens") -> Convert this screen in main)
4. Execute the game in Fullscreen Mode

### Expected behavior

The game runs normal, but the audio doesn't work.
Menu music, Tuxedo Labs intro music, game audio, SFX, and more can't be listened, even if you pause the audio source from another program

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: Windows 11 Pro 21H2 
- GPU: NVIDIA GeForce GTX 1650 4 GB (Game) / Intel UHD Graphics (Video)
- Graphics driver version: GeForce Game Ready 516.59 (28/06/2022)
- CPU: Intel Core i5-9300H 2,40 GHz (8 CPUs)

### Additional context

Previously, the way to fix this problem was reinstalling Windows 11, keeping files, but deleting programs, and that fix the problem, but now, the way to trigger that Audio Bug, is by use two Monitors in Extended Mode

**Comment by YuLun-bili** [comment]
hmmm I never noticed such issue on my device...

**Comment by YuLun-bili** [comment]
Cannot reproduce in latest version of game (1.5.3). Audio do disappears when out of focus but as long as one is playing, audio is always there. I suspect some audio mixing software could cause this.

Feel free to reopen or create a new one if occurs again.
