### ISSUE TITLE
certain Level Editor Functions

### ISSUE THREAD

**Issue by hotcocoadotcom** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#258]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I think functions for modders to make their own in-game level editor for beginners who want to make a quick and easy level should be able to. This came up after the user Autumnatic was making a type of car themed puzzle game, and i suggested a level editor, but thats not possible without file saving, editing, and all those types of functions.

### Describe the solution you'd like

Functions that could include prefab file saving, editing, deletion, and all that could be pretty useful. It should only allow .xml files to be saved, edited, and deleted though.

### Describe alternatives you've considered

Not many other alternatives were considered, maybe a one time level editor that doesnt save progress, but thats not fun.

**Comment by SadWeeble** [comment]
The savegame.mod registry can be used to save data. It would no doubt be difficult to extend this to saving entire player-made levels, but as long as something can be broken down into .xml strings, it can be saved in savegame.mod.

**Comment by YuLun-bili** [comment]
> Functions that could include prefab file saving, editing, deletion, and all that could be pretty useful. It should only allow .xml files to be saved, edited, and deleted though.

This is enough to pose a threat to device safety if not tightly restricted. e.g.: intentionally creating and saving new files constantly with automated process and fill up disk storage space and/or memory. Additionally, it's practical for modders to make their simple level editor with existing modding API, including editing, saving, loading and sharing. Even though still requires some additional work got done manually such as copy pasting or create new files.
