### ISSUE TITLE
[Bug] Global (UI) mods cannot access their files through PlayMusic function (looks into level mod's files instead)

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#26]
**Describe the bug**
Issue with UI mods (the ones using only `main.lua`, not containing any map, nor weapon).
I'm trying to make a global music player and I stumbled upon the fact that global mods can't access their own files via `PlayMusic` function. They can do it via `PlaySound` and `UiSound` (probably also `PlayLoop` but I didn't check).
In case of `PlayMusic`, you can find and play official music, but if you try "custom" music (included in UI mod) it will instead look into the directory structure of currently played level mod.

**To Reproduce**
1. Copy Speedometer mod
2. Add some custom music
3. Try to `PlayMusic("MOD/custom_music.ogg")` or `PlayMusic("custom_music.ogg")`
4. Copy Basic map example and put `custom_music.ogg` on the root, then try again (should work which is wrong)
5. Try `PlayMusic("win.ogg") from Speedometer mod (should work, which is okay)

**Expected behavior**
Custom music located in UI mod's files should be accessible to UI mod from Lua (instead of looking into files of whatever level mod is running).

**Screenshots**
None

**Environment**
 - Teardown Version 0.6.2 (patch 1)
 - OS: Windows
 - GPU: GTX 1080Ti
 - Graphics driver version: does it matter?
 - CPU: Intel i5 4670K

**Additional context**

**Comment by tuxedolabs** [comment]
This is fixed in 0.7.0
