### ISSUE TITLE
[Bug] #Include fails silently

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#264]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/183244350-b6c5b6bd-5dd3-4a8d-a730-c444a1caf919.png)
#Include needs to generate error message when the formatting etc is wrong

### Steps to reproduce the behavior

1. get a working script
2. include another working script
3. ONLY does the include wrong
4. nothing works, and no error message
5. comment out everything in frustration, leaving only DebugPrint("PLEASE WORK FOR THE LOVE OF GOD") inside the tick function
6. doesnt work
7. cries

### Expected behavior

error message for bad #include

### Environment

- Teardown Version: 1.1.0 
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

https://discord.com/channels/760105076755922996/768940642767208468/1005413273467887618
this is the final push for this bug report

**Comment by YuLun-bili** [comment]
I feel like that's a internal issue of Lua rather than game

**Comment by Please-Pick-a-Name** [comment]
> I feel like that's a internal issue of Lua rather than game

#include is dennis magic, so he is responsible for that :)

**Comment by Please-Pick-a-Name** [comment]
im pretty sure this has been changed but i dont remember

**Comment by squarebracket-s** [comment]
> im pretty sure this has been changed but i dont remember

Yep, it's fixed now :)

**Comment by Please-Pick-a-Name** [comment]
> > im pretty sure this has been changed but i dont remember
> 
> Yep, it's fixed now :)

i tested myself and its indeed fixed, closing issue
