### ISSUE TITLE
[Bug] Vehicle interacts with object that im about to spawn

### ISSUE THREAD

**Issue by davigeeek** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#265]
### Describe the bug

When I'm about to spawn any object, and i make it go up from under any car "that has suspensions", the car goes up a little, like there was a hidden force in the object I'm about to spawn. I repeat: this works with any car and any objects.

https://user-images.githubusercontent.com/81991811/183297080-45ab78ae-0ea6-4a02-8cbd-4ee0f7bbb9e4.mp4

### Steps to reproduce the behavior

1. Go to any map
2. Spawn a car (or use an already spawned one)
3. Spawn any object
4. Put under the car the object but not spawn it (when it lets you decide where to spawn)
5. Still without spawning, let the object go up, from under the car

### Expected behavior

I was spawning cars for my hotel to make a video, when suddenly i see one of the cars go up for no reason. I was confused at the beginning, but then i inspected and found out the problem. It technically should go thru the other car without colliding in some way.

### Environment

- Teardown Version 1.1.0
- OS: Windows 10
- GPU: GTX 1650
- Graphics driver version: Geforce Driver 516.59
- CPU: Intel Core i7 2600K 3.4GHz Quad-Core

### Additional context

I don't think this is supposed to happen.

**Comment by Tresquel** [comment]
similar to #129, objects in that state are spawned but frozen in the air and with collision not disabled entirely

[Response from Dennis](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/129#issuecomment-1048572094)

**Comment by davigeeek** [comment]
oh didnt know

**Comment by SKullemiji** [comment]
that's normal
