### ISSUE TITLE
[Bug] Unused function parameter

### ISSUE THREAD

**Issue by xBlixon** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#266]
### Describe the bug

While browsing through Teardown code i've noticed that in `data/ui/options.lua` on the very first function (`optionsSlider`) on the third line, there's unused parameter `def`. I simply assume it stands for default and unless it's not just a hint for the devs what value it should have by default. I propose changing it as such.

```diff
-function optionsSlider(setting, def, mi, ma)
+function optionsSlider(setting, mi, ma)
	UiColor(1,1,0.5)
	UiPush()
		UiTranslate(0, -8)
		local val = GetInt(setting)
		val = (val-mi) / (ma-mi)
		local w = 100
		UiRect(w, 3)
		UiAlign("center middle")
		val = UiSlider("common/dot.png", "x", val*w, 0, w) / w
		val = math.floor(val*(ma-mi)+mi)
		SetInt(setting, val)
	UiPop()
	return val
end
```

and also change it for all places where the function is called.

### Steps to reproduce the behavior

Read the code.

### Expected behavior

```lua
function optionsSlider(setting, mi, ma)
	UiColor(1,1,0.5)
	UiPush()
		UiTranslate(0, -8)
		local val = GetInt(setting)
		val = (val-mi) / (ma-mi)
		local w = 100
		UiRect(w, 3)
		UiAlign("center middle")
		val = UiSlider("common/dot.png", "x", val*w, 0, w) / w
		val = math.floor(val*(ma-mi)+mi)
		SetInt(setting, val)
	UiPop()
	return val
end
```

### Environment

- Any Hardware.

**Comment by Please-Pick-a-Name** [comment]
`def` was probably originally supposed to be `w`, but they later hardcoded the value, it wont effect anything if changed, and devs probably wont bother with it, as it will took extra effort to remove that parameter from everywhere that calls this function

**Comment by Please-Pick-a-Name** [comment]
nvm ye they wanted it to be the default value of the given key, probably was meant to implement some sort of things that you can say right click on it and it just goes back to the default value, not sure why they didnt implement it, but again still extra effort to remove that parameter from everywhere that calls it

**Comment by xBlixon** [comment]
From what i saw this function is used like 7 times throughout the game. In fact this is extra effort that wont change a whole lot, but it should take at most 3 minutes to change this.

**Comment by YuLun-bili** [comment]
function removed due to game update
