### ISSUE TITLE
[Bug] SetCameraTransform in vehicle does not remember whether or not vehicle was in the first person mode

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#27]
**Describe the bug**
SetCameraTransform in vehicle does not remember whether or not vehicle was in the first person mode, so once you set it even momentarily (for one frame), you get back to external view (but strangely, it remembers zoom level of external camera).

**To Reproduce**
1. Prepare script that allows you to SetCameraTransform with key press/hold
2. Go to vehicle
3. Zoom in into the first person mode
4. Press and release "the Key" to SetCameraTransform momentarily (it can be the same position as vehicle's first person camera to highlight the issue even further).
5. See error (game goes back to third person)
6. Zoom out and repeat step 4, it should go back to the proper zoom (out) level which hints that camera was probably intended to remember both zoom level and first person mode

**Expected behavior**
If you're in first person view of the vehicle, you should stay in it after calling SetCameraTransform (or at least get the parameter for that), since it maintains the zoom level in third person view.

**Screenshots**
Videos could maybe help, but screenshots won't.

**Environment**
 - Teardown Version 0.6.2 (patch 1)
 - OS: Windows
 - GPU: GTX 1080Ti
 - Graphics driver version: shouldn't matter, Teardown works without graphical glitches nor performance issues otherwise
 - CPU: Intel i5 4670K

**Additional context**
It really bugs me when accessing control panel in my first-person-focused vehicle mod with a certain jet-black car with red lightbar on front.

**Comment by tuxedolabs** [comment]
Fixed in 0.7.0. I also removed the transition back to automatic camera from script override in all cases.
