### ISSUE TITLE
[Bug] Glitching through movable objects

### ISSUE THREAD

**Issue by Glarky** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#276]
### Describe the bug

When holding any object you are able to pass through it like it is nothing. This glitch can be done without any mods and on any map. 

### Steps to reproduce the behavior

1. Find any object that you are able to hold.
2. Hold the object.
3. While holding the object walk through it.
4. You are now inside the object.
5. If the object is not empty you can walk through it like its nothing.

### Expected behavior

If you hold a object you should not be able to noclip through it. By holding the object you are able to pass through it like it doesn't exist.

### Environment

- Teardown Version 1.1.0
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 2070
- Graphics driver version: 512.15
- CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz

### Additional context

Video Evidence
[part 1.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/9796063/part.1.zip)
[part 2.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/9796064/part.2.zip)

**Comment by Please-Pick-a-Name** [comment]
this is to avoid prop fly, and is intended
