### ISSUE TITLE
[Bug] ISSUE TITLE HERE

### ISSUE THREAD

**Issue by Bluefires05** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#279]
### Describe the bug FIXED

(sorry if it was planned for fix)
On the new sandbox map in experimental the cash from the campaign shows up 

### Steps to reproduce the behavior

1. Go on the new sandbox map in experimental
2. Look at the top conner and look at cash

### Expected behavior

i went on the game and decided to look at the patch notes, then saw the new map. went into think it was sandbox and saw cash.

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows/Linux]
- GPU:
- Graphics driver version:
- CPU:
Teardown 1.20 experimental
NVIDIA Geforce Gtx 1660 Ti and AMD Radeon(Tm) Graphics
Geforce game ready driver 497.29
AMD Ryzen 7 4800H with Radeon Graphics

**Comment by YuLun-bili** [comment]
Not sure what you meant but when loading the newly added sandbox map game didn't crash.
Maybe try verifying game files since when steam updates a game it would possibly miss something.

**Comment by Please-Pick-a-Name** [comment]
> Not sure what you meant but when loading the newly added sandbox map game didn't crash. Maybe try verifying game files since when steam updates a game it would possibly miss something.

cash, not crash

**Comment by Please-Pick-a-Name** [comment]
> > Not sure what you meant but when loading the newly added sandbox map game didn't crash. Maybe try verifying game files since when steam updates a game it would possibly miss something.
> 
> cash, not crash

yeap, it shows on the top right
![image](https://user-images.githubusercontent.com/81009804/196850884-b465f5f5-c2db-446a-9a36-cbb060a62df7.png)

**Comment by Bluefires05** [comment]
Its is now fixed after the patch

**Comment by Please-Pick-a-Name** [comment]
somebody close this issue
