### ISSUE TITLE
[Feature] Temporarily set the FOV (without writing it to settings)

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#28]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
It would also be nice to set temporary FOV instead of using SetCameraTransform or setting arbitrary FOV saved in settings by  using `SetInt("options.gfx.fov", targetFov)`, which will stay here if you don't change it back, or more often, if game crashes.
SetCameraTransform in vehicles is known to lag one frame and produce very bad position issue when driving (with velocity, the camera ends up first in your seat, then back seat, and with enough speed, behind the car), while setting FOV through settings does not have such issues due to view being handled directly by vehicle camera logic.

**Describe the solution you'd like**
`SetSessionFOV(targetFov)` function that will remember FOV for this current session instead of writing it to the settings (would also help with zoomed weapons). Maybe additionally a `RevertSessionFOV()` to bring back the selected one from the settings (you can also read it from `options.gfx.fov` and turn it back smoothly, so it's won't be that big of a deal if the second one does not appear).
It could be handy to be able to read the SessionFOV for addons that require it to make instant adjustments to camera or UI positioning, and maybe also a way to `Push` `Pop` them instead of just setting in case more than one mod uses it and wants to go to the previous setting (whatever it was) which was introduced by another mod. `Peek` to the previous one might also be useful in this case

**Describe alternatives you've considered**
`Push/Pop` approach described in the latter part of the previous point.
We can use `SetInt("options.gfx.fov", targetFov)` for now, but it's bad due to the reasons I mentioned in the description. But at least it's something.

**Additional context**
Screenshot with reason why SetCameraTransform is useless in (moving) vehicles.
![image](https://user-images.githubusercontent.com/9891611/114382333-8c822c00-9b8c-11eb-809d-a4ff19380dbd.png)

**Comment by tuxedolabs** [comment]
Added SetCameraFov in 0.7.0, that will temporarily override field of view for any camera.
