### ISSUE TITLE
sandbox menu issue

### ISSUE THREAD

**Issue by SKullemiji** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#281]
### Describe the bug

so i started teardown and then i clicked sandbox and wanted to play on cullington, whatever, but then when i clicked the right arrow i didnt actually click the  arrow, i clicked a tiny bit above the arrow, and went directly to frustrum, i posted something on discord about it, and they asked me to take all mods off, and that was what i did but i still got sent to frustrum, and then somebody sent a video of them clicking exactly the spot where i got sent to frustrum and nothing happened.

### Steps to reproduce the behavior

1. Go to sandbox menu
2. Click off a tiny bit of the right arrow
3. See error (you probalby wont)

### Expected behavior

nothing

### Environment

- Teardown Version 1.2.0 (patch1)
- OS:  Windows 10
- GPU: NVIDIA GeForce GTX 1660 Ti
- Graphics driver version: im too dumb to figure out
- CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz, i dont know if that is the right thing but i hope it will work

### Additional context

IT'S ONLY IN THE EXPERIMENTAL VERSION!

**Comment by Please-Pick-a-Name** [comment]
i have successfully recreated the issue, no worry, lets keep this here

**Comment by Please-Pick-a-Name** [comment]
discord help forum of this bug: https://discord.com/channels/760105076755922996/1032967399126880256

also, additional note, this bug doesnt seem to exist in the official branch, only on the experimental

**Comment by SKullemiji** [comment]
yes i found out today just now

**Comment by Please-Pick-a-Name** [comment]
this had been fixed with 1.5.0 ui update
@Thomasims
