### ISSUE TITLE
[Bug] Issue with built in slow mo mod

### ISSUE THREAD

**Issue by Rusigais** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#290]
### Describe the bug

its an issue with the slow mo mod, built in game, it freezes debri, and when it gets disabled, the debri sitll floats, and is stopped in motion

### Steps to reproduce the behavior

1.Enable slow mo mod, built in game.
2.Go to any sandbox map.
3.Rocket launch a building
4.Enable slow mo mod
5.Debri stops
6.Disable slow mo mod
7.Debri floats
![image](https://user-images.githubusercontent.com/117009882/203617819-cc37bf33-3fa6-4114-919e-d2933dbb1356.png)

### Expected behavior

The debri to go back into normal time, when slow mo mod is disabled

### Environment

- Teardown Version:1.20 [patch2]
- OS: Windows 10
- GPU: GTX 1650, 4GB vram
- Graphics driver version:
- CPU:i5-6500

**Comment by PneumaOfficial** [comment]
Its an engine limitation, every other mod I've seen that "fixes" this, doesn't truly fix it, and the ones that get close enough are costly on performance. If your pc can handle it, use the structural integrity mod, its partially meant to resolve this issue.

Otherwise, its the way it is.

**Comment by YuLun-bili** [comment]
resolved in 1.5.4 since `SetTimeScale()` function patched
