### ISSUE TITLE
[Bug] CreateBrush function does not pick sub-object

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#294]
### Describe the bug

The function `CreateBrush()` for voxscript doesn't pick sub-object however this feature is documented in API (https://teardowngame.com/modding/voxscript.html#CreateBrush)

### Steps to reproduce the behavior

1. Make a simple voxscript
2. Add function `CreateBrush()` and attempt to pick a sub-object
3. Refresh editor scene and voxscript rejects to load model 

### Expected behavior

Be able to load sub-object as brush

### Environment

- Teardown 1.2.0 patch 2

### Additional context

The voxcript in [24 slice mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2426900155) have following comments:
```lua
-- Selecting a sub-object from the Magica Voxel file isn't supported in the public build yet. Sorry about that :)
--[[
object = GetString("object")

if object ~= "" then
	model = model .. ":" .. object
end
--]]
```

**Comment by nooitaf** [comment]
Not sure what you mean by "sub-object" but you can pick objects like this..
```lua
CreateBrush("MOD/file.vox:objectname",true)
```

**Comment by YuLun-bili** [comment]
why I still left this open :|
