### ISSUE TITLE
[Bug] Portion of the pattern for the "on target' truck lights up when reversing

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#297]
### Describe the bug

when reversing, a couple of voxels light up on the back of the "on target" truck.
![2022-12-16-20-34-12](https://user-images.githubusercontent.com/85895661/208217092-e140d6e0-df94-4f3c-8df9-47d47cb490d3.png)

### Steps to reproduce the behavior

1. Go to Tilläggaryd in the "Paper Girl" mission (iirc that's the name)
2. Get in the "on target" truck near the art cafe
3. Reverse the vehicle

### Expected behavior

This may come as a surprise, but I don't think that part of the truck is supposed to light up

### Environment

- Teardown Version 1.3.0
- OS: Windows
- GPU: blah blah blah...

### Additional context

For fear of stating the obvious, i think the materials got a little mixed up. If I had to guess, the logo was created as an image and then imported into magicavoxel, but part of it turned into a pink hue of glass that just so happens to light up on a vehicle when it reverses.

**Comment by YuLun-bili** [comment]
I'd track this in #278
