### ISSUE TITLE
[Bug] Visibility Bug

### ISSUE THREAD

**Issue by BlackRaydee1** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#299]
### Describe the bug

Whenever the game is launched, the bottom right corner will immediately hyper focus on a single pixel, and become massive blur. Literally 1/4 of the screen completely covered in a blur.

### Steps to reproduce the behavior

As simple as starting up the game, either 1. The game menu and title screen are fine until you are required to put an input or 2. The corner will automatically focus upon a single pixel. Here are 3 examples, including the title screen.

![20221217164559_1](https://user-images.githubusercontent.com/120859288/208271846-766f16a3-20a9-4b49-9a19-4846ad86e7e9.jpg)
![20221217164643_1](https://user-images.githubusercontent.com/120859288/208271848-670fd27a-f7dd-4735-b0b1-ffeaa11e3cba.jpg)
![20221217164650_1](https://user-images.githubusercontent.com/120859288/208271849-9ab7f1a9-f617-4c30-92c2-de1d66c0423f.jpg)
![20221217165203_1](https://user-images.githubusercontent.com/120859288/208271876-616a4973-cfe5-4b5c-8035-29e6945d27fc.jpg)

### Expected behavior

I would expect to open the game, as if this issue never existed.

### Environment

- Teardown Version (Cannot access though it is currently on "Art Vandals" update. Dec 15th.
- OS: Windows 10
- GPU: AMD XFX 590 Fatboy
- Graphics driver version: 22.11.2 (Latest as of 12/17/22)
- CPU: Ryzen 7 3700X

### Additional context

This has been an on-going issue for a whole year, I thought it would've been fixed by now but it has not. I've tried many different methods since I've found this bug and nothing seems to work. Verifying files, reinstalled drivers and the game itself and no luck. Hopefully it can be resolved. Please and thank you.

**Comment by 38020372** [comment]
disable Razer Cortex FPS overlay

**Comment by BlackRaydee1** [comment]
Appreciate it.
