### ISSUE TITLE
[Feature] <screen> elements PBR settings

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#30]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
Screens really, really could use some PBR settings (eg. roughness).
Examples of usage include making them less reflective/actual matte, mention possibility of sci-fi clear screens for Star Wars or  Quake 2 Stroggos bases.
It actually is related to a problem because the screens in a certain first-person-view-focused vehicle are so shiny that they're unreadable unless in standstill and without much sun.

**Describe the solution you'd like**
`<screen>` element already contains `emissive` property. It could (and maybe should) contain more properties like `roughness` and probably transparency.
By transparency, I mean that with nothing drawn to it, it would remain transparent and could be used for fancy warning symbols, sci-fi displays, and maybe holograms (if allowed not to be back-face culled, but that can be solved with two screens if it's truly required).
For now, I would at least like to be able to make screen way less reflective, but the transparency will allow even more fun uses (thought it might require changes to the way raycasts are handled).

**Describe alternatives you've considered**
These parameters could also be set from Lua, but that will not make it any easier to implement :)

**Additional context**
-

**Comment by MisterSirCode** [comment]
this would fit quite well into the game, as currently when screens are disabled / broken, they reveal the parent voxel object, which normally has PBR textures and settings.

It would be convenient if low-light screens had toggleable PBR properties, so that it wasnt such a sharp conversion when a screen is broken, going from non PBR to PBR filtered

**Comment by tuxedolabs** [comment]
This sounds very specific. Unless heavily requested we probably won't add.

**Comment by RavMahov** [comment]
I'm pretty sure transparent and less shiny screens were requested in modding discussion at least a couple of times.
I might have worded it wrongly somehow, but while I personally want to use them too for various stuff (screens are awesome!), it's not only for me. They're unique entities that do not lag with non-player camera movement (like vehicles make the sprites move wrongly).
Could also save a lot of draw calls if the Portal Gun could spawn transparent screen with no reflectiveness and move `<screens>` instead of creating a lot of sprites.
