### ISSUE TITLE
[Bug] Game Crash in Menu

### ISSUE THREAD

**Issue by PIRANY1** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#302]
### Describe the bug

Every time i go in the Game and click when i am in the loading Screen or go in another Programm my Game crashes.
I tried it on 4 devices and it works on every but im not sure that it works at yours.

### Steps to reproduce the behavior

1. Go on any Map
2. When you are in the Menu Screen click somewhere
3. Your game chrashes

### Expected behavior

Nothing

### Environment

- Teardown Version: Every version since 0.7
- OS: Windows 11
- GPU: Nvidia rtx 3060 ti
- Graphics driver version:
- CPU:Ryzen 5 3600

**Comment by YuLun-bili** [comment]
The pause menu you mean?

**Comment by PIRANY1** [comment]
no i mean the menu if you go in a new map or reset the map

**Comment by YuLun-bili** [comment]
That's "loading screen"
But sometimes (especially when loading larger maps) windows would think the game halts while game is still running, just wait a while and game would be fine.

**Comment by UwQ-Official** [comment]
Why did you close it suddenly? Did it fix itself?

**Comment by PIRANY1** [comment]
yeah its not rlly an issue if its windows that detects it as crashed
