### ISSUE TITLE
[Feature] Welding Tool

### ISSUE THREAD

**Issue by TinFoil77** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#303]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

In Teardown there are only 2 ways of connecting things (cable and plank). I feel like it would be interesting to see a welding tool that welds metallic voxels together. This would make it much easier to make stable and secure structures instead of having to hold them together with wooden planks.

### Describe the solution you'd like

A welding tool that combines metal voxels when used on them both at once. Would work kind of like the blowtorch but does the opposite thing, instead of breaking pixels it welds them.

### Describe alternatives you've considered

I guess an alternative would be a glue gun or stapler, but i think a welding tool would be better.

### Additional context

I don't really know how it could be used in the campaign, but it would be fun/useful to mess around with in sandbox.

**Comment by PneumaOfficial** [comment]
There is already a mod for this, as there is no use for it in the base game why bloat the players inventory with tools they never use? Just makes finding specific tools harder
