### ISSUE TITLE
[Bug] Frustrum Sandbox Hotel door goes through wall.

### ISSUE THREAD

**Issue by XanderSyr** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#304]
### Describe the bug

The door of the hotel balcony in the Frustum sandbox map goes through the wall when opened very far.

Uploading 2022-12-29-13-24-49.mp4…

### Steps to reproduce the behavior

1. Go to Sandbox
2. Click on Frustrum
3. Walk to the hotel balcony door
4. Open door as far as possible
5, Watch the door disappear in the wall.

### Expected behavior

I expected the door to stop before going in the wall. It did not.

### Environment

- Teardown Version: 1.3.0
- OS: Windows 11
- GPU: Nvidia Geforce RTX 3060 Laptop GPU 6 GB VRAM
- Graphics driver version:
- CPU: Intel i7-10750H

### Additional context

Small minor bug. Door broke

**Comment by Please-Pick-a-Name** [comment]
this had been fixed since idk when @Thomasims
