### ISSUE TITLE
[Bug] FOV slider not staying on certain values

### ISSUE THREAD

**Issue by LeanderJDev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#305]
### Describe the bug

When trying to set the FOV to 100, it jumps down to 99. After fiddling around with it a little bit, I found out this happens on other numbers to, but they always only jump down.
For this bug report I investigated a bit and found out that, there are kind of "unstable values", because in some cases, the slider even jumps down two values(eg. from 61 & 62 it jumps down to 60). This issue is also independent of the display resolution.
These "unstable values" are: 61, 62, 64, 65, 68, 70, 73, 76, 79, 80, 83, 86, 89, 92, 95, 98, 100, 103, 106, 109, 112, 115, 118

### Steps to reproduce the behavior

1. Go to Options > Graphics
2. Set the FOV slider to one of the aforementioned values
5. Notice that you can spam left click and it always jumps back
6. Have fun :>

### Expected behavior

You should be able to set the FOV slider to any value in it's range and it should stay there.

### Environment

- Teardown Version 1.3.0
- OS: Windows 10 Home
- GPU: AMD RX580
- Graphics driver version: AMD Adrenalin 22.11.2
- CPU: AMD Ryzen 5 5600x

### Additional context

Just looked it up again in the issue tracker and found a closed issue about this, but my inner monk needs this and as it would add a lot of quality(in the sense, that even little details are perfected) to the game and isn't hard to fix, I wanted to bring the attention back.
(it was closed because it was "too minor to fix", after that the original author added a comment how it could be easily fixed, so it would also be quite a "minor" fix) [original issue](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/89)

**Comment by Please-Pick-a-Name** [comment]
this is fixed in the new 1.5.0 experimental version since the UI get a total rework

**Comment by LeanderJDev** [comment]
Sounds good

**Comment by Please-Pick-a-Name** [comment]
@Thomasims pls close this issue
