### ISSUE TITLE
[Bug] Being able to activate mods that are offscreen

### ISSUE THREAD

**Issue by vu1canic** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#308]
### Describe the bug

I was writing custom main menu and noticed that mods that were off screen were activated by clinking in specific region.
After short investigation I was able to pinpoint that it is problem with function listMods.

### Steps to reproduce the behavior

1. Click Play
2. Go to mod manager
3. Click in region of activation mods (that yellow/ or empty dot) but higher or lower of items in view
4. Scroll back and see that mod is activated/deactivated

(attached video is of vanilla not edited mods menu)
https://user-images.githubusercontent.com/40404096/210287238-ee2f4e19-d214-49c4-af77-01ea040dd0e7.mp4

### Expected behavior

Not doing that.

### Environment

- Teardown Version 1.3.0
- OS: -
- GPU: -
- Graphics driver version: -
- CPU: -

**Comment by Please-Pick-a-Name** [comment]
UiWindow does not clip user interactable elements correctly

**Comment by Please-Pick-a-Name** [comment]
this had been fixed @Thomasims
