### ISSUE TITLE
[Bug] Some modded tools is broken

### ISSUE THREAD

**Issue by AppleInternal** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#312]
### Describe the bug

My modded tools is broken

### Steps to reproduce the behavior

1. See error

### Expected behavior

My modded tools is broken

### Environment

- Teardown Version 1.3.0
- OS: Windows 11
- GPU: AMD Radeon 570
- Graphics driver version: Unknown (Not launching)
- CPU: AMD Ryzen 5 2600

### Additional context

![image](https://user-images.githubusercontent.com/118739448/210887948-979ee036-d57b-4951-a0a4-d0fc39ad4dae.png)
![image](https://user-images.githubusercontent.com/118739448/210888003-045a3837-70ad-4eaf-a497-af66b9b61c2f.png)
![image](https://user-images.githubusercontent.com/118739448/210888099-485322c5-ad5f-47c5-b0e1-4e0cc30c788d.png)
![image](https://user-images.githubusercontent.com/118739448/210888280-97db8ff7-1381-4d0c-bcf5-9aa919a53eb3.png)
![image](https://user-images.githubusercontent.com/118739448/210888371-08b4fb05-18d3-4c03-af13-e514c0595701.png)
![image](https://user-images.githubusercontent.com/118739448/210888437-a1c35b36-91c5-4386-8e30-e91d827be489.png)
![image](https://user-images.githubusercontent.com/118739448/210888510-5ee0316e-f309-494d-8c78-e6e8fb295089.png)
![image](https://user-images.githubusercontent.com/118739448/210888548-f067ac23-d340-492c-bc87-4f0b08156cff.png)

**Comment by nooitaf** [comment]
There is probably some other mod doing some weird things with your tool location or something. 
This is more something for the discord instead of github.

**Comment by Please-Pick-a-Name** [comment]
can someone just close this issue, this individual seems to have more mods enabled then the number of mods i have ever subscribed to in teardown, and is completly unaware what mod they have enabled

**Comment by YuLun-bili** [comment]
It could be AMD doing something weird

**Comment by Thomasims** [comment]
This Github is for issues related to the base game. I recommend you seek help on the official Teardown Discord server to figure out which mod is causing this behavior.
