### ISSUE TITLE
[Bug] Evertides SunnyMax fetch objective does not trigger alarm

### ISSUE THREAD

**Issue by unami-fx** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#313]
### Describe the bug

If you start with the SunnyMax objective in Evertides Fetch, picking this objective up does not trigger the alarm.

### Steps to reproduce the behavior

1. Startup Evertides Mall
2. Go to the objective "Electronics store"
3. Pick the target up and see what happens

### Expected behavior

Alarm should be triggered when picking the target up

https://user-images.githubusercontent.com/121177755/211171402-bbc50e8e-fb41-4c01-8e67-a73aa100d121.mp4

### Environment

- Teardown Version: 1.3.0
- OS: Windows 10
- GPU: NVIDIA GeForce GTX 1650 SUPER
- Graphics driver version:
- CPU: Intel(R) Core(TM) i7-10700 CPU

**Comment by YuLun-bili** [comment]
resolved in 1.5.4 (maybe 1.5.3 as well)
