### ISSUE TITLE
[Bug] Art vandals

### ISSUE THREAD

**Issue by Atsmats7** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#314]
### Describe the bug

My game crahes every time i open Art vandals

### Steps to reproduce the behavior

1. Go to expantions
2. Click on Art vandals
3. Scroll down to sandbox or campain
4. See error (game crahes)

### Expected behavior

open the Art vandals sandbox or campain

### Environment

- Teardown Version [1.3.0]
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
verify files should fix
https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB
