### ISSUE TITLE
[Bug] UiGetTextSize do -inf funi

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#315]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/212447235-317b5876-e270-4292-9c47-bebb56fd1979.png)

### Steps to reproduce the behavior

local tw,th = UiGetTextSize('')
DebugPrint("Size of empty string with UiGtTextSize")
DebugPrint('tw: '..tw)
DebugPrint('th: '..th)
local tw,th = UiText('')
DebugPrint("Size of empty string with UiText")
DebugPrint('tw: '..tw)
DebugPrint('th: '..th)

### Expected behavior

tw: 0
th: 0

### Environment

- Teardown Version: 1.3.0 
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
not only empty but also string only include any characters beyond `U+00FF`

**Comment by Please-Pick-a-Name** [comment]
this has been fixed
