### ISSUE TITLE
[Feature] Exit vehicle location setting through Lua

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#32]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
In my case, my vehicle has openable automatic roof (t-top) and once it's closed, the player exits through the roof (!), and when it's open, player exits in the position correct for the previous setting (to the left of the driver (left) door).
I would like to decide on exit location and direction depending on "roof closed", "roof open", "roof open + ejection activated" through Lua.

**Describe the solution you'd like**
It would be very nice to have a set of Lua functions related to:
1. Reading "xml exit position/rotation" (similarly to driver position, as all the vehicle-based locations disappear on load)
2. Setting new exit position/rotation through Lua (until vehicle exit at least, which will bring back hardcoded position)
3. Reading that temporary exit position/rotation

Setting these could allow for ejection mechanisms (tested) and... player cannonballs (on vehicle exit, you apply force in both cases).

**Describe alternatives you've considered**
Multiple player exit locations in xml, but this will complicate things more, and we can't exactly say "use this when this joint is fully open" in xml, nor specify any other conditions without Hammer Editor-like logic nodes.

**Additional context**
The circle in the middle (closest to the driver door) shows the position of exit with roof open. The currently opened roof is exit position itself when the roof is closest. The rest of the marked locations are ejection mechanism tests (most of them with "max allowed tilt" and one when trying really hard to land in the middle between 0 and `max tilt`), which shows the exiting definitely happens in the middle.
![image](https://user-images.githubusercontent.com/9891611/114549222-0b489900-9c61-11eb-8b37-8d73a8aaab9e.png)

**Comment by tuxedolabs** [comment]
There is already support for a vehicle exit location. Check editor help.
You need to leave some air around the exit location for it to work properly.

**Comment by RavMahov** [comment]
Very cool, then I should focus this Feature Request on Lua functionality instead and lower the priority (if possible).

**Comment by RavMahov** [comment]
> There is already support for a vehicle exit location. Check editor help.
> You need to leave some air around the exit location for it to work properly.

Edited out the description to make it still valid request (Lua-based location setting).
Thanks for pointing out that the exit value is already supported (but used mostly on boats because vehicles were handled properly)

**Comment by tuxedolabs** [comment]
I don't think there's a strong enough case to implement this feature. You can emulate it by setting SetPlayertransform manually after exiting vehicle.
