### ISSUE TITLE
[Feature] Pitch control for sounds

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#325]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

One really easy way to make it sound like you have a lot of slightly different sound effect is to make pitch variation on a given sound effect.
Plus it allows for nice "charge up" effect on any given sound.
Plus this would reduce a lot the space taken by some mods by reducing the amount of .ogg files embedded in it.

I would like to have this ability in Teardown :)

### Describe the solution you'd like

Have an extra parameter in the  PlaySound() and PlayLoop() function to change pitch of the sound played on the fly.

### Describe alternatives you've considered

Right now you can sort of achieve similar result by manually creating a lot of .ogg sound files and somehow play them one after the other: this is pain.

**Comment by FlorentP42** [comment]
@tuxedolabs: To pitch or not to pitch?

**Comment by YuLun-bili** [comment]
resolved since 1.5.4 added more control to sound related functions (e.g.: pitch parameter)

**Comment by FlorentP42** [comment]
1.5.4 API does not seem to be the released yet, is there a link to the future version?

**Comment by YuLun-bili** [comment]
it's [experimental](https://teardowngame.com/experimental/api.html) :)
