### ISSUE TITLE
[Bug] Debug menu has a typo

### ISSUE THREAD

**Issue by 1AGameMaster** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#329]
### Describe the bug

![image](https://user-images.githubusercontent.com/73741427/220109967-790626ae-7c96-4ff5-ab00-0e687c36da2f.png)
As you can see there is an **s** after Visible in Visible Shapes on the Stats dropdown!

### Steps to reproduce the behavior

1. Open the debug menu
2. Expand the Stats dropdown menu (if you haven't)
3. You can see the typo

### Expected behavior

Visible Shapes instead of Visible**s** Shapes

### Environment

- Teardown Version: 1.3.0
- OS: Windows (probably Linux too)
- GPU: Doesn't matter
- Graphics driver version: Doesn't matter
- CPU: Doesn't matter

**Comment by UwQ-Official** [comment]
I still think this should be fixed :)

**Comment by Thomasims** [comment]
Feel free to reopen this if the debug menu is ever exposed to the public (through a command line option perhaps).
