### ISSUE TITLE
Audio dissapears upon loading game, reappears when display is refreshed

### ISSUE THREAD

**Issue by JBeastCreations** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#341]
### Describe the bug

All audio disappears upon booting up the game. When changing the display settings (fullscreen to borderless window or back), the audio is restored. 

### Steps to reproduce the behavior

1. Boot game.
2. Note lack of audio.
3. Go to display settings.
4. Change your display settings to any non-current display state,
5. Witness restored audio.

### Expected behavior

Audio working from boot. 

### Environment

- Teardown Version W.3.0
- W10 latest update
- RTX2070Super.
- Graphics driver version: 
- CPU: i7 9700k

**Comment by YuLun-bili** [comment]
known issue, do not tab out or leave game run in background during loading

**Comment by Thomasims** [comment]
Duplicate of #292
