### ISSUE TITLE
[Feature] Keep location entity child of vehicle in scene rather than "phrased & removed"

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#345]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I am attempting to turn some existing robots into drivable vehicles, when doing so I noticed that the `<location>` blocks cannot be found by `Find()`, `FindLocations("weapon")` or `FindLocations("weapon", true)` in `script.lua` with the following prefab:

```xml
<prefab version="1.3.0">
  <group name="instance=MOD/prefab.xml" pos="0.0 0.0 0.0" rot="0.0 0.0 0.0">
    <script pos="-0.1 -0.1 -0.1" file="MOD/script.lua">
      <group prop0="texture=12 0.5">
        <vehicle pos="0.0 0.0 0.0" rot="0.0 0.0 0.0" driven="false" sound="none" topspeed="1" antispin="0" antiroll="0" friction="0" tags="vehicle">
          <body tags="body" pos="0.1 1.2 0.1" dynamic="true">
            <vox pos="-0.05 1.0 0.0" rot="0 90 0" texture="12" density="40" file="MOD/dummy.vox" object="torso2">
              <location tags="weapon=laser" pos="1.1 1.1 -0.05" rot="-30 -90 0"/>
            </vox>
          </body>
        </vehicle>
      </group>
    </script>
  </group>
</prefab>
```

### Describe the solution you'd like

Make sure that Locations can always be found in scripts, even if children of a vehicle.

### Describe alternatives you've considered

None

### Additional context

This issue originally described #555, but went a little bit off topic so I reworked it.

**Comment by YuLun-bili** [comment]
locations on vehicles are removed during load before `init()` function is called

**Comment by FlorentP42** [comment]
> locations on vehicles are removed during load before `init()` function is called

Why on earth would this be a thing ??? Please remove that behavior @tuxedolabs XD
Because of that I cannot possibly access the weapon locations of the robots when I turn them into vehicles, which is bad... Also I don't know what kind of design reason could possibly justifiy to delete elements of the prefab that can potentially be used elsewhere, but I would like to know if there is a good reason for that and if it could potentially be changed.

**Comment by YuLun-bili** [comment]
Issue #140 described a workaround but I personally don't like this either. Making locations work inside a vehicle is one of the best improvements/features I want in this game xD

**Comment by FlorentP42** [comment]
What I understand from the above thread is that the reason behind the deletion is that Locations will not follow the body movement when it becomes dynamic.
This is absolutely fine, just make it super clear in the doc of `FindLocation()` and other related functions: all we need is to access them in the `init()` function, just don't delete them before whe had a chance to access them from script please...

PS: Now I understand better the logic in `robot.lua` that finds the closest shape to a location and saves that shape and the local transform to it instead of the location, it's fine if we have to do that elsewhere too.

**Comment by YuLun-bili** [comment]
changed issue type :)

**Comment by FlorentP42** [comment]
Updated description to be more relevant with the topic discussed in the comments and new title and made a separate issue for the other topic in #555

**Comment by TTFH** [comment]
This has been a feature since October last year or so.

**Comment by FlorentP42** [comment]
Is it? Nice I will have to give it one more try then :)
