### ISSUE TITLE
[Bug] Pausemenu bottom bar dimensions incorrectly calculated

### ISSUE THREAD

**Issue by squarebracket-s** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#346]
### Describe the bug

The part of `hud.lua` that calculates if the user clicked _outside_ the pause menu or _in it_ has hardcoded dimensions for the bottom bar.
[Line 1113-1117] hud.lua
```
local mouseInBottomBar = false
UiPush()
    UiTranslate(0, UiHeight()-80)
    mouseInBottomBar = UiIsMouseInRect(UiWidth(), 80) --Both lines are wrong, since the height of the bar may change because of user-set display resolution.
UiPop()
```

Correct code:
```
local mouseInBottomBar = false
UiPush()
    UiTranslate(0, UiHeight()-(gUiScaleUpFactor*80))
    mouseInBottomBar = UiIsMouseInRect(UiWidth(), gUiScaleUpFactor*80) --Height now respects user-set display resolution.
UiPop()
```

### Steps to reproduce the behavior

1. Go to **Options -> Display** in the main menu.
2. Set the window mode to "Windowed" and the resolution to **1280x720**
3. Open any map, open pause menu and click at the top of the bottom bar
4. Notice that pause menu closes even though the mouse was in the bottom bar

### Expected behavior

Pause menu would not close.

### Environment

- Teardown Version 1.4.0
- OS: Windows 10
(no pc information since it's a bug in the code)

### Additional context

Video of bug:
https://files.catbox.moe/5v2ob6.mp4

Edit;
Video showing that the corrected code works:
https://files.catbox.moe/ag0plp.mp4

**Comment by Please-Pick-a-Name** [comment]
you can nologer leave pause menu by clicking outside of boxes
@Thomasims this can be closed now ig
