### ISSUE TITLE
[Bug] Creative mode voxels misaligned when placed

### ISSUE THREAD

**Issue by Maticzpl** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#348]
### Describe the bug

Voxels placed on the green car at the Frustum gas station are misaligned.
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/27724912/f8c1e0e5-2afc-4781-8578-5dfe73402741)
On the image you can see the left wood voxel properly aligned to the car's grid which is the preview visible before placing it.
The voxel on the right is the one placed beforehand, its appears misaligned by half a voxel edge length.
The same behaviour can be seen on some other objects like the red gas pumps.

### Steps to reproduce the behavior

1. Go to main menu > Play > Sandbox > Frustum
2. After the level finished loading, press ESC
3. Click on the Creative Mode button
4. Scale the brush down to 1 voxel (its more visible this way)
5. Approach the green car at the gas station
6. Place a voxel on the car's body

### Expected behavior

The voxel should be aligned properly without offset with the other voxels of the objects they are attached to.

### Environment

- Teardown Version 1.4.0
- OS: Fedora Linux 38 (Workstation Edition)
- GPU: AMD Radeon RX 6600
- Graphics driver version: don't know, provided by linux kernel
- CPU: AMD Ryzen 5 5600

**Comment by tuxedolabs** [comment]
Confirmed. Fixed in 1.4.0 patch 1. Thanks for reporting!
