### ISSUE TITLE
[Documentation] just a existingf issue

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#349]
### Document to improve

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/31348167-38a0-4b1a-91a0-4438ed9ddefc)

### Enhancement

f-less

**Comment by tuxedolabs** [comment]
Fixed in patch 1. Thanks!
