### ISSUE TITLE
[Bug] Pause menu causes stuttering

### ISSUE THREAD

**Issue by Malar10** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#35]
**Describe the bug**
Opening the pause menu in game causes camera stuttering and problems with several mods (such as elboydo's [Simple Ai](https://steamcommunity.com/sharedfiles/filedetails/?id=2405563231&searchtext=ai), I also had a slight problem with the precision flight mod in 0.7.0 but it is not easily reproducible)

**To Reproduce**
Camera stuttering with vehicles:
1. Go to map with a vehicle
2. Pause and unpause while driving vehicle
3. See stuttering (clearer with faster vehicles)

Camera stuttering outside vehicle:
1. Go in any map
2. pause and unpause
3. move your camera and observe stuttering

Simple Ai mod stops working
1. play the [Simple Ai](https://steamcommunity.com/sharedfiles/filedetails/?id=2405563231&searchtext=ai) map
2. give the car a target to drive towards by pointing at a location and pressing g
3. pause and unpause while the car is driving
4. car will begin to rapidly start and turn off, making it nearly immobile

**Expected behavior**
Game should continue as normal with no stuttering

**Screenshots**
links to videos through discord because they're too large to attach directly
[video example with vehicle](https://cdn.discordapp.com/attachments/768940642767208468/835241387741544508/Teardown_2021.04.23_-_22.49.07.18.mp4)
[video example with tools and camera stuttering](https://cdn.discordapp.com/attachments/760106493944135710/835242965684846702/Teardown_2021.04.23_-_22.53.59.19.mp4)
[video example with mod affected by bug](https://cdn.discordapp.com/attachments/768940642767208468/835209225906290698/Teardown_2021.04.23_-_20.37.10.02.mp4)

**Environment**
 - Teardown Version 0.6.2 (patch 1) as well as 0.7.0 experimental
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 2060
 - Graphics driver version: 27.21.14.6611
 - CPU: AMD Ryzen 7 2700 Eight-Core Processor

**Additional context**
Sometimes multiple pauses are required to reproduce the bug. The fact that pausing the game interferes with mods, makes me believe it is a problem with the tick() or update() functions. Not sure about that though

Edit: Made a [small test](https://cdn.discordapp.com/attachments/760106493944135710/835589723917516880/Teardown_2021.04.24_-_21.38.51.07.mp4) and sure enough pausing the game causes stuttering both with tick(dt) (left) and update(dt) (right)
![image](https://user-images.githubusercontent.com/83091887/115969945-2a400880-a548-11eb-91d9-1f4626bb9c96.png)

**Comment by MisterSirCode** [comment]
Someone else may need to confirm this on their end. Cant reproduce myself.
@Malar10 Its very much possible it could be a client sided issue with your device.

Stuttering has been commonly associated with framerate jumps. Are you running the game past 60 fps?

**Comment by Malar10** [comment]
@MisterSirCode That is very odd.
No, I'm not running the game past 60fps. I have Vsync on every frame and my geforce overlay says it usually stays at around 60.
It does sometimes go to 61-62 for some reason, but I don't think it would cause this big of a problem.

Can you try a test like I did with the scripts (shoot every tick) to see if it really is on my side

**Comment by MisterSirCode** [comment]
Well, if youre shooting every single tick, its bound to create lag and stuttering. The more objects there are in a scene moving, the more bodies have to have velocity and speed calculated and applied to their positions. I'm assuming each of those bullets are also sending out raycasts towards voxel surfaces to apply damage to them.

**Comment by Malar10** [comment]
I don't want to be rude but you clearly didn't look at the edit at the bottom where I put the shoot script test lol

Basically I just used the basic shoot() function to easily see any weirdness and I don't believe the shooting is the root cause of the stuttering.
It was a constant stream, but when I paused it started having random gaps and stuttering in the "beam"
Gaps in the beam means the timing between calls of the function are irregular and therefore the timing between ticks is irregular

And since this all only happens after I open the pause menu, I believe it really is causing some problems
Not even with incredible amounts of explosives did I manage to create this kind of consistent stuttering

Not sure what you mean by that last question but it does seem to affect any script that heavily relies on timing or when a lot of the logic is inside the tick() function (see video example with mod affected by bug)

**Comment by tuxedolabs** [comment]
I found two issues here. It's related to the update/tick calling order. tick() is guaranteed to run exactly once per frame and it can be followed by zero, one or two calls to update depending on frame rate. The issue was related to time accumulating even when paused, which caused the game to try and catch up after unpause and could initiate an oscillating state in some cases. This could always happen when the hardware is very close to managing 60 fps, so this could still happen, just not as likely to be initiated by pause after this fix.

The Simple AI problem is due to the mod calling DriveVehicle from the update method instead of tick (see DriveVehicle documentation), which can cause exactly these kind of issues when the update ends up in an oscillating state.
