### ISSUE TITLE
[Bug] Creative mode camera movement behaves poorly at framerates higher than 60 

### ISSUE THREAD

**Issue by alekseiM88** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#350]
### Describe the bug

If player is in creative mode and the game is running at a framerate higher than 60 then camera movement is mildly to extremely unresponsive, depending on just how high the framerate is.

### Steps to reproduce the behavior

1. Make sure vsync is disabled, and that settings are lowered as is needed to run the game above 60 FPS, the higher the framerate the more apparent this issue is.
2. Load a sandbox level.
3. Enter creative mode and try looking around.

### Expected behavior

Smooth and responsive movement like what is seen at or below 60 frames per second.

### Environment

- Teardown Version 1.4.0

### Additional context

Modifying creativemode.lua so that handleCamera() is called from tick() rather than update() seems to fix this issue.

**Comment by tuxedolabs** [comment]
Confirmed bug. Fixed in 1.4.0 patch 1. Thanks for reporting!
