### ISSUE TITLE
[Bug] Game crashes when clicking a specific textbox and clicking away

### ISSUE THREAD

**Issue by Malar10** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#352]
### Describe the bug

The game crashes when clicking the textbox and then clicking away from it.
This only seems to work with the textbox in the "Open level" tab in the editor.

### Steps to reproduce the behavior

1. open the game
2. go edit a level (copy an existing one if you need to)
3. click File -> Open
4. click the text box
5. click anywhere outside of the text box
6. game crashes

[video of me reproducing the bug](https://cdn.discordapp.com/attachments/768940642767208468/1119620445604417567/Desktop_2023.06.17_-_16.08.50.06.mp4)

### Expected behavior

the game should not crash

### Environment

- Teardown Version 1.4.0
- OS: Windows 10 Home, Version: 10.0.19045 Build 19045
- GPU: NVIDIA GeForce RTX 2060
- Graphics driver version: 27.21.14.6677
- CPU: AMD Ryzen 7 2700 Eight core processor

### Additional context

The game does NOT crash if you have interacted with any other text box since opening the game.
(object properties, the "save as" textbox, etc.)

**Comment by tuxedolabs** [comment]
Bug confirmed. This was introduced with ImGui upgrade. Implemented a fix for 1.4.0 patch 1. Thanks!
