### ISSUE TITLE
[Feature] Creative Controls Unusuable with non-QWERTY layout

### ISSUE THREAD

**Issue by PoemOnTyperacer** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#353]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Creative controls are unusable with non-QWERTY layouts.
For example, on AZERTY, where ZQSD is the equivalent of WASD, pressing Q results in the player going left and up at the same time.

### Describe the solution you'd like

Creative controls need to be remappable.

### Describe alternatives you've considered

In the meantime, creative mode is unusable for me, barring a remap of my ZQSD controls to remove the conflict on Q and Z, which is not practical

**Comment by Thomasims** [comment]
I had already reported this with a fix directly but I'll put the code here if anyone needs this working right now:

in `creativemode.lua` on line 108, `game.input.forward` and `game.input.left` should be `options.input.keymap.forward` and `options.input.keymap.left` respectively.

**Comment by tuxedolabs** [comment]
I have applied the suggested fix, so should be resolved in 1.4.0 patch 1. In my tests, this is only an issue if Windows input is set to QWERTY, but using AZERTY keymapping in Teardown. Thanks for reporting!
