### ISSUE TITLE
unbreakable tag not working!

### ISSUE THREAD

**Issue by glkdrlgkrlzflnjkgh** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#354]
### Describe the bug

so i added the tag unbreakable into my custom map lockelle jam:the break in to a door and nothing happened in game. The door could still be smashed to pieces!

### Steps to reproduce the behavior

add unbreakable tag to a door in hiest example then apply the chang and in game nothing happens.

### Expected behavior

the object wont break.

### Environment

latest updat creative mode 
windows 11
6core cpu

### Additional context

nothing to see here

**Comment by Please-Pick-a-Name** [comment]
in where, name property?

**Comment by tuxedolabs** [comment]
Can not reproduce. Works as expected.
