### ISSUE TITLE
azerty layout not made for creative mode/creative mode keybinds not editable

### ISSUE THREAD

**Issue by krunkske** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#355]
### Describe the bug

azerty layout not made for creative mode/creative mode keybinds not editable

### Steps to reproduce the behavior

see title

### Expected behavior

to be able to change the keybinds

### Environment

- Teardown Version e.g. 1.4.0
- OS: Windows 11 64 bit
- GPU: Nvidia GeForce 1650
- Graphics driver version: not relevant 
- CPU: AMD Ryzen 7 3750H

**Comment by Thomasims** [comment]
Duplicate of #353

**Comment by krunkske** [comment]
Did not see that one. Sorry for the duplicate post.
