### ISSUE TITLE
[Bug] Heavy machinery features

### ISSUE THREAD

**Issue by Eblancher** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#356]
### Describe the bug

So for whatever reason when I spawn in more than one dump truck, it causes the raise and lower bed controls to not work. This is happening to every heavy machine

### Expected behavior

I was hoping to be able to spawn in a new dump truck in case one got destroyed

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows/Linux]
- GPU:
- Graphics driver version:
- CPU:

**Comment by UwQ-Official** [comment]
What mods are you spawning from? The built-in heavy machinery shouldn't do that

**Comment by Eblancher** [comment]
I think it was the shreadozer mod

**Comment by UwQ-Official** [comment]
That's most likely because the mod wasn't optimized for spawning. So it's not really a game bug

**Comment by Eblancher** [comment]
Ok, thanks for the clarification.

**Comment by Please-Pick-a-Name** [comment]
why is this still open @Thomasims
