### ISSUE TITLE
[Bug] Slash character in mod name creates subfolder on local copy

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#36]
**Describe the bug**
Slash character in mod name creates subfolder on local copy

**To Reproduce**
1. Subscribe to mod 'Train Derailing and Chase Map'
2. Click on Local Copy
3. Look at folder structure

**Expected behavior**
Slash characters in `into.txt` name value should either be replaced or not create subfolder on local copy.

**Screenshots**
![Screenshot from 2021-04-28 20-26-29](https://user-images.githubusercontent.com/1898194/116455151-0be84e80-a861-11eb-9839-2f8b95d38237.png)

**Environment**
 - Teardown Version 0.7.0
 - OS: Linux and Windows

**Additional info**
Before the creator updates the `info.txt`, this is the current one
```text
name = Train Derailing/Chase Map
author = Resident Emil, Tkmined
...
```

**Temp fix**
Move files from subfolder to main mod folder to use/edit/start the mod.

**Comment by tuxedolabs** [comment]
Nice catch, thanks for reporting! I have fixed the issue in 0.7.1
