### ISSUE TITLE
[Bug] Game crash if two wheels have the same name in Magica Voxel

### ISSUE THREAD

**Issue by TTFH** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#363]
### Describe the bug

If there are 2 or more shapes with the same name in Magica Voxel and one of those shapes is used as a wheel the game will spawn a ghost copy of the wheel shape close to the (0, 0, 0) coordinates, this new breakable shape will spawn at the same distance to the world origin as it's original distance to the center of the vehicle. The original wheels may or may no spawn.

Test map:
[Content Mod.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/11937922/Content.Mod.zip)

### Steps to reproduce the behavior

1. Extract the test map
2. Play the map
3. Notice ghost wheels
4. Shoot both explosives
5. Game crash

### Expected behavior

For the game not to crash and only one copy of the wheels to spawn.

### Environment

- Teardown Version 1.4.0 (patch 1)
- OS: Windows 11
- GPU: NVIDIA GeForce GTX 1050 Ti
- Graphics driver version: 30.0.14.7212 / 31.0.15.3179
- CPU: i5 6500

### Additional context

This bug has happen since the first version of the game, there are multiple maps in the workshop with this problem.
A few examples:
https://steamcommunity.com/sharedfiles/filedetails/?id=2414773887
https://steamcommunity.com/sharedfiles/filedetails/?id=2415637896

**Comment by Please-Pick-a-Name** [comment]
#324
