### ISSUE TITLE
[Feature] Animation System

### ISSUE THREAD

**Issue by hotcocoadotcom** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#367]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I think there should be some kind of easy animation system in the editor or with lua scripts, with keyframes, tweening, and some other useful features. This would be very useful for cutscenes in story based mods

### Describe the solution you'd like

A simple way to make animations in the editor. I'm not expecting this to be a feature, but I wish it would at least be considered.

### Describe alternatives you've considered

I have considered an animation system made with the existing API, but it would require much work for coders who dont have a deep knowledge in lua scripting. These animation systems may also be inefficient and hard to work with.

**Comment by YuLun-bili** [comment]
1.6.0?

**Comment by hotcocoadotcom** [comment]
Solved. I'll close this
