### ISSUE TITLE
[Question] Does Teardown use anti-aliasing when showing text with UiText()?

### ISSUE THREAD

**Issue by squarebracket-s** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#369]
**Question**
I'm using pixelated fonts in my mod. They aren't pixelated when using font sizes approximately below 35.
![Picture of the font in different sizes](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/100999666/9a4ab8c3-f0b8-4ac7-a067-aa38c03504b8)
Is that intended or is it because of its size?
If it is intended, I'd like an optional parameter for UiText() for the ability to disable it.

[Font link](https://www.1001fonts.com/pix-pixelfjverdana12pt-font.html)

**Comment by Thomasims** [comment]
I don't understand what you're expecting to happen here, if the text wasn't scaled this way it would look awful regardless of the font (nearest-neighbor does not look great for text).
If you want good pixelation at such a small scale you're gonna have to find a font with a lower starting resolution.

**Comment by squarebracket-s** [comment]
> I don't understand what you're expecting to happen here, if the text wasn't scaled this way it would look awful regardless of the font (nearest-neighbor does not look great for text). If you want good pixelation at such a small scale you're gonna have to find a font with a lower starting resolution.

Oh so this was just me basically rambling about the fact that fonts look bad when scaled down...
I'll consider your suggestion and try out other ways of showing small pixelated fonts then.
