### ISSUE TITLE
[Bug] Game - vehicles with no powered wheels can move using A and D while driving

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#37]
Any vehicle which have no powered wheels can move using A & D keys, no matter how the vehicle is driven, by player or scripts

**To Reproduce**
1. Make a vehicle and set all wheels no power and no steering
2. Drive it only using A & D
3. It moves... yes

**Expected behavior**
Certainly it shouldn't move at all

**Video**
https://discord.com/channels/760105076755922996/768940642767208468/837048696418992180

**Environment**
This shouldn't matter I think, I found this bug in 0.6 but at that moment they aren't such "powerful", you can see from the video that my truck is rolling backwards sometimes but actually is the trailer attached pulling it

**Comment by tuxedolabs** [comment]
I suspect you have a really high value on "steerassist" that is causing this. Set steerassist to zero and the problem should go away. Please close issue if it works. Thanks!
