### ISSUE TITLE
[Bug] Cyrillic filenames make local copy fail

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#370]
### Describe the bug

Any cyrillic filename will block the folder and anything that comes after

### Steps to reproduce the behavior

1. Publish mod with files in cyrillic
2. Subscribe to mod
3. Make local copy
4. See missing files or even full system freeze/crash

### Expected behavior

No freeze/crash
Should copy the files

### Environment

- Teardown Version 1.4.0 Patch 1
- OS: Linux/Proton

**Comment by YuLun-bili** [comment]
closing this one since nobody would dig into history...
