### ISSUE TITLE
[Bug] Many shape-related functions does not work with tool shape

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#371]
### Describe the bug

The following functions does not work on shapes coming from a tool:

- `GetShapeMaterialAtIndex()` => always return empty
- `GetShapeMaterialAtPosition()` => always return empty
- `CopyShapePalette()` => seems to completely erase the palette of the shape (future calls to `GetShapePalette()` returns empty list, calls before copy returns proper results though)
- I did not test with the other new shape editing functions, but I fear most of them wouldn't work either.

### Steps to reproduce the behavior

1. Get tool body.
2. Get one shape from tool body.
3. Call one of the functions above on that shape.
4. Observe erroneous result.

### Expected behavior

All shape-related functions works on the tool shapes as they do on all other shapes.

### Environment

- Teardown Version: 1.4.0
- OS: Windows 10
- GPU: NVIDIA GeForce GTX 960M
- Graphics driver version: 531.79
- CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz 2.59 GHz

### Additional context

Some of the body-related functions may not work either on the main tool body, would be nice if they all did.

**Comment by Thomasims** [comment]
I can't reproduce any of this, all the functions work just fine for me. Are you certain you have the right handles?

**Comment by FlorentP42** [comment]
Well this is what I tried to do in `tool.lua` of the [Hungry Slime](https://steamcommunity.com/sharedfiles/filedetails/?id=2695893023&searchtext=hungry+slime) mod:
```Lua
function tool.run()

    if tool.tool.input.isShooting() then -- Shooting.
        Gun.actions.shoot()
    end

    if tool.tool.input.didReset() then -- Pressed Reset.
        Gun.actions.reset()
    end

    if tool.tool.input.didHalf() then -- Pressed Half.
        Gun.actions.half()
    end

    if tool.tool.input.didLimit() then -- Pressed Limit.
        Gun.actions.limit()
    end

    if tool.tool.input.endLimit() then -- Released Limit.
        Gun.actions.endLimit()
    end

    if  GetString("game.player.tool") == tool.tool.setup.name then
        local t = Transform()
        t.pos = Vec(0.6,-0.3,-0.7)
        -- DebugPrint("pos("..tool.tool.x..","..tool.tool.y..","..tool.tool.z..")")
        SetToolTransform(t)
        -- This is broken in current version of the game
        -- Update slime tool color
        local toolCenter = nil
        if tool.tool.toolShape == nil then
            local toolBody = GetToolBody()
            dbp("toolBody="..toolBody)
            local toolShapes = GetBodyShapes(toolBody)
            tool.tool.toolShape = toolShapes[1]
            dbp("tool.tool.toolShape="..tool.tool.toolShape)
            toolCenter = AabbGetShapeCenterPos(tool.tool.toolShape)
            dbp("toolCenter="..VecStr(toolCenter))
            local hit, point, normal = GetShapeClosestPoint(tool.tool.toolShape, toolCenter)
            if hit then
                toolCenter = point
            end
            dbp("voxCenter="..VecStr(toolCenter))
            local voxelIndex = GetVoxelIndex(tool.tool.toolShape, toolCenter)
            dbp("voxelIndex="..VecStr(voxelIndex))
            local type, r, g, b, a, entry = GetShapeMaterialAtIndex(tool.tool.toolShape, voxelIndex)
            tool.tool.entry = entry
            dbp("type="..type)
            dbp("r="..r)
            dbp("g="..g)
            dbp("b="..b)
            dbp("a="..a)
            dbp("entry="..entry)
        else
            toolCenter = AabbGetShapeCenterPos(tool.tool.toolShape)
        end
        -- Extract tool shape palette
        local content = GetShapePaletteContent(tool.tool.toolShape)
        dbp("tool.tool.entry="..tool.tool.entry)
        dbp("content="..json.encode(content))
        for i=1,#content do
            content[i].r = regGetInt('slime.color.r')/255
            content[i].g = regGetInt('slime.color.g')/255
            content[i].b = regGetInt('slime.color.b')/255
            content[i].emissive = regGetFloat('slime.glow')
        end
        SetShapePaletteContent(tool.tool.toolShape, content)
    end

end
```
Leading to the results I described above...

Note that this relies on your `GetShapePaletteContent()` / `SetShapePaletteContent()` functions that are not yet included in the latest version of the mod on the workshop.

Also note that the loop at the end should not be necessary, I just tried that as a last resort after all else failed, but I originally was only updating the content with the index having the same value as `entry`.

**Comment by Thomasims** [comment]
One thing I can see immediately is that you're using `GetShapeMaterialAtIndex` wrong, it takes 4 parameters (shape, x, y, z) not 2. I'm not sure why you're translating world pos into index since we also have `GetShapeMaterialAtPosition`, the result point of `GetShapeClosestPoint` should be perfectly fine to feed into it directly.

As for my shape utils functions you seem to be using them correctly, either there's a bug in shape utils (I doubt this is the case here, I'm effectively using the same method in the physgun), or you're feeding it bad data. I'd check the content table after that loop.

**Comment by FlorentP42** [comment]
🤦‍♂️ Well I was probably really tired when I wrote that piece of code -_-
Good catch on the bad usage of `GetShapeMaterialAtIndex()`, I will try again with the correct call and see what happen.
And yeah I probably don't need that index at all, I may have copy pasted a few lines from one of my other mods without thinking too much about it...

**Comment by FlorentP42** [comment]
Okay so I did a few more tests and learnt a few more thing: First of all, it appears that the tool body is fully recreated every time you unselect/reselect a tool? This was unexpected, I thought it would only be hidden somewhere when unused, which also means the whole logic behind the code above to store the shape only once would not work.

Then, the first time I enter this function call, the tool body is something completely unexpected: it has two shapes in it (mine has only one), each shape having only one voxel in them (this is totally unrelated to the current tool or any other tool that I know of...), so this is why my initial voxel color pick is giving wrong results: it comes from that unknown 1-voxel shape...

Code sample that revealed that unknown initial tool body:
```Lua
...
    if  GetString("game.player.tool") == tool.tool.setup.name then
        local t = Transform()
        t.pos = Vec(0.6,-0.3,-0.7)
        -- DebugPrint("pos("..tool.tool.x..","..tool.tool.y..","..tool.tool.z..")")
        SetToolTransform(t)
        -- This is broken in current version of the game
        -- Update slime tool color
        local toolCenter = nil
        local toolBody = GetToolBody()
        dbp("toolBody="..toolBody)
        local toolShapes = GetBodyShapes(toolBody)
        dbp("#toolShapes="..#toolShapes)
        for i=1,#toolShapes do
            local sh = toolShapes[i]
            dbp("toolShapes["..i.."]="..sh)
            dbp("valid="..BoolToStr(IsHandleValid(sh)))
            dbp("voxels="..GetShapeVoxelCount(sh))
            local tr = GetShapeWorldTransform(sh)
            dbp("pos="..VecStr(tr.pos))
            dbc(tr.pos, 0, 1, 0, i/2)
            local center = AabbGetShapeCenterPos(sh)
            dbp("center="..VecStr(center))
            dbc(center, 1, 1, 1, i/2)
        end
    end
...
```

**Comment by FlorentP42** [comment]
Also it appears that calling `GetShapePaletteContent()` / `SetShapePaletteContent()` every tick while modifying the palette inbetween seems to get exponentially laggy over time... Any clue why that is?

Another interesting behavior of `SetShapePaletteContent()` is that us seems to add elements on its own up to 252... Is that intended?
So if you have a palette with only one content element from `GetShapePaletteContent()`, then you call `SetShapePaletteContent()` with this palette, and then call `GetShapePaletteContent()` again: the new palette will have 252 elements.

**Comment by FlorentP42** [comment]
I got it to work with the following code. But still I run into the error case ever time I swap tool, meaning to tool body is not always accurately matching with the value returned by `GetString("game.player.tool")` which is a bit annoying...
```Lua
    if GetString("game.player.tool") == tool.tool.setup.name then
        local t = Transform()
        t.pos = Vec(0.6,-0.3,-0.7)
        -- DebugPrint("pos("..tool.tool.x..","..tool.tool.y..","..tool.tool.z..")")
        SetToolTransform(t)
        -- If tool was just selected
        local toolBody = GetToolBody()
        if toolBody ~= tool.tool.toolBody then
            tool.tool.toolBody = toolBody
            tool.tool.updateColor = true
        end
        -- If color update needed
        if tool.tool.updateColor then
            -- Update slime tool color
            dbp("toolBody="..toolBody)
            local toolShapes = GetBodyShapes(toolBody)
            if #toolShapes ~= 1 then
                dbp("Body has unexpected amount of shapes: "..#toolShapes..", skip recolor this tick")
                return
            end
            local toolShape = toolShapes[1]
            -- Extract tool shape palette
            local content = GetShapePaletteContent(toolShape)
            if (#content ~= 1) and  (#content ~= 252) then
                dbp("Palette has unexpected content: "..#content..", skip recolor this tick")
                return
            end
            for i=1,#content do
                content[i].r = regGetInt('slime.color.r')/255
                content[i].g = regGetInt('slime.color.g')/255
                content[i].b = regGetInt('slime.color.b')/255
                content[i].emissive = regGetFloat('slime.glow')
            end
            SetShapePaletteContent(toolShape, content)
            tool.tool.updateColor = false
        end
    end
```

**Comment by Thomasims** [comment]
Yea tool bodies get recreated fairly often (tool swap, driving vehicles, etc) and you have to skip a frame when the player just changed tool. That's just game behavior you'll have to adjust to though, you can have a look at UMF if you want to see all (known) edge cases like this.

I'm not sure why `SetShapePaletteContent` would get laggier over time since it does cleanup itself. The 252 thing is because the workaround can't generate arbitrary palette indices, it has to build up for 1 and any "holes" have to have *something* so it's best to cache the palette and not call `GetShapePaletteContent` again.

I think the initial issue is resolved then, if you want to continue the troubleshooting for shape utils you should make an issue on https://github.com/SpunkyTheHedgeHog/Teardown-Totally-Documented/issues since that's where I host that file.
