### ISSUE TITLE
[Bug] Inactive bodies do not cast shadows

### ISSUE THREAD

**Issue by squarebracket-s** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#374]
### Describe the bug

I was making a spawn room for my map. While I was testing scripts, I noticed there was light going through the door after a few seconds of not interacting with it.

### Steps to reproduce the behavior

1. Make a room with 1 cut-out wall with another flat object covering the hole (as shown in the video)
2. Play the map
3. Wait for a few seconds
4. Light goes through the flat object covering the hole

### Expected behavior

Light would not go through the covering shape.

https://files.catbox.moe/znfizl.mp4 (Github only allows less than 10mb)

### Environment

- Teardown Version 1.4.0 (patch 1)
- OS: Windows
- GPU: NVIDIA GeForrce GTX 960M
- Graphics driver version: 536.67
- CPU: Intel(R) Core(TM) i5-63000HQ @ 2.30GHz

### Additional context

-I disabled all mods except for a few that did not modify any behavior of the bodies/shapes
(Only Gmod-esque menu was used)
-Sorry for the potato quality
-I'm new to mapmaking so I may not know specific stuff

**Comment by nooitaf** [comment]
I assume it's related to your very low quality settings? 
.. Try it with these and see if it's still the case
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/bac6d348-4af2-43a3-9129-74db733a5d9b)

**Comment by Thomasims** [comment]
It's due to the door not being aligned to the world voxel grid, that tends to confuse the shadow volume generation and slight changes can make it move in and out of alignment.

I'm guessing you can't make it 2 voxels thick? that's usually the solution for this particular problem.

**Comment by squarebracket-s** [comment]
> I assume it's related to your very low quality settings? .. Try it with these and see if it's still the case ![image](https://user-images.githubusercontent.com/1898194/256221532-bac6d348-4af2-43a3-9129-74db733a5d9b.png)

I tried that already. Didn't fix it. <br> <br>

> It's due to the door not being aligned to the world voxel grid, that tends to confuse the shadow volume generation and slight changes can make it move in and out of alignment.
>
> I'm guessing you can't make it 2 voxels thick? that's usually the solution for this particular problem.

Both solutions work, though I want a small gap, so I thickened the door and the wall.
