### ISSUE TITLE
[Bug] Game freezes and then crashes to desktop.

### ISSUE THREAD

**Issue by profande** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#375]
### Describe the bug

While playing the game it will freeze for a moment then crash to desktop with an exit code of *`0xC0000409`. This happens after a random amount of time of playing the game. 

I experience this issue with or without mods and it does not appear to happen while in the main menu. 

*I don't always get this code, I have seen `0xC0000005` (Access Violation), but most of the time it is `0xC0000409`.

### Steps to reproduce the behavior

Unfortunately, I don't have a clue what's causing this and due to the randomness as to when the crash occurs, I have no idea how to reproduce it.

### Expected behavior

The game continues to play.

### Environment

- Teardown Version 1.4.0 (patch 1)
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 3080
- Graphics driver version: 531.79
- CPU: AMD Ryzen 5 5600X

**Comment by profande** [comment]
### Update
I updated my graphics drivers and when I run the game I now get a consistent access violation. Out of curiosity, I ran the game in a debugger and found that the error is taking place within `nvogl.dll` with the User Data Execution Prevention being the main culprit of the crash. 

At this point, I don't know if this is an engine bug or if it's a driver bug.

**Comment by YuLun-bili** [comment]
Closing. `nvogl.dll` is not delivered by game but by Nvidia, suggest reinstalling graphics drivers.
