### ISSUE TITLE
[Feature] Add frame rate limiting - a proper frame rate management system

### ISSUE THREAD

**Issue by Hedreon** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#377]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

This feature should be added so we can limit our frame rates (FPS) to a number we want, similar to Minecraft (The different options UI is coming from a mod called "Sodium"):

![Screenshot](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/39467046/985c1985-045c-4c52-afb8-1a2d304bdfae)

Why do I want this added? it is so people can be able to limit their frame rates due to something like, for example, preventing their fans from getting loud, letting the computer not do as much work as if without it, etc

### Describe the solution you'd like

What I want to happen is to have a slider in the Options UI (increments by 5 each, "slide" i guess) where people could adjust their maximum frame rates.

### Describe alternatives you've considered

None.

### Additional context

With no files ever modified, I get ~400-700 FPS in just the menu itself, now that could be quite some work for the computer.

Screenshot:

![Teardown](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/39467046/7430048d-4f0a-4d89-8e0c-783917bfb8da)

Details may be subject to change.

**Comment by Hedreon** [comment]
Wrong place to provide feature requests to.

**Comment by UwQ-Official** [comment]
> Wrong place to provide feature requests to.

Wdym?
