### ISSUE TITLE
[Feature] Draw sprites with depth

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#38]
Sprites drawn behind each other only draw correctly in one direction. They seem to always get drawn in the same dimensional order. If you have multiple sprites behind each other they don't overlay correctly if looked at from different directions.

**Suggestions:**
Either add `order` property to `DrawSprite()` or order them automatically depending on camera position.

![Screenshot from 2021-05-02 15-00-56](https://user-images.githubusercontent.com/1898194/116814111-721deb80-ab57-11eb-8736-a756b62679b9.png)
![Screenshot from 2021-05-02 15-01-21](https://user-images.githubusercontent.com/1898194/116814115-74804580-ab57-11eb-84cd-39327128d2bb.png)
![Screenshot from 2021-05-02 15-01-40](https://user-images.githubusercontent.com/1898194/116814118-764a0900-ab57-11eb-9891-be4182e8bc72.png)
![Screenshot from 2021-05-02 15-02-25](https://user-images.githubusercontent.com/1898194/116814122-7813cc80-ab57-11eb-98d8-50c53b48ed81.png)

**Comment by ss-gnalvesteffer** [comment]
I encountered this when I was working on Teardown Tactical for my sprite-based NPCs. I had to sort the sprites to draw by their distance to the camera in order to get their depth corrected each tick.

Here's an example:
https://github.com/ss-gnalvesteffer/teardown-sprite-weapons/blob/main/sprite_weapons_and_npcs/npcs/init.lua#L18
https://github.com/ss-gnalvesteffer/teardown-sprite-weapons/blob/main/sprite_weapons_and_npcs/npcs/npc.lua#L5

**Comment by nooitaf** [comment]
Hmm, i thought i actually ordered them and found, however the order you draw them, they still get drawn in a specific order. The screenshots above should be ordered by distance to camera. But hope i just brainfarted and it's actually possible already. Will investigate.

**Comment by tuxedolabs** [comment]
Good suggestion! The sprites are already queued in the renderer, so adding depth sorting is easy. Will fix for 0.7.2. I also changed API so that color and alpha can be omitted and defaults to white with alpha 1.0

**Comment by ss-gnalvesteffer** [comment]
> Good suggestion! The sprites are already queued in the renderer, so adding depth sorting is easy. Will fix for 0.7.2. I also changed API so that color and alpha can be omitted and defaults to white with alpha 1.0

Awesome!
