### ISSUE TITLE
[Feature] More modding possibilities 

### ISSUE THREAD

**Issue by UwQ-Official** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#383]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

You can add possibility for things like custom materials, custom map objects (like `<vox/>`, `<screen/>`, etc.).

To make it easier (for you, the devs) you can force that to be in C++ instead of Lua

You can also make a moddable editor (so people can fix editor problems, instead of waiting months for an update (that may not solve the problem))

### Describe the solution you'd like

The mod file structure could include `materials.cpp` and `editor_objects.cpp` that may add custom features / modify current.

### Describe alternatives you've considered

None, it's not possible currently

### Additional context

Issues that you might have to resolve before that:
 - Limiting the possibilities of such scripts so that they can't be used for making viruses

**Comment by UwQ-Official** [comment]
Why did you close it @Thomasims ?

**Comment by Thomasims** [comment]
- It's incredibly vague
- The one concrete suggestion (extending the game with "C++" aka binary modules) is either very dangerous or _extremely_ difficult to make safe.
