### ISSUE TITLE
[Bug] Strange GSync behavior

### ISSUE THREAD

**Issue by AdrianTheFrog** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#385]
### Describe the bug

The game is locked at 60 FPS unless you enable G-Sync while the game is running.

### Steps to reproduce the behavior

1. Launch the game with GSync enabled in the Nvidia control panel
2. Enable VSync (any mode)
3. Game is locked at 60 FPS
4. Disable and Reenable G-Sync in the Nvidia control panel (apply settings after disabling and after reenabling)
5. GSync now works properly, the game is no longer locked at 60 fps and no screen tearing occurs with any VSync mode, including 'Disabled'. The monitor correctly adapts to the game's framerate, and gameplay is very smooth.

### Expected behavior

The game should be limited only to the monitor's max refresh rate, and the monitor should adjust its refresh rate to match the framerate of the game when GSync is enabled, regardless of when the setting is applied.

### Environment

- Teardown Version: 1.4.0 (patch 1) 
- OS: Windows
- GPU: Nvidia RTX 3060
- Graphics driver version: 537.42
- CPU: Intel Core i7 11700k
- Monitor: 1080p 144hz with AMD Freesync (Acer KG241Q Sbiip 23.6")

**Comment by YuLun-bili** [comment]
Game would always try to run at 60fps to ensure better physic simulation results. Set display setting to "borderless window" if you don't want to lock in 60fps
