### ISSUE TITLE
[Bug] Menus that don't work

### ISSUE THREAD

**Issue by Wellmare** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#389]
### Describe the bug

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/bc99c59c-65ee-4246-a254-47ebcc8b2e5b)
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/ca3acffa-1c80-47bd-9384-ce26525a3b75)
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/3ea8cbe3-9b27-4612-8c8d-48686f0db840)

In none of these menus does mouse clicking work. Moving and hovering works

### Steps to reproduce the behavior

1. Go to 'extensions'
2. Click on 'Destroyers of art'

### Expected behavior

Mouse response

### Environment

- Teardown Version 1.5
- OS: Windows
- GPU: rx460 2gb
- Graphics driver version:
- CPU:i5 7400

**Comment by Wellmare** [comment]
It looks like all the menus in the game don't work

**Comment by dannyTuxedoLabs** [comment]
Can you please provide some more information. We're troubleshooting this issue right now and can't reproduce it.

1. Screen/Monitor?
2. Resolution/mode?
3. Windows 10 or 11?

**Comment by Wellmare** [comment]
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/bf28554c-f8ad-4541-ba89-925d108aa6d0)
Monitor resolution 1366x768. Game resolution 1600x900. Mode in a window without a frame. Windows 11

**Comment by Wellmare** [comment]
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/d9547e45-d650-4ff6-ad58-8ba782ce86b4)
Also the buttons completely fail to work in the weather menu

**Comment by Wellmare** [comment]
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/101342758/fdd22529-8a25-454f-9b36-0f23a91b2df0)

The buttons are also not working after the update. Maybe console log will give more information

**Comment by Wellmare** [comment]
It's all because of the Sir codes menu mod
