### ISSUE TITLE
[Bug] GetTriggerBounds() with polygon type doesn't return correct bounding box

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#39]
**Describe the bug**
GetTriggerBounds() with polygon type doesn't return correct bounding box. It only seems to return the correct Y position.
Sphere and Box seem to work correctly.

**Environment**
 - Teardown Version 0.7.1
 - OS: Linux

**Comment by tuxedolabs** [comment]
Confirmed and fixed in 0.7.2. Thanks!
