### ISSUE TITLE
[Bug] ui_extensions.lua shadows table.concat

### ISSUE THREAD

**Issue by Thomasims** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#393]
### Describe the bug

The new UI extensions replace the base Lua function `table.concat` with a function that does not comply to the standard.
This is a problem because it forces modders to either completely ignore the new UI framework or otherwise not use this base function.

### Steps to reproduce the behavior

1. Create a new ui script that uses the new ui_extensions.lua
2. Attempt to use table.concat [as defined in the manual](https://www.lua.org/manual/5.1/manual.html#pdf-table.concat)

### Expected behavior

The function currently called `table.concat` in ui_extensions.lua should be renamed to something like `table.merge` to avoid shadowing existing functions.

### Environment

- Teardown Version: 1.5.0
- OS: n/a
- GPU: n/a
- Graphics driver version: n/a
- CPU: n/a

### Additional context

While it is possible to rewrite a standard-compliant `table.concat` function in Lua as a workaround, this would end up being much less performant and would still need to be named something else to avoid breaking ui extension functions that expect this non-standard behavior.

**Comment by x4fx77x4f** [comment]
You could (probably (not tested)) work around this by having a file like this (e.g. `workaround.lua`):
```lua
table.concat_ex = table.concat
```
and including from your main file like this:
```lua
--[[
#include "workaround.lua"
#include "ui_extensions.lua"
]]
table.merge = table.concat
table.concat = table.concat_ex
table.concat_ex = nil
```
This issue absolutely should be resolved. Absolutely no custom values should be going in the tables used by standard libraries, especially when they have keys that clobber existing values.
