### ISSUE TITLE
With norton 260 you get a message saying teardown has a invalid digital signature

### ISSUE THREAD

**Issue by Crowley606** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#394]
### Describe the bug

Not sure what it is, all i know is norton don't like it but when i ignore the message nothing happens in game so i believe its just an error/bug.

### Steps to reproduce the behavior

1. have norton 360 install with subscription active.
2. Click on 'Teardown to start'
4. See error when you start the game.

### Expected behavior

N/A

### Environment

- Teardown Version (patch 1.5.0) 
- OS: Windows 11
- GPU: RTX 3070 8gb VRAM
- Graphics driver version: Newest one by 26th October 
- CPU: Intel core I7_-11700f 11th gen

**Comment by YuLun-bili** [comment]
already fixed
