### ISSUE TITLE
Mods installed are not enabled and after enabling them, playing a map for a while and going to the main menu and then checking it shows all disabled.

### ISSUE THREAD

**Issue by Crowley606** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#395]
### Describe the bug

All mods are disabled on start and after re enabling all and then playing on a map for a bit and going to the main menu it shows all mods disabled.

### Steps to reproduce the behavior

1. load teardown
2. go to the mods tab
3. it shows all disabled
4. enable all
5. enter a modded map, sandbox or campain.
6. Return to main menu
7. All mods should be disabled

### Expected behavior

all mods that i enabled before the experimental branch update to be enabled.

### Environment

- Teardown Version 1.5.0
- OS: Windows 11
- GPU: RTX 3070 8gb VRAM
- Graphics driver version: newest one before 26th october
- CPU: Intel core i7-11700f , 8 cores , 11th gen

**Comment by Thomasims** [comment]
It looks like the engine is writing some mod registry values under `<modid>.<field>` rather than `mods.available.<modid>.<field>` like it used to (and like the ui code expects).

**Comment by YuLun-bili** [comment]
game only made that wrong in main menu, in scenes are still normal
