### ISSUE TITLE
[Bug] Marina Map (Campaign, Sandbox, possibly other modes, through map glitch)

### ISSUE THREAD

**Issue by BMEC-1400** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#4]
It is possible to drive the large fishing trawler into the Lee Company Warehouse on the Marina map, if you do not exit prior to the wheelhouse being destroyed, you will glitch under the map when you exit.   See photos:

![image](https://user-images.githubusercontent.com/80723685/111231994-9716c900-85c0-11eb-9694-2f2ae3e130b6.png)
![image](https://user-images.githubusercontent.com/80723685/111232158-ed840780-85c0-11eb-8b23-1a12c04b7756.png)

**Comment by CoolJWB** [comment]
I think this was deemed impossible/too hard to fix as we can't really figure out when the player is in an invalid place.
