### ISSUE TITLE
[Bug] Game crash when loading level or quick save on Linux

### ISSUE THREAD

**Issue by Redkefy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#40]
**Describe the bug**
Sometimes when loading a level or a quick save the game crash on the Loading screen and closes

**To Reproduce**
Load a level or a quick save in campaign

**Expected behavior**
The game should load with no issues

**Environment**
 - Teardown Version 0.7.2
 - Proton Version: 6.3-3
 - OS: Linux Mint 20.1
 - GPU: Nvidia GTX 980 4GB
 - Graphics driver version: 460.73.01
 - CPU: Intel i7 4770k 3,5 GHz

**Comment by tuxedolabs** [comment]
Linux is not officially supported and we don't have Linux set up for debugging, so probably won't get fixed.
