### ISSUE TITLE
[Bug] Incorrect ui word wrap behavior with game language set to chinese

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#410]
### Describe the bug

https://discord.com/channels/760105076755922996/768940642767208468/1167851285324775476
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/dfd6ef27-9c2b-4db5-b5a4-9257e897b70d)

### Steps to reproduce the behavior

1. create mod with plain english description
2. Set Game language to chinese
3. Go to mod manager
4. See bad word wraping behaviour

alternative:
1. create mod with UiText() drawing some long english sentence
2. have UiWordWrap set to something reasonable
3. set game language to chinese
4. see words within sentences gets chopped in half

### Expected behavior

dont cut word in half

### Environment

- Teardown Version: 1.5.0
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:
- Language: Chinese

### Additional context

https://discord.com/channels/760105076755922996/768940642767208468/1167862751725633639

**Comment by YuLun-bili** [comment]
Japanese language also have this problem

**Comment by YuLun-bili** [comment]
Resolved in 1.5.4
