### ISSUE TITLE
[Bug] Calling PauseMenuButton with loc@ string thats too long cause it to not display text at all

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#415]
### Describe the bug

(i "injected" `DebugPrint(id..": "..textButton)` between line 1534 and 1535 in hud.lua)
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/640fdb74-d6a3-4b2c-bde5-a270a668074d)

### Steps to reproduce the behavior

1. Prepare localization key thats 35 character in length or more: 
2. Call PauseMenuButton with said key
3. ingame, check pause menu buttons
4. See an empty button

### Expected behavior

the PauseMenuButton only trim the actual text that is displayed, NOT the localization key

### Environment

- Teardown Version: 1.5.0
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

we are finding obscure bugs everyday :muscle:

**Comment by dannyTuxedoLabs** [comment]
Thanks for your input. We're troubleshooting this issue and other localization bugs as we speak. Can you please provide a screenshot of the data/texts folder and send me the localization file that you're currently using. Thanks!

**Comment by Please-Pick-a-Name** [comment]
> Thanks for your input. We're troubleshooting this issue and other localization bugs as we speak. Can you please provide a screenshot of the data/texts folder and send me the localization file that you're currently using. Thanks!

the same as the one in #416 https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/416#issuecomment-1786887821

**Comment by Please-Pick-a-Name** [comment]
This has been fixed
