### ISSUE TITLE
[Bug] Localization doesnt work in options.lua

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#416]
### Describe the bug

ASSUMING THE CORRECT WAY TO ADD LOCALIZATION IS BY ADDING A FILE IN data/texts WITH THE CORRESPONDING FILE NAME

if i try to reference my own localization key in the options.lua, the game dont even draw anything

### Steps to reproduce the behavior

1. Prepare some localization strings
2. Try to reference the localization strings in options.lua
3. Nothing is drawn

### Expected behavior

Have string drawn

### Environment

- Teardown Version: 1.5.0
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

the localization file: 
```
PPAN_ADVSPEEDO_OPTIONS_VARIANTS_TEXT				"Variant: {STRING}"
PPAN_ADVSPEEDO_VARIANT_				"Clean"
PPAN_ADVSPEEDO_VARIANT_VAN				"Vanilla"
PPAN_ADVSPEEDO_VARIANT_ADV				"Advanced"
```

```lua
if UiTextButton("loc@UI_BUTTON_RESET_TO",210,40)then
	default()
end
UiTranslate(0,-50)
local txt = GetBool("savegame.mod.mph") and "loc@UI_BUTTON_IMPERIAL_MPH" or "loc@UI_BUTTON_METRIC_KM/H"
if UiTextButton(txt,210,40)then
	SetBool("savegame.mod.mph",not GetBool("savegame.mod.mph"))
end
UiTranslate(0,-50)
if UiTextButton("loc@PPAN_ADVSPEEDO_OPTIONS_VARIANTS_TEXT,"..GetVarientName(),210,40) then
	CycleVarients()
end
```
(function GetVarientName() returns "PPAN_ADVSPEEDO_VARIANT_", "PPAN_ADVSPEEDO_VARIANT_VAN" or "PPAN_ADVSPEEDO_VARIANT_ADV")
the above code produced:
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/d34741c8-d7b9-4891-a251-21af0f4e2381)

**Comment by dannyTuxedoLabs** [comment]
Thanks for reporting this! Can you please elaborate a little on the steps you're taking to reproduce this issue. We're troubleshooting it as we speak. Can you also provide a screenshot of the data/texts folder and send me the localization file that you're currently trying to use. Cheers!

**Comment by Please-Pick-a-Name** [comment]
> Thanks for reporting this! Can you please elaborate a little on the steps you're taking to reproduce this issue. We're troubleshooting it as we speak. Can you also provide a screenshot of the data/texts folder and send me the localization file that you're currently trying to use. Cheers!

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/7b9aa73d-cd65-478d-a0ee-12c088855384)
(github do not like .str so i change the file extension to .txt)
[strings_english.txt](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13214871/strings_english.txt)

**Comment by Please-Pick-a-Name** [comment]
This has been fixed
