### ISSUE TITLE
[Bug] Mod class/object function definitions are nil after Quicksave -> Quickload

### ISSUE THREAD

**Issue by uFloppyDisk** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#42]
**Describe the bug**
My mod implements a class with a "new" function used to instantiate an object. The mod functions as expected after loading any level from the main menu. After a quicksave and quickload, the "new" function returns a nil value (Screenshot 1).

**To Reproduce**
1. [Subscribe](https://steamcommunity.com/sharedfiles/filedetails/?id=2497776711) to this demo mod on the Steam Workshop
2. Enable the "Object definition bug" mod
3. Load any sandbox map
4. Equip the "Object Bug" tool
5. Pause and click "Quick Save"
6. Pause again and click "Quick Load"
7. Press the LEFT mouse button

**Expected behavior**
The "OBJECTS length" DebugWatch should increase by 1 for every click of the LEFT mouse button. Each object should also create a new DebugWatch labeled "Object #<n>" (Screenshot 2)

**Screenshots**
1: https://i.imgur.com/LU0BSz6.png (error message for each of the three attempts to instantiate an object)
2: https://i.imgur.com/JqUS5ar.png (each object adds to the OBJECTS length variable and adds a new labeled DebugWatch)

**Environment**
 - Teardown Version **0.7.2** _[experimental branch]_
 - OS: **Windows 10 Pro** _(10.0.19042 Build 19042)_
 - GPU: **NVIDIA GeForce GTX 1080**
 - Graphics driver version: **465.89**
 - CPU: **Intel i9 9900K**

**Additional context**
Issue occurs regardless of if the file containing the class is imported using "#include" nor if the class is contained within "main.lua"

**Comment by Thomasims** [comment]
The Lua state quicksave method Teardown employs is far from perfect and has a few edge case that break even simple structures like this when referenced in _G. I (tried to) explain the reason for this [in this issue](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/5#issuecomment-811799295)

**Comment by CoolJWB** [comment]
See comment by Thomasims.
