### ISSUE TITLE
[Bug] [Experimental] Mod Manager invisible after exiting Editor

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#421]
### Describe the bug

Mod Manager is open but invisible after exiting the Editor,... when you click anywhere it shows up.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/af5868fc-0a20-42f1-9602-6aa10d4c4e7e

### Steps to reproduce the behavior

.

### Expected behavior

.

### Environment

- Teardown Version 1.5.0
- OS: Linux

**Comment by Please-Pick-a-Name** [comment]
"I have this issue aswell."
