### ISSUE TITLE
[Bug]lags when using search function in the spawn menu 

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#423]
### Describe the bug

whenever u type something in the spawn menu search bar it lags hard
also lags hard if you clear it with the "x" button

### Steps to reproduce the behavior

1. Go to any level
2. Pause
3. Click on spawn menu
4. Attempt to search something
5. LAGS

### Expected behavior

no lag (it wasnt lagging in 1.4.0)

### Environment

- Teardown Version: 1.5.0
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
Fixed? didn't notice lag on my end
