### ISSUE TITLE
[Bug] The surfacing of a sunken transport

### ISSUE THREAD

**Issue by Gondoplas** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#424]
bug

If the ship is, say, half drowned, then if you turn on the slow-motion mode, the ship will start to float. This also works with machines
Video - https://wdfiles.ru/1s106 (This is not a virus-link. It's just that you can't upload a video on GitHub, I used a link generator for the video.)

**Comment by nooitaf** [comment]
Here is your video.. Github doesn't accept `.avi` files.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/c680d7aa-27c2-4817-adf5-5949cb69ad6d

**Comment by YuLun-bili** [comment]
resolved in 1.5.4 since `SetTimeScale()` patched
