### ISSUE TITLE
[Bug] Game fatally crashes when quicksaving while using a mod with object definitions

### ISSUE THREAD

**Issue by uFloppyDisk** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#43]
**Describe the bug**
Teardown crashes to desktop when attempting to quicksave while instantiated objects exist.

**To Reproduce**
1. [Subscribe](https://steamcommunity.com/sharedfiles/filedetails/?id=2497776711) to this demo mod on the Steam Workshop
2. Enable the "Object definition bug" mod
3. Load any sandbox map
4. Equip the "Object Bug" tool
5. Press the LEFT mouse button
5. Pause and click "Quick Save"

**Expected behavior**
Game should quicksave and unpause.

**Screenshots**
1: https://i.imgur.com/JqUS5ar.png (DebugWatch output upon clicking the LEFT mouse button three times)

**Environment**
 - Teardown Version **0.7.2** _[experimental branch]_
 - OS: **Windows 10 Pro** _(10.0.19042 Build 19042)_
 - GPU: **NVIDIA GeForce GTX 1080**
 - Graphics driver version: **465.89**
 - CPU: **Intel i9 9900K**

**Additional context**
N/A

**Comment by CoolJWB** [comment]
The crash seems to be resolved.
