### ISSUE TITLE
[Feature] Invert Y Axis for Console edition (PS5, XSS, XSX)

### ISSUE THREAD

**Issue by bigAnt1991** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#432]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

There is no option for invert y axis in the input options as I am one of them few that use invert aiming and cannot aim the camera properly.

### Describe the solution you'd like

I would like it to be added in the input options as all other games have this option and would really appreciate it. 
Thanks

### Describe alternatives you've considered

I cannot think of an alternative option as this is an input related issue with a controller.

**Comment by Please-Pick-a-Name** [comment]
This has been implemented in the most recent console patch i believe, atleast i seen someone with ps5 posted a screenshot with the option
@Thomasims https://discord.com/channels/760105076755922996/1179323379619209267/1181978259890634752

**Comment by bigAnt1991** [comment]
Ok thank you, I've just checked on XSX and a patch has not yet been issued.
