### ISSUE TITLE
[Bug] Can still place planks while on a horse in time campers DLC

### ISSUE THREAD

**Issue by Figeltar** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#433]
### Describe the bug

When on a horse you can place planks on objects even though the hud doesn't show

### Steps to reproduce the behavior

1. Go on a horse and near some object
2. grab planks and place them like normal.

### Expected behavior

Not being able to place planks.

### Environment

- Teardown Version  1.5.1
- OS: Windows
- GPU: RTX 3060
- CPU: Intel core i6 4690K

**Comment by Please-Pick-a-Name** [comment]
this has been fixed @Thomasims
