### ISSUE TITLE
[Bug] In time campers dlc on the base map the flying car doesn't have hitboxes.

### ISSUE THREAD

**Issue by Figeltar** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#434]
### Describe the bug

You can basically walk through the flying car when you launch time campers dlc on the lockelle teardown services map the flying car does not have a hitbox.

### Steps to reproduce the behavior

1. Go to time campers dlc
2. Walk to home
3. Go turn on the fusebox
4. Go to the flying car and you will be able to jump inside of it as it has no collisions.

### Expected behavior

Collide with the car.

### Environment

- Teardown Version 1.5.1
- OS: Windows
- CPU: Intel core i6 4690K

**Comment by YuLun-bili** [comment]
already fixed in 1.5.3
