### ISSUE TITLE
[Bug] Time Campers - Terminal UI bug

### ISSUE THREAD

**Issue by nathangur** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#435]
### Describe the bug

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/84688324/02300fe1-ec73-4e1e-8238-20cad9cbc46a)

There isn't a tool tab in the Time Campers DLC. Nor are there valuables to be had. This is incorrect.

### Steps to reproduce the behavior

Hover over the cash in the top right hand corner in the terminal

### Expected behavior

There shouldn't be any cash.

### Environment

Version 1.5.1

**Comment by Please-Pick-a-Name** [comment]
this has been fixed probably since 1.5.2
