### ISSUE TITLE
[Bug] Escape vehicle not working in DLC

### ISSUE THREAD

**Issue by Crownviking** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#436]
### Describe the bug

In the Time Campers mission "Choo-choosing path", The escape vehicle won't let you in even after completing the requirement.

### Steps to reproduce the behavior

1. Go to 'Time Campers'
2. Start the mission 'Choo-choosing Path'
3. Complete the mission as intended
4. Press E at the escape vehicle

### Expected behavior

The player should enter the vehicle and complete the mission.

### Environment

- Teardown Version: 1.5.1
- OS: Windows
- GPU: GTX 1050 Ti
- Graphics driver version: 457.51
- CPU: AMD Ryzen 5 3400G

**Comment by dannyTuxedoLabs** [comment]
Hi! Can you please send us a video or screenshot showing this issue. It'll be easier for us to troubleshoot the issue.

**Comment by Crownviking** [comment]
> Hi! Can you please send us a video or screenshot showing this issue. It'll be easier for us to troubleshoot the issue.

Nevermind, it turns out I accidentally deleted a file.
