### ISSUE TITLE
[Bug] Game freeze and crash if tab out in full screen mode

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#438]
### Describe the bug

game display mode set to full screen, tab out from game (I have two monitors so even though game forces to stay on top I can still do that) and game crashes when I came back

### Steps to reproduce the behavior

- Might be easier to reproduce with 2+ monitors
1. set game mode to full screen (not borderless windowed)
2. tab out/ move mouse away and click outside game
3. back to game, game freezes and crashes

### Expected behavior

game would not freeze nor crash

### Environment

- Teardown Version 1.5.1
- OS: Windows 11 23H2 (22631.2428) (with Windows Feature Experience Pack 1000.22674.1000.0)
- CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
- GPU: NVIDIA GeForce MX250
- Driver ver:
  - DirectX: 31.0.15.4617 (nvldumd.dll 1.0.0.9)
  - OpenGL: 4.6

### Additional context

1. This issue existed since 1.5.0 [experimental] but for some reason I forgot to report...
2. Using DX12 at the time of crash

**Comment by 89537kay3** [comment]
I have this too, but only on launch. If it launches okay, i can't click out then alt tab.

**Comment by YuLun-bili** [comment]
Already fixed in 1.5.3
