### ISSUE TITLE
[Bug] UI interactions, including "Change Weather" do not work

### ISSUE THREAD

**Issue by 70UNIK** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#441]
### Describe the bug

Happening since v1.5, the UI functionality for the Change Weather menu is not working for me. This is also apparent for other mods, but I'm listing it here since it's a base function of the game that is not working. Basically, when I try to open the Change Weather menu, it cannot be interacted with. Worse, I'm stuck there, as I cannot press 'ESC' to get out of the menu. 

### Steps to reproduce the behavior

1. While in any map, press 'esc' to get to the pause menu
2. Find and click on 'Change Weather'
3. Try to click on any options, or even press 'esc'
4. If you cant do all of those, then there is a problem.

### Expected behavior

What should happen, is that when you go into the Change Weather menu, you should be able to select the buttons and also able to press 'Esc' to get out of the menu,

### Environment

- Teardown Version v1.5
- Windows 10
- GPU: 1660Ti Mobile
- Graphics driver version: 31.0.15.2756
- CPU: i7 8750H

### Additional context

This affects many other modded UIs.

**Comment by dannyTuxedoLabs** [comment]
Hi! Can you please send us a video highlighting this issue. It'll be easier for us to troubleshoot it.

**Comment by polacos** [comment]
Hi, i have same problem. 
(link to the video)
https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/33966795/1d0142be-9d60-47e3-843f-4935bb089b3f

**Comment by dannyTuxedoLabs** [comment]
Thanks for sending us video footage of this issue.

**Comment by polacos** [comment]
I'm posting it again because I deleted the last message thinking the matter was closed.
https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/33966795/95ab5a97-ad24-4e89-ad65-106ebe002913

**Comment by YuLun-bili** [comment]
Should be fixed already.
@Thomasims please close this one :)
