### ISSUE TITLE
[Feature] Add options to remove head bob and tool sway to console versions

### ISSUE THREAD

**Issue by martygabel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#442]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I’m suffering from terrible motion sickness playing on PS5. I turned off motion blur, depth of field etc., but consoles are lacking the option to turn off head bobbing and tool sway like on PCs, and these would be great additions for PS5 and Xbox console players. 

### Describe the solution you'd like

Either in control/input settings or regular settings… a slider or toggle. 

### Describe alternatives you've considered

Tried turning off motion blur and depth of field but it’s definitely the bobbing that makes me and other players (this is widely reported) feel queasy. 

### Additional context

Thank you for your time and a wonderful game.

**Comment by Gregory-Gregory** [comment]
@martygabel hi,

Thank you for this suggestion! The team has looked into it and the mentioned Head Bob option will be released on the consoles in one of the upcoming patches.
