### ISSUE TITLE
[Bug] Flashlight/Lantern sound in Time Campers DLC

### ISSUE THREAD

**Issue by catgirlseraid** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#444]
### Describe the bug

When pressing the keybind to activate the lantern in the "Time Campers" dlc before picking up the lantern during the first mission, the sound of the lantern being lit still plays despite the player not having unlocked it (picked up the lantern) yet. Nothing happens visually as the player does not have the lantern yet.

### Steps to reproduce the behavior

1. Reset all progress in the Time Campers dlc.
2. Go to the first mission, and after entering the first mission, press the keybind to activate the lantern before picking the lantern up.
3. Observe sound of lantern being lit despite the player not having the lantern yet.

### Expected behavior

When pressing the key to activate the lantern, no sound should be produced as the lantern has not been picked up yet.

### Environment

- Teardown Version [1.5.1]
- OS: [Windows 11 22H2]

**Comment by YuLun-bili** [comment]
#429
