### ISSUE TITLE
[Bug] Game/Computer crashing on AMD Ryzen 3000 CPU coupled with RTX 2070 Super graphics card using driver version 466.47+

### ISSUE THREAD

**Issue by ColtonSpitdowski** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#45]
**Describe the bug**
It appears for myself and at least one other person that using graphics drivers past 466.27 on an RTX 2070 Super coupled with an AMD Ryzen 3000 series CPU causes either the game or the entire computer to crash.

**To Reproduce**
1. Attempt to launch the game on a computer with a Ryzen 3000 CPU and an RTX 2070 Super GPU. (GPU driver must be past version 466.27 as that version and ones before it seems to resolve the issue)

No other information regarding how the bug is able to be reproduced is known at the moment.

**Expected behavior**
Personally, the attempt to launch the game results in no display being detected on my monitor resulting in it turning off. In addition to this, my entire computer crashes and must be forcefully powered off. Another user experiences the game crashing and monitors turning off as well but only has their computer freeze for a minute and not fully crash.

**Screenshots**
No screenshots available as the computer crashes or freezes as a result.

**Environment**
 - Teardown Version 0.7.2
 - OS: Windows 10
 - GPU: RTX 2070 Super
 - Graphics driver version: 466.47 and onward
 - CPU: AMD Ryzen 3000 series (I have a Ryzen 7 3700X and the other user has a Ryzen 5 3600)

**Comment by CoolJWB** [comment]
I have an RTX 2070 (not super) with driver version 466.63 and a Ryzen 7 3800X, I haven't noticed this at all.
So while I can't confirm it I can narrow the search down by quite a bit.

**Comment by CoolJWB** [comment]
I have talked to players with a 2070 Super and CPUs alike but they have had no issues with the current driver versions, it could either have been 466.47 that was broken and no one I talked to ever tried that version, so if the issue still persists after a driver update then I would strongly believe it to be some other software-related issue.
If this is the case (that the issue persists) then please contact me on Discord so that we can take a closer look at this (CoolJWB#5847).

**Comment by CoolJWB** [comment]
Seems like this is still an issue as I've been contacted about it again on the latest driver version 466.77, if you have more info about this please go ahead and send it. A dxdiag savefile would be to some help pinpointing where the issue is at.

**Comment by MisterSirCode** [comment]
I have an RTX 2070 Super

This sounds like an NVidia Game Ready Driver issue.

I have the latest NVidia Studio Driver (Its ever so slightly faster in most cases) and I can play it fine.

**Comment by CoolJWB** [comment]
I'll revert this back to closed since I have not heard much about it recently.
