### ISSUE TITLE
[Bug] New UI Visual Issue Slow

### ISSUE THREAD

**Issue by Pufvv** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#451]
### Describe the bug

When you click the play button the options come up before the backround box. 
![Screenshot 2023-11-16 124810](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/75551375/d07bfd78-d63d-437c-9085-c779fb295fc8)
![Screenshot 2023-11-15 163720](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/75551375/18961fd7-b9a7-4c14-bb10-1044344c8e2d)

### Steps to reproduce the behavior

1. Open Teardown
2. Click on 'Play'
3. Look closely at the UI animation
4. See the  issue

### Expected behavior

I just want the new UI to work as good as the old UI if you guys are going to change it. I want the buttons to not go over the backround.

### Environment

- Teardown Version 1.5.1
- OS: Windows 11
- GPU: Nvidia 1660 Super
- Graphics driver version: 3.27.0.120
- CPU: 11th Gen Intel(R) Core(TM) i5-11400 2,60GHz

### Additional context

I love teardown. I dont want you guys to throw this game away.

**Comment by Please-Pick-a-Name** [comment]
this has been fixed
@Thomasims
