### ISSUE TITLE
Unable to alt tab out of the game

### ISSUE THREAD

**Issue by codypro134** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#452]
### Describe the bug

im trying to stream to my friends on discord, however the game stays on screen whenever i try to alt tab out.
![image_2023-11-16_170752233](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/116044596/c9506666-65d5-427c-b80b-65cbd7244a1b)
also the game freezes in this state

### Steps to reproduce the behavior

1. open teardown
2. try to alt tab
3. See error

### Expected behavior

the game should minimize, allowing me to interact with other programs

### Environment

-1.5.1
- Windows 11
- RTX 3060
- Nvidia 31.0.15.3640:
- Ryzen 5 5600G

**Comment by YuLun-bili** [comment]
game would force to stay foreground in full screen mode, can change to borderless windowed instead

**Comment by codypro134** [comment]
there is a way to get around this by win + tabbing and putting the game into desktop 2 then switching between the two

**Comment by YuLun-bili** [comment]
Already fixed in 1.5.3
