### ISSUE TITLE
[Bug] Grayscale Type JPEG Image Causing Crash

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#455]
### Describe the bug

the image in question: (yes this is supposed to be a place holder image)
![missing image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/9ff29e0f-c782-4303-8a21-594f36955a65)
the image should be a jpg
the code that crashes:
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/96c3d484-b249-429a-819c-ee4ae6347bd7)
i packaged everything in a zip for quick setup and test
[Global Mod.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13391571/Global.Mod.zip)

### Steps to reproduce the behavior

1. click the options button of this mod ingame
2. crash

### Expected behavior

no crash

### Environment

- Teardown Version: 1.5.1
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

please tell us why it crashed

**Comment by nooitaf** [comment]
It's grayscale, not rgb
```
Image:
  Filename: missing_image.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: PseudoClass
  Geometry: 3333x2989+0+0
  Units: Undefined
  Colorspace: Gray
  Type: Grayscale
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    gray: 8-bit
  Channel statistics:
    Pixels: 9962337
    Gray:
      min: 85  (0.333333)
      max: 255 (1)
      mean: 233.22 (0.91459)
      standard deviation: 25.0355 (0.0981784)
      kurtosis: 23.4687
      skewness: -5.04426
...
  Rendering intent: Undefined
  Gamma: 0.454545
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: JPEG
  Intensity: Undefined
  Compose: Over
  Page geometry: 3333x2989+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 99
  Orientation: Undefined
  Properties:
    date:create: 2023-11-17T14:02:09+00:00
    date:modify: 2023-11-17T10:56:32+00:00
    jpeg:colorspace: 1
    jpeg:sampling-factor: 1x1
    signature: d1b02c32fca3d73fe88b2c7977069df161cf1977c202eb478ad7c0557ca4cde9
  Artifacts:
    filename: missing_image.jpg
    verbose: true
  Tainted: False
  Filesize: 63616B
  Number pixels: 9.96234M
  Pixels per second: 206.456MB
  User time: 0.150u
  Elapsed time: 0:01.048
  Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
```

**Comment by YuLun-bili** [comment]
and it no longer crashes
<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/f2c6572a-5d31-4ef9-8ecf-fdf6e0f1c8bd" width="580px">
