### ISSUE TITLE
[Bug] Spawn menu and extra gui in maps (read)

### ISSUE THREAD

**Issue by TonyTeardown** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#456]
### Describe the bug

in the spawn menu, you cannot click on anything nor can you get out. Nothing is responsive other then the UI when you hover over. Same in extra gui maps.

### Steps to reproduce the behavior

1. Go into map
2. when you joined an map with extra gui you cant click anything
3. when theres not an extra gui go to menu
4. click spawn menu (same as extra gui map) your game freezes and you can hover over it and turns yellow but need to restart pc
5. after you restarted then its still the same and on experimental+normal newest version

### Expected behavior

what supposed to happen was, you go into map want to spawn somenthing and then it happends
what supposed to happen was,(extra gui) you go into map and it freezes

### Environment

- Teardown Version experimental& 1.5.1
- OS: Windows
- GPU:NVIDIA Geforce RTX 3070
- Graphics driver version: 31.0.15.3713
- CPU:Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

### Additional context

the video is tooo big

**Comment by TonyTeardown** [comment]
I EVEN REINSTALLED AND IT DOESNT WORK DUDE

**Comment by Please-Pick-a-Name** [comment]
i assume you mean: you cannot interact with any "additional" UI, they do not have any responses when clicking them.
do me a favor:
- Press windowskey-R
- Type dxdiag
- Hit enter
- Let the program finish (green progress bar in lower left)
- Click the "Save all information" button
- Upload the DxDiag.txt file here

**Comment by Please-Pick-a-Name** [comment]
@dannyTuxedoLabs, we now have a report of this issue but intel chips, what we gonna do with this information:sob:

**Comment by TonyTeardown** [comment]
and what if i dont?

**Comment by TonyTeardown** [comment]
i dont need to leak my system

**Comment by TonyTeardown** [comment]
+ i already called a dev and they said they are gonna be working on it

**Comment by Please-Pick-a-Name** [comment]
please close this issue @Thomasims

**Comment by TonyTeardown** [comment]
Just close it I fixed it myself it was a mod problem but Si already fuxed

Please-Pick-a-Name ***@***.***> schrieb am Mi., 20. Dez.
2023, 01:26:
