### ISSUE TITLE
[Bug] QueryRaycastWater is documented but doesn't actually exist

### ISSUE THREAD

**Issue by f1nniboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#457]
### Describe the bug

When I try to use `QueryRaycastWater(...)`, it fails with:
```
Attempt to call global 'QueryRaycastWater' (a nil value)
```

### Steps to reproduce the behavior

1. Create script
2. Call `QueryRaycastWater()`

### Expected behavior

`QueryRaycastWater()` should exist according to the API docs

### Environment

- Teardown Version: 1.5.1

**Comment by Please-Pick-a-Name** [comment]
this has been fixed @Thomasims
