### ISSUE TITLE
[Bug] Having many mods enabled blocks "Loading" text when loading world on 1280x720 resolution

### ISSUE THREAD

**Issue by Enderbyte09** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#458]
### Describe the bug

If I have many mods enabled (7+), the "mods enabled" box covers up the "Loading" text.

### Steps to reproduce the behavior

1. Set resolution to 1280x720
2. Install and enable 7 or more mods
3. Load any world
4. see bug

### Expected behavior

The box would remain under the loading text

### Environment

- Teardown Version 1.5
- OS: Manjaro Linux KDE Edition 23.0.7 (Running in Proton/Wine Environment)
- The bug also occurs on Windows 11
- And also on Kubuntu 23.10

### Additional context

A photo of the issue:
![Screenshot_20231118_154908](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/83879635/6dd70ae0-6668-4a8b-9b5a-363d10ed8d18)

**Comment by Gregory-Gregory** [comment]
Hi @Enderbyte09,

Thank you for this report! The team has fixed a similar issue in one of the latest updates. 

Please let us know if the reported issue is still relevant in the latest game version.

**Comment by Enderbyte09** [comment]
The issue is fixed
