### ISSUE TITLE
[Bug] Modding - Engine just quits code without any error messages!

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#46]
**Describe the bug**
Essentially, I have code which isnt working and i have identified what is happening, the problem is, there is no way to figure out WHY it is happening. But what is happening is part way through the code, the engine is just abandoning the function, without any error messages at all.

Obviously the code below may not be perfect, but the really awful part is the engine isnt giving any kind of error message at all. It is just quitting the code without giving an error message. I have had this happen multiple times recently, where from moving around a DebugPrint() I can find the exact line that it is stopping on, but theres also no reason why it should, and nothing to go on.

So i tried to make a copy of the effect of the leafblower effect. Pushes objects away from the player:

local function callFunctions() -- This is called from the main tick routine.
    QueryRequire("physical dynamic large")
    local bodies = QueryAabbBodies(min, max)
    for i = 1, #bodies do
        local body = bodies[i]
            if automode==1 and ((VecLength(VecSub(GetBodyTransform(body).pos,GetPlayerTransform().pos)))*0.5 < 10) and GetTime() > 4 then
                local maas = GetBodyMass(body)                        
                if maas < 2000000 then
				SetBodyDynamic(body, true)
				local forceStrength = 0.001
				local playerPos = GetPlayerTransform().pos
				local bodyTransform = GetBodyTransform(body)                    
				local directionFromPlayer = VecDir(playerPos, bodyTransform.pos)           
				DebugPrint("entered the loop")    -- DEBUG CHECKER - DOES NOT REACH THIS LINE
				local strengthAdjustedDirectionVector = VecScale(directionFromPlayer, forceStrength * maas)    
				ApplyBodyImpulse(body,bodyTransform.pos,strengthAdjustedDirectionVector)
			end
	end
end

**To Reproduce**

1 - In a new mod, add this function and call it.
2 - Run the mod and go to a level.
3 - the Debug print is not printed.
4 - IF  YOU MOVE THE DEBUG PRINT up a single line, it will print, but the ApplyBodyImpulse does not run. It is still abandoning the code on the line:

local directionFromPlayer = VecDir(playerPos, bodyTransform.pos)   

Without any error message.

**Expected behavior**
The code to either run and push objects away, or an error message as to what is wrong.

**Environment**
 - Teardown Version: 0.7.2
 - OS: Windows 64
 - GPU: RTX 3070
 - Graphics driver version: 457.51
 - CPU: Ryzen 3800x

**Additional context**
It sort of feels like the code or engine has had some errors not print any helpful text, like verbose mode may be turned off? Although this might make things nice for regular gamers, please put a way for modders to turn this back on and see error messages, such as the ones the code above must be generating.

**Comment by tuxedolabs** [comment]
Sounds weird. I guess the error comes from the undefined function VecDir which does not exist, but normally that generates an error printed on the screen. I tried calling VecDir and it did indeed give an error on screen. Please provide a complete repro case. The function you provded does not work in isolation. Also note that lua uses late binding, which means a lot of errors won't be seen until the code is reached for the first time during execution.
