### ISSUE TITLE
[Bug] Selecting elements in editor cause the scene explorer content to jump right, cause numerous inconveniences

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#461]
### Describe the bug

When selecting a element that is a bit deeper in the hierarchy tree, the scene explorer content will "scroll" to the right:
- visual bug within scene explorer with highlighted element
- unable to go back to the left side easily, thus
- unable to collapse elements

### Steps to reproduce the behavior

1. go to editor
2. create a hierarchy tree that have some depth
3. select any element that have some depth in the hierarchy tree
4. see scene explorere content jump right
5. pain

### Expected behavior

No randomly jumping left/right

### Environment

- Teardown Version: 1.5.1
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

this editor changes certainly isnt working, can we go back on this one?

**Comment by Please-Pick-a-Name** [comment]
update:
- the "jumping" also origins from the name in the scene explorer being too long either from for example: a opened prefab (which have long group name) or default [vox] name (contain both the path and object)
- the "jumping" does not occur when selecting long/deep entity within the scene explorer, it does occur when selecting them in the world

plz check this

**Comment by Gregory-Gregory** [comment]
Hi @Please-Pick-a-Name,

Can you please clarify if you still have this issue in the latest version of the game?

Thank you!

**Comment by Please-Pick-a-Name** [comment]
> Hi @Please-Pick-a-Name,
> 
> Can you please clarify if you still have this issue in the latest version of the game?
> 
> Thank you!

yes, as far as 1.5.3 goes

**Comment by Gregory-Gregory** [comment]
@Please-Pick-a-Name thank you for the clarification!

I have gathered and forwarded all the information to the QA team for investigation. 
If they need any additional details, I will let you know.

**Comment by Gregory-Gregory** [comment]
@Please-Pick-a-Name hi again,

This issue will be fixed in one of the upcoming patches.

**Comment by Please-Pick-a-Name** [comment]
"fixed" in 1.5.4 on experimental branch by introducing horizontal slider
