### ISSUE TITLE
[Bug] Vehicles can no longer exit the map boundaries when not driven

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#464]
### Describe the bug

As the title say, vehicles used to be able to cross map boundaries when not driven.

I can understand how this could be a feature and not a bug, but I have a use case of an vehicle driven by its own AI when no player is driving it and I would like to be able to cross the map boundary with it.

### Steps to reproduce the behavior

1. Enter a vehicle.
2. Drive to the map boundary
3. Notice the the vehicle is blocked when crossing it
4. Exit the vehicle
5. Push the vehicle (eg: using some thrusters)
6. Notice the the vehicle cannot cross the boundary even when not driven

### Expected behavior

Ideal fix would be:
- Add an option (some tag maybe) that let vehicles cross the boundaries.

An alternative that does not really solve the problem but could help mitigate it:
- Add a way to compute if a point is inside the map boundaries or not from script.

### Environment

- Teardown Version: 1.5.1
- OS: Windows
- GPU: NVIDIA GeForce RTX 3070 Ti
- Graphics driver version: 546.17
- CPU: AMD Ryzen 7 6800H with Radeon Graphics

**Comment by Thomasims** [comment]
This is already a feature, the vehicle bodies are assigned the `bounded` tag when driven. Removing that tag in update will let them leave the map bounds.

**Comment by FlorentP42** [comment]
I can confirm this works wonderfully, but did we confirm that the fact that this tag remains on the vehicle when you exit it is the intended behaviour and not an actual bug?
