### ISSUE TITLE
[Bug] Flavor Text Typo

### ISSUE THREAD

**Issue by D3364N** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#465]
### Describe the bug

In time campers, the flavor text on the globe has a typo (the globe in the lobby, not the missions)
donate is spelt as "donte"

### Steps to reproduce the behavior

1. Go to mines area in Time Campers lobby (having already collected the globe souvenir)
2. Look at the globe
3. See error

### Expected behavior

"donte" is supposed to say "donate"

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows/Linux]
- GPU:
- Graphics driver version:
- CPU:

**Comment by Gregory-Gregory** [comment]
Hi @D3364N,

Thank you for your bug report. This issue should be resolved in the latest patch.
