### ISSUE TITLE
[Bug] Quickload crash on Motivational reminder mission.

### ISSUE THREAD

**Issue by elilouve** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#466]
### Describe the bug

I did a quick save, then a quick load. Each time the game crashed, displaying an empty CMD console only. My mods don't seem to be the cause (some testing done) and I've already checked the integrity of the files.
For the moment, only this mission seems to be affected.

### Steps to reproduce the behavior

1- Launch the "Motivational reminder" mission
2- Make a quick save
3- Make a quick load
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/85528438/3cefd3f9-4d40-4462-beec-9d5d8dca280d)

### Expected behavior

That quickloading works

### Environment

- Teardown Version 1.5.1-
- OS: Windows
- GPU: EVGA rtx 2060
- Graphics driver version:546.17
- CPU:Ryzen 5 2600x

**Comment by dannyTuxedoLabs** [comment]
Hi there! Can you please specify which mods you have been using when this issue occurred. Does this issue occur if you have mods disabled when Quicksaving and Quickloading?

**Comment by elilouve** [comment]
> Hi there! Can you please specify which mods you have been using when this issue occurred. Does this issue occur if you have mods disabled when Quicksaving and Quickloading?

sure, there is this mods,
A lighter
Ability to read
AC130 Airstrike
ak-12 assault rifle
ak-47 assault rifle
asteroid strike
c4
Davy crockett launcher
fire storm
flood mod
gasoline flamethrower
grapple gun
hackerphone (optimized)
hungry slimes
keys_f8
lava bucket
megagun
physics gun
quilez laser
revengeance katana
shaky world
thermite canon
twin railgun
zenitka
nuclear strike
no clip

I tested it by deactivating the mods, but it still crashed. I redid the test and the game no longer crashed, I had certainly forgotten to deactivate a mod without paying attention. So obviously it's a mod that's causing the problem.
But it's specific to this mission, all the other missions worked fine

**Comment by dannyTuxedoLabs** [comment]
Thanks a lot for that information. That'll help a lot.

**Comment by Gregory-Gregory** [comment]
Hi @elilouve,

Can you please check the issue in that latest patch? Do you still crash when using the quick load?

**Comment by YuLun-bili** [comment]
closing as no updates from submitter for 6 months and likely to be problem with mods rather than base game.
