### ISSUE TITLE
[Bug] Unable to switch tools, alongside with speed decrease and visual vignetting

### ISSUE THREAD

**Issue by jimthiscity** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#467]
### Describe the bug

Video of bug occurring here: https://www.youtube.com/watch?v=f97vymvQZpI

Around :13 seconds in, when I place the third bomb, you can see my camera sort of zoom in, alongside some vignetting on the edges of the frame. When this occurs, I am no longer able to switch my tools. In addition, it feels like the speed of the character decreases (though I cannot say this for sure). Dying, loading a save, making explosions, etc, does nothing to resolve the issue. The only solution is to quit to main menu (and thus losing all progress).

### Steps to reproduce the behavior

Unfortunately unsure how to reproduce as it seems to occur at random. It has happened to me numerous times.

### Expected behavior

Tools are able to be switched.

### Environment

- Teardown Version 1.5.0
- PS5

**Comment by Please-Pick-a-Name** [comment]
i do not have a ps5 controller at home to tell you which button u need to press, but that is the "focus" effect on tools allowing more accurate shots to be made
aka press that button again and you are good

**Comment by glucero0** [comment]
Verified on Xbox series x. After multiple quick saves, could no longer switch tools or pick up items. Occurred at Lee's

**Comment by jimthiscity** [comment]
@glucero0  I was able to determine that this was zoom, triggered by clicking the left stick in. I rebound this function to the right stick instead so I would stop accidentally triggering it and haven't been having any issues.

Since this is a toggle on consoles instead of a hold like on MKB, I would say that the behavior of zoom persisting across deaths and resets feels like a potential bug, also the zoom doesn't work on some tools (Hammer specifically) making it feel very inconsistent, which is why I had so much trouble figuring out the issue. Thanks to Please-Pick-a-Name for pointing this out!

**Comment by glucero0** [comment]
Thank you for letting me know. I appreciate it.

Gary

**Comment by Please-Pick-a-Name** [comment]
@Thomasims we should close this, not an issue

**Comment by glucero0** [comment]
Vote to close
