### ISSUE TITLE
[Bug] Screen recorder completely crashes Teardown

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#471]
### Describe the bug

everytime i use the screen recorder the game crashes, there's a small delay before it crashes, sound is still audible but visuals are completely frozen, then an empty command prompt window appears and game closes

### Steps to reproduce the behavior

enable screen recorder, then in any level start the screen recorder

### Expected behavior

it not to crash

### Environment

- teardown 1.5.1
- OS: windows 11
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Graphics driver version: Geforce Game Ready 536.40
- CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

**Comment by Gregory-Gregory** [comment]
Hey @MexicanHulkHogan42069,

In one of the previous patches, the team has made changes that may have already fixed this issue.
Please check this issue again in the latest version of the game.

If the issue persists, please let us know.
