### ISSUE TITLE
[Bug] Being tabbed out while game launches then coming back completely freezes game and softlocks computer

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#472]
### Describe the bug

title self-explanatory

### Steps to reproduce the behavior

1. launch game
2. once game has launched and tuxedo labs logo sequence starts, tab out of game
3. tab back in
4. The incident

### Expected behavior

it not to freeze and softlock my pc

### Environment

- teardown 1.5.1
- OS: windows 11
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Graphics driver version: Geforce Game Ready 536.40
- CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

**Comment by TTFH** [comment]
This did happen once for me, not even Alt+Tab, Alt+F4 nor Ctrl+Alt+Delete did work to close the game.
What I did to avoid force restart my PC was to press Win+R and blindly type `taskkill \F \IM teardown.exe`
Additional info: it did happen on Windows 11, using DX12 with the game set to fullscreen mode.

**Comment by Gregory-Gregory** [comment]
Hi @MexicanHulkHogan42069 

Thank you for your bug report. If you are still experiencing this, please share additional details in this open issue #482.
