### ISSUE TITLE
[Bug] Tabbing out of the game doesn't work anymore

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#473]
### Describe the bug

i have to resort to using the windows key to switch to another program but then i have to click the game again for some reason for it to let me go on another window

### Steps to reproduce the behavior

1. go on either title screen, editor, or in-game
2. alt+tab
3. doesn't work
4. alt+esc
5. doesn't work
6. win key and clicking on random program
7. doesn't work
8. win key and clicking on random program, then clicking game again and then win key and clicking on random program
9. works

### Expected behavior

to be let out of the game instantly when using alt+esc or alt+tab

### Environment

- teardown 1.5.1
- OS: windows 11
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Graphics driver version: Geforce Game Ready 536.40
- CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

**Comment by Gregory-Gregory** [comment]
Hi @MexicanHulkHogan42069 

Thank you for your bug report. If you are still experiencing this, please share additional details in this open issue #482.
