### ISSUE TITLE
[Bug] InputLastPressedGamepadButton() returning empty string

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#475]
### Describe the bug

function tick()
	local name = InputLastPressedKey()
	if string.len(name) > 0 then
		DebugPrint(name) 
	end
end
--this doesnt return anything (with my ps4 controller)

### Steps to reproduce the behavior

1. not typing this

### Expected behavior

return anything other then empty string when i press whatever button on the controller

### Environment

- Teardown Version: 1.5.1
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by dannyTuxedoLabs** [comment]
Hi! Could you please clarify which function you're using - InputLastPressedGamepadButton() or InputLastPressedKey()?

**Comment by Please-Pick-a-Name** [comment]
> Hi! Could you please clarify which function you're using - InputLastPressedGamepadButton() or InputLastPressedKey()?

oh didnt notice the reply
as the title says, InputLastPressedGamepadButton()
i have my ps4 controller hooked up

**Comment by f1nniboy** [comment]
still happening in 1.5.3

**Comment by dannyTuxedoLabs** [comment]
> still happening in 1.5.3

Reported this issue to Saber QA again.

**Comment by dannyTuxedoLabs** [comment]
This issue will be fixed in one of the upcoming updates.

**Comment by Gregory-Gregory** [comment]
@Please-Pick-a-Name, we will close this issue for now. If you encounter a similar case in the next patch, please reopen it again.
