### ISSUE TITLE
[Feature] config file for ignoring certain file/folder when uploading mods

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#476]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Mors longa have 484 mb of actual***** content, while our .git folder weights 582 mb
an unspoken mod have 1.3gb of actual content, while the .git folder weights 1.04gb
my fella spent 15+ minutes to upload it :sob:

### Describe the solution you'd like

a way to have a file that tells the game to ignore certain files/folders while uploading mod

### Describe alternatives you've considered

move the files/folders out off the mod folder
pain

**Comment by nooitaf** [comment]
Alternative i'm doing for a long time:
- Make a folder in your repositiory which is the root of the mod
- Symlink that folder to your mods folder

Pros:
- proper file structure
- you can have as much other folders as you like (working files, pictures, docs, readme, betas, etc)
- publishing exactly what is needed (like a build folder in other projects)

Cons:
- none

**Comment by Gregory-Gregory** [comment]
@Please-Pick-a-Name hi!

Thank you for this suggestion. I have added it to the team's request list.

**Comment by UwQ-Official** [comment]
Also added?
