### ISSUE TITLE
[Bug] ctrl shift d would triggers ui debug mode, causing normal player to be confused on how the game changed color

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#479]
### Describe the bug

it appears that ctrl shift d would toggle the new saber:tm: UI's debug mode, which during normal gameplay it looks like the game bugged, and the fact it only debug more stuff with creative mode dont help player noticing its not an engine bug
this seems to only happen ingame

### Steps to reproduce the behavior

1. Go to any map
2. Hit ctrl shift d
3. see screen turn purple/yellow
4. (no ui shows debug element, except creative mode UIs)

### Expected behavior

maybe some sort of text display that shows the debug keybind while in debug mode

### Environment

- Teardown Version: 1.5.2
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by YuLun-bili** [comment]
I feel like that thing should be disabled totally

**Comment by Please-Pick-a-Name** [comment]
this has been fixed in 1.5.3
