### ISSUE TITLE
[Bug] Method SetDescription() consistently resets description of entity

### ISSUE THREAD

**Issue by atenfyr** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#48]
### Describe the bug

The Lua method SetDescription() does not properly set the description of entities to the string provided as the second parameter; instead, it "wipes" the description of the entity on which it is called, setting it to an empty string.

### Steps to reproduce the behavior

1. In a new content mod, create a body, assign it the tag "test", and set its "desc" field within the level editor to "old description."
2. Fetch the body using FindBody() and attempt to set the description of the body using SetDescription().
3. Call GetDescription() using the same body handle that was passed to SetDescription().
3. Observe that GetDescription() returns an empty string instead of the expected new description.

Here is some example code that illustrates this bug, with the first DebugPrint() statement correctly displaying the description set in the editor of a body with the "test" tag and the second DebugPrint() statement displaying an empty string. I have seen this issue occur when this code is ran in the init() method as well as the tick() method.
```lua
local x = FindBody("test", true)
DebugPrint("Old: " .. GetDescription(x))
SetDescription(x, "new description")
DebugPrint("New: " .. GetDescription(x))
```
![Sample debug output](https://user-images.githubusercontent.com/7481976/123500586-c055e500-d604-11eb-9d0a-e5a48e433a05.png)

### Expected behavior

I expect the SetDescription() method to override the entity's description with the string that is passed to the method instead of with an empty string.

### Environment

- Teardown Version: 0.7.2
- OS: Windows
- GPU: NVIDIA GeForce GTX 1660
- Graphics driver version: 461.37
- CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 CPUS) ~3.0GHz

### Additional context

The output of GetDescription() is corroborated by the text that appears when you hover over the body in question; after using SetDescription(), no text is displayed when hovering over the body whose handle was passed to the method.

**Comment by tuxedolabs** [comment]
Thanks for reporting, fixed in in 0.8!
