### ISSUE TITLE
[Bug] Photo mode zoom does not reset accumulation

### ISSUE THREAD

**Issue by ahs3n** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#481]
### Describe the bug

When scrolling the mouse wheel to zoom in photo mode without moving the camera, the raytraced accumulation does not reset. Instead it blends together new frames and previous frames.

### Steps to reproduce the behavior

1. Activate photo mode
2. Scroll the wheel **without** moving the camera

### Expected behavior

Raytracing accumulation should be reset, as it is when you rotate or move the camera. 

### Environment

- Teardown Version: Updated the day of this report
- OS: Windows
- GPU: RTX ADA 4000
- Graphics driver version: Newest driver as of 3 weeks before this report
- CPU: Intel i9 13th generation

**Comment by Please-Pick-a-Name** [comment]
this had been fixed @Thomasims
