### ISSUE TITLE
[Bug] Game freezes out of nowhere at random when tabbed out while in the editor

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#482]
### Describe the bug

when i tab out of the game and do other things the game will just, freeze, out of the blue

### Steps to reproduce the behavior

1. tab out of game
2. do other stuff
3. wait for teardown icon to flash red
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/94859623/b1ea2192-bb06-4faf-a222-0a2ba26925f6)
4. reopen teardown
5. doesn't open
6. reopen teardown
7. doesn't open
8. reopen teardown
9. doesn't open
10. reopen teardown
11. doesn't open
12. reopen teardown 
13. doesn't open
14. close teardown
15. doesn't close
16. close teardown
17. doesn't close
18. close teardown
19. doesn't close
20. clo

### Expected behavior

it to open like normal

### Environment

- teardown 1.5.2
- OS: windows 11
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Graphics driver version: Geforce Game Ready 536.40
- CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

**Comment by RoverBot-Dev** [comment]
if you arent already on borderless windowed mode, switch from fullscreen to borderless windowed in display settings ingame
thats what fixed itfor me

**Comment by Gregory-Gregory** [comment]
Hi @MexicanHulkHogan42069,

Could you please clarify if you still have the same issue in the latest patch?
Also, have you tried the previously mentioned workaround with the Borderless Window mode?

**Comment by Gregory-Gregory** [comment]
@MexicanHulkHogan42069, if you encounter this or a similar issue again, please be sure to let us know about it in this or a new discussion.
