### ISSUE TITLE
[Bug] Teardown doesn't open steam on startup

### ISSUE THREAD

**Issue by lukesplyne** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#483]
### Describe the bug

Sometimes when you open Teardown, it does not pre-launch steam. This affects mods as they don't load, also causing the "deleted DLC content" message to appear on the quicksave option if you used mods in the quicksave that are now unavailable. 

### Steps to reproduce the behavior

1. Open Teardown
2. It doesn't open Steam first, causing mods to not load
3. This also causes the "cannot load due to deleted DLC" message to appear on quicksave if you used mods that are now unavailable

### Expected behavior

Teardown opens Steam first, therefore loading mods.

### Environment

- Teardown Version 1.5.2
- OS: Windows 10
(the rest is unneeded)

**Comment by lukesplyne** [comment]
You can fix this by opening steam and then restarting Teardown

**Comment by Gregory-Gregory** [comment]
Hi @onethousandvolts,

Thank you for the information regarding this bug. If you encounter a similar case again, please reopen this issue.
