### ISSUE TITLE
Green outlines on snow, etc. seen through glass with Direct3D 12

### ISSUE THREAD

**Issue by MikeStirner** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#484]
### Describe the bug

As you see in the image, some things have a green outline when seen through glass.

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/114986084/9ec696b1-fe80-4930-b381-a9092f8c847e)

### Steps to reproduce the behavior

Have Direct3D 12 on, instead of OpenGL. Look at falling snow through a window.

### Expected behavior

No green.

### Environment

- Teardown Version: 1.5.2
- OS: Windows 10
- GPU: AMD Radeon RX 6800
- Graphics driver version: 22.40.37.17-230424a-391195C-AMD-Software-PRO-Edition (up to date as of today it says)
- CPU: AMD Ryzen 5 7600X 6-Core Processor
- Direct 3D API version: 12.1
- Direct3D® Driver Version: 9.14.10.01525

### Additional context

Fixed when switching back to OpenGL.

**Comment by nooitaf** [comment]
Teardown version?

**Comment by MikeStirner** [comment]
Here are my graphics settings: 
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/114986084/4ed49bfb-f34b-4971-ab7e-d48c47a0b748)

**Comment by MikeStirner** [comment]
> Teardown version?

1.5.2 sorry. I edited the post to reflect this.

**Comment by MikeStirner** [comment]
Still persists on version 1.5.3

**Comment by Gregory-Gregory** [comment]
Hi @MikeStirner, 

Can you please clarify if you are still having the same issue with the 
latest version of the AMD graphics and Direct3D drivers?

If the issue persists, please also share your DxDiag file:
1. In **Windows**, select **Start** and enter **dxdiag** into the search box on the taskbar. Select **dxdiag** from the results.
2. In the tool, select **Save All Information** for an easily shared format.

This will help the QA team a lot with their investigation.

Thank you!

**Comment by MikeStirner** [comment]
Actually I realized my graphics drivers weren't auto-updating. I updated manually and now the issue is fixed.

Sorry about the false alarm!
