### ISSUE TITLE
[Bug] Slider can be dragged as long as lmb is down

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#485]
### Describe the bug

Yes, from the title it seems like im saying something that is normal
no, what i meant is thats all it need
literally

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/81009804/ecfb903c-e112-428b-b224-3878999741c8

### Steps to reproduce the behavior

(faster to see then the vid procedures)
1. Go to options
2. Go to sounds
3. hold down lmb
4. drag it over the sliders

### Expected behavior

to uh know if the slider is getting "selected" by idk a press event

### Environment

- Teardown Version: 1.5.2
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by Gregory-Gregory** [comment]
Hi @Please-Pick-a-Name,

 Thank you for the information regarding this issue. The development team has looked into this issue and it should be fixed in one of the next patches.
