### ISSUE TITLE
Game Crashing When Launching One Specific Mission (Speed Deal)

### ISSUE THREAD

**Issue by Mattsib01** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#486]
### Describe the bug

I have launched teardown ,went onto the computer clicked speed deal, play and the game says loading and then 3 seconds later the game closes. i have tried with other missions, but nothing happens.

### Steps to reproduce the behavior

1. Go to computer
2. Click on missions
3. Click speed deal and then play
4. Game crashes during loading.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/b6a334c5-0c42-4c0d-ad07-1edecbe1d86f

(the black screen at the end is the game closing)

### Expected behavior

I expected to go to the computer, play speed deal, instead it crashes and sends me back to my home page.
![20231209155056_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/29dea670-dcde-440a-86a4-4fe6128bda39)
![20231209155100_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/d88ff2a4-ae1f-44ba-afcb-06329bb3a770)
![20231209155106_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/affeb987-7133-40cf-827b-4480a591cd0b)
![20231209155110_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/943c621f-5c60-4ac3-ba85-55c0885744d2)
![20231209155128_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/535b0b14-a199-428f-8e07-a614da2796c1) 
![20231209155130_1](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/133565840/e1830937-1bf2-4f9f-9046-6bcb8a7525c7)
**After this screenshot, the game crashes**

### Environment

- Teardown Version: 1.5.2
- OS: Windows 11
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Graphics driver version: 546.29
- CPU: INTEL Core i5-10400F @ 2.90GHz

### Additional context

**It only happens on speed deal.**

**Comment by Mattsib01** [comment]
EDIT: The screenshots of wet affair are just to say the bug only happens on speed deal

**Comment by dannyTuxedoLabs** [comment]
Hi there! Sorry to hear that you're having issues with Teardown. Could you please help us out and send us crash reports and some other data. Are you using OpenGL or DX12?

CRASH REPORTS
- \AppData\Local\CrashDumps
- \AppData\Local\Teardown\crash
- \Documents\Teardown\crash
- AppData\Local\Teardown - we need the log.txt file

DXDIAG
1. Press windowskey-R
2. Type dxdiag
3. Hit enter
4. Let the program finish (green progress bar in lower left)
5. Click the "Save all information" button

Thanks for helping us out. That'll help us troubleshoot this issue much faster.

**Comment by Mattsib01** [comment]
Hello, I hope you can fix my problem.
So, to answer your question, I am using DX12.

**The Crash Dumps**
[5108.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641054/5108.dmp)
[6456.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641056/6456.dmp)
[6576.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641057/6576.dmp)
[7324.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641059/7324.dmp)
[11204.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641060/11204.dmp)
[13800.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641061/13800.dmp)
[14672.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641062/14672.dmp)
[14912.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641063/14912.dmp)
[15820.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641064/15820.dmp)
[19256.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641065/19256.dmp)

**The Other Crashes**
[callstack.txt](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641123/callstack.txt)
[minidump.dmp](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641128/minidump.dmp)

**Can't seem to find the next one, sorry.**

**Log.txt**
[log.txt](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641142/log.txt)

**I don't know if I need to send this, so I am going to do it anyways.**
[DxDiag.txt](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/13641164/DxDiag.txt)

**Hope this helped you solve the problem. :)**

**Comment by Mattsib01** [comment]
UPDATE: I loaded into speed deal and its now working fine, don't know why, sorry for bothering you.

**Comment by dannyTuxedoLabs** [comment]
Thanks a lot for the answer. We see that the size of minidump.dmp is 0. Is this the actual size or was this file corrupted when uploaded to Github?
