### ISSUE TITLE
DebugPrint and DebugWatch not working properly on Table, Vec, Transform, Quat etc

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#49]
### Describe the bug

DebugPrint : 
Cant print Table, Vec, Transform, Quat
DebugWatch : 
Cant display or display properly
Table: DebugWatch("Value", {String, Int, Float, Vec: Type that dont display properly})  Display a transform
 DebugWatch("Value", {0.0, 0.0, 11.0})  Display {0.0, 0.0, 11.0}--Think it a vec cause if i remplace the 3 value in the table by string or else it will display three number which string become 0.0
DebugWatch("Value", {1, 1, 1, 1, 1, 1}) --Think it a transform
DebugWatch("Value", QuatEuler(1,1,1))--Think it an Quateurion(add a value at the end)

### Steps to reproduce the behavior

Is in the bug description

### Expected behavior

(Bad explanation) DebugWatch a table with the correct value DebugWatch a Euler and not a quaternion Print a Vec Table etc

### Environment

- Teardown Version : 0.7.2
- OS: Window
- GPU: Radeon RX 570 Series
- Graphics driver version: 26.20.15017.1005
- CPU: Core i-5 3570
The computer composant wont change anything but i put them anyway

### Additional context

Editor Problem

**Comment by tuxedolabs** [comment]
Both function are mostly intended to be used with strings. Other types supported for convenience, but there is no support for general tables.
