### ISSUE TITLE
[Bug/Documentation?] function UiText() not behaving as documented

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#492]
### Describe the bug

As described in [Teardown scripting API](https://teardowngame.com/modding/api.html#UiText), function `UiText()` should return 4 values if second parameter is not given/set to false. However this function only returns 2 values, regardless of what value is given as second parameter.

### Steps to reproduce the behavior

1. call `UiText()` in a reasonable approach with second param not given/set to false, watch returned value.

### Expected behavior

return 3rd and 4th value

### Environment

- Game 1.5.2(patch 2)
- OS: Windows 11

### Additional context

I don't believe these got removed intentionally. But if they were, I'd express an extremely strong feeling against this.

**Comment by lelanceflamer** [comment]
Yeah, the devs saw this but they didn't do anything and I don't think they updated the documentations since they removed those 2 return values, it completely broke one of my mods' settings UI, which really sucks because it was a total pain to design.

Hope the devs will actually understand this

**Comment by Gregory-Gregory** [comment]
Hi @YuLun-bili,
 
Thank you for the information about this bug issue. We have forwarded it to the QA team for further investigation.
If more details are needed, we will get back to you.
