### ISSUE TITLE
[Bug] Command("game.screenshot") not working properly

### ISSUE THREAD

**Issue by Prankejten** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#497]
### Describe the bug

In older versions when you run _Command("game.screenshot")_ in a script, it took a screenshot immediately. However a few days ago I noticed that now when you trigger it, it takes the screenshot the next time you open Photo Mode. I assume this is a bug, as this command has worked for a long time before.

I did some additional testing by creating a content mod and a script which runs _Command("game.screenshot")_ at game start, and again, the screenshot was only taken when I opened Photo Mode after running the command, confirming that it is not an issue related to the other parts of the camera mod I was using for the demonstration.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/71499525/a5bcab0f-8bb9-471f-86ee-1471b70ee65e <-- showcase of the issue

### Steps to reproduce the behavior

1. Go into any teardown level
2. Run _Command("game.screenshot")_ one way or another
3. No screenshot should be taken
4. Open Photo Mode
5. A screenshot should be taken and photo mode should open right after

### Expected behavior

When the command is run, the game takes a screenshot like how it does when you take one in Photo Mode.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/71499525/f688819b-5ba5-412e-a690-db6ea98b1f91 <-- this is a video from december 2022 _(This bug only appeared recently, however this is what I was able to find in under 10 seconds, so I just went with this)_ showcasing what's supposed to happen _(The username on the "Saved to ..." screen is different because I recently had to reinstall Windows)_

### Environment

- Teardown Version 1.5.3, the latest version as of right now
- Windows 10 22H2
- GPU: NVIDIA GeForce GTX 750 Ti
- CPU: Intel Core i7-2700K

### Additional context

- I assume this issue was caused by the recent GUI overhaul (though this is only a guess)
- The camera worked up until at least the end of october 2023, as that's when I last used the mod

I hope this will soon get fixed, as I like taking photos of random things I find while playing maps

**Comment by Gregory-Gregory** [comment]
Hi @Prankejten,
 
Thank you for the information regarding this issue. We have forwarded it to the QA team for further investigation.
If more details are needed, we will get back to you.

**Comment by Gregory-Gregory** [comment]
@Prankejten, @YuLun-bili 
 
The development team has looked into this issue and it should be fixed in one of the next patches.
