### ISSUE TITLE
[Bug] Wheel with negative drive acts weird

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#498]
### Describe the bug

Vehicle wheels with drive set to -1 cause really weird behaviour:
the vehicle will roll backward by itself when you are in the vehicle, without any throttle
the vehicle will correctly go backward faster when holding down the "up" key
the vehicle will not go forward when holding down the "down" key

### Steps to reproduce the behavior

1. Make vehicle with all wheels drive set to -1
2. load ingame, gets in the vehicle
3. see vehicle roll backward on itself
4. see vehicle not go forward when holding the down key

### Expected behavior

vehicle does not roll backward by itself
vehicle goes forward when holding the "down" key

### Environment

- Teardown Version 1.5.3
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

the issue is probably there since ages ago, but it wasnt relevant as no one would want to set wheel drive to negative anyways
untill now it is possible to set entity property including wheels, which makes once want to do something called tank steering
please bless us

**Comment by Gregory-Gregory** [comment]
Hi @Please-Pick-a-Name,

Thank you for your bug report. The development team has looked into this issue and it should be fixed in one of the next patches.
