### ISSUE TITLE
[Bug] Deleting an instance with 'Delete but keep children' accidentally would break

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#50]
### Describe the bug

I was editing an instance moments ago and I mistakenly delete it by 'Delete but keep children' then editor breaks.

### Steps to reproduce the behavior

1. Open editor
2. Find an instance
3. Delete it with 'Delete but keep children' operation
4. Editor breaks (maybe not instantly but within 10 seconds)

### Expected behavior

Disable this operation on instance is the best behaviour

### Environment

Teardown V0.7.4

 CPU:
 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
 Hardware threads: 8
 Physical memory: 8037 Mb
 Display resolution: 1536x864
 Executable path: D:\SteamLibrary\steamapps\common\Teardown\teardown.exe
 Appdata dir: C:\Users\Anson\AppData\Local
 Documents dir: D:\User Files\Anson\Documents

 GPU:
 OpenGL vendor: NVIDIA Corporation
 OpenGL renderer: NVIDIA GeForce MX250/PCIe/SSE2
 OpenGL version: 3.3.0 NVIDIA 471.11
 Total VRAM: 2048 Mb
 Available VRAM: 1957 Mb

**Comment by tuxedolabs** [comment]
Ouch, I missed that on the shortcut. Thanks, this is fixed in 0.8!
