### ISSUE TITLE
[Bug] unable to hide cursor for interactive screen even with UiSetCursorState(2)

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#502]
### Describe the bug

screens with interactive enabled will draw a cursor, i dont want a cursor cause im doing a directional navigation
and UiSetCursorState(2) does not hide the cursor, despite implied it can by the terminal.lua found in the game file

### Steps to reproduce the behavior

1. Go to editor
2. Make screen that is interactive
3. Call UiSetCursorState(2) in draw of screen script
4. See cursor

### Expected behavior

no cursor

### Environment

- Teardown Version: 1.5.3
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by KevysNotHeavy** [comment]
Same...

**Comment by KevysNotHeavy** [comment]
I feel like this should have an option to enable controller support too possibly

**Comment by Gregory-Gregory** [comment]
Hi @Please-Pick-a-Name, 

Thank you for the information on this issue. The development team has looked into this and it should be fixed in one of the next patches.
