### ISSUE TITLE
[Bug] Integer overflow in registry

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#504]
### Describe the bug

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/c3c7d7b6-bbd5-42bc-a3da-601c5c337b90)

### Steps to reproduce the behavior

1. keep playing and demolishing
2. check value of `savegame.stats.brokenvoxels`

### Expected behavior

Maybe use a secondary node to record how many times player have reached upper limit so it won't overflow to negative.

### Environment

- Teardown Version 1.5.3

**Comment by Gregory-Gregory** [comment]
Hi @YuLun-bili, 

Thank you for your bug report. The development team has looked into this issue and it should be fixed in one of the next patches.
