### ISSUE TITLE
[Bug] GetShapeSize() returns 4th value with floating point inaccuracy when shouldn't

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#506]
### Describe the bug

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/9037b3aa-18da-4d7c-8c6a-8137c570389c)

### Steps to reproduce the behavior

call that function such that handle passed in is a valid not scaled shape in scene, watch returned values

### Expected behavior

According to [Teardown Scripting API](https://[teardowngame.com/modding/api.html#GetShapeSize](https://teardowngame.com/modding/api.html#GetShapeSize)):
> The size of one voxel in meters (with default scale it is 0.1)

Therefore it should return 0.1 which makes most sense

### Environment

- Teardown Version 1.5.3
- OS: Win 11

**Comment by Gregory-Gregory** [comment]
Hello @YuLun-bili, 

Thank you for the information regarding this issue. We have forwarded it to the QA team for further investigation.
If more details are needed, we will get back to you.

**Comment by Gregory-Gregory** [comment]
Hi @YuLun-bili,

The QA team has reviewed this issue and mentioned that it is a correct representation of 0.1 in the 32-bit float IEEE754 used by the engine, even though Lua uses double precision for numbers.
