### ISSUE TITLE
[Bug] Two Yellow Quilez R0113R in Spawn Menu on 1.5.2

### ISSUE THREAD

**Issue by DoctorNutmeg** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#508]
### Describe the bug

Two Yellow Quilez R0113R show up in the spawn menu despite being on 1.5.2 and the patch notes for that update show this issue as being fixed

### Steps to reproduce the behavior

Go to spawn menu for Quilez R0113R, last two in the list are both labeled yellow

### Expected behavior

One should be labeled purple I think

### Environment

Xbox Series S

Version 1.5.2

**Comment by Gregory-Gregory** [comment]
Hi @DoctorNutmeg,

Thank you for your bug report. The patch that fixes this issue will be shipped in one of the future updates.
