### ISSUE TITLE
[Feature] A debug/crash log.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#51]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

YES - I have made a mod, and it is randomly crashing the game to desktop. I dont know why. Without some log of what error occurred, I havent got a single chance of fixing it.

My suggestion is therefore that the game write some output to a log file (a bit like the teardown / log.txt) except this one logs a lot more stuff like errors in the game or small problems, so that when a crash to desktop happens, I or anyone else who may find themselves in this situation can dig themselves out of it.

### Describe the solution you'd like

A log file of any and all errors, or minor issues during the game, including as much detail as possible when a crash to desktop happens.

### Describe alternatives you've considered

Erm, dunno what else to say, its a debug log innit?

**Comment by tuxedolabs** [comment]
There is actually a log.txt in %LOCALAPPDATA% , but it's probably not granular enough. Writing a detailed log file every frame would be very problematic for a number of reasons and will likely not happen.
