### ISSUE TITLE
[Bug] Sub-Instances Selectable in Instances

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#510]
### Describe the bug

When in the editor, if you have an instance inside of another instance, if you click on a part of the sub-instance in the view window, the sub-instance will be selected instead of the correct instance. This sub-instance can be moved and rotated using the gizmos, but will not correctly update the level xml (as it doesn't move the correct instance)

### Steps to reproduce the behavior

1. Enter the editor
2. Create the following structure in the scene explorer:
```
> Group 1
    > Group 2
        Voxbox
```
3. Convert Group 2 to an instance, convert Group 1 to an instance
4. Try to select the Group 1 instance in the view window, see Group 2 instance is selected instead

### Expected behavior

Group 1 should have been selected instead. Nothing inside of an instance should ever be selected.

### Environment

- Teardown Version 1.5.3
- OS: Windows

### Additional context

Haven't tested this with even more levels of instances.

**Comment by nooitaf** [comment]
Duplicate of #247

**Comment by bingleboy** [comment]
Missed that, apologies.
