### ISSUE TITLE
[Bug] creative mode

### ISSUE THREAD

**Issue by monke12121** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#513]
### Describe the bug

So in console most of the stuff dosent work like paint or pick materials for some reason. Im on xbx series x

### Steps to reproduce the behavior

1. Go to 'menu'
2. Click on 'turn on creative'
3. Scroll down to 'pick material or paint'
4. Try to get the material or paint the material
5. See error

### Expected behavior

paint the thing ur looking at with selected material or take the material from the material u are looking at

### Environment

- Teardown Version 
-xbox series x

**Comment by Gregory-Gregory** [comment]
Hi @monke12121,

Thank you for this bug report!

Can you please clarify what exactly happens when you try to get the material or paint?
Do you get any error messages or do they just not work?

If you could share some screenshots or a video, it would help the team investigate.

**Comment by YuLun-bili** [comment]
I think the user is expecting to pick a colour/material from the shape currently being painted over, which is impossible as game use an independent predefined palette with no option to adjust either colour or material.

And submitter is not responsive anyway... so closing

If the submitter still wants to customize/pick colour and material from another shape then I'd suggest opening a feature request instead.
