### ISSUE TITLE
[Bug?] Able to unlock "Above and Beyond" achievement with creative mode

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#515]
### Describe the bug

since one can fly with creative mode and it moves player rather than camera, flying up to 100m can grant the achievement which is not very difficult.

But as building a nitroglycerin tower also grant this achievement (also quite easy), I'm not sure if worth to patch. Not to mention those with mods.

### Steps to reproduce the behavior

just use creative mode to fly up until achievement unlocked

### Expected behavior

doesn't unlock the achievement maybe?

### Environment

- Teardown Version 1.5.3

**Comment by Gregory-Gregory** [comment]
Hi @YuLun-bili,

I have forwarded this information to the team. If they find it to be a bug, I will let you know.

Thank you!

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi again,

The team has checked this and mentioned that it is not a bug.
