### ISSUE TITLE
[Bug] Draggable Profiler UI Dividers

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#517]
### Describe the bug

3 dividers in the profiler can be dragged using your mouse while the game is paused. While being dragged, the content around the divider is incorrectly cropped and the divider snaps back to it's original location once released. This seems like very unintended behavior.

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/85895661/5d2bbde4-7850-4443-b417-9317b150cafc

### Steps to reproduce the behavior

1. Enter any level
2. Open the profiler (`shift` + `alt` + `f3`)
3. Pause to bring up the mouse cursor
4. Attempt to drag any of the dividers in the "Stat" section or the "Engine" section
5. See error

### Expected behavior

These dividers should either not be grabbable or should work correctly when dragged.

### Environment

- Teardown Version 1.5.3

**Comment by Gregory-Gregory** [comment]
Hi @bingleboy!

Thank you for this report. I have forwarded it to the QA team. 
If any additional details are needed, I'll let you know.

**Comment by Gregory-Gregory** [comment]
@bingleboy hi again!

The team has looked into this issue, and it will be fixed in one of the future updates.

**Comment by Please-Pick-a-Name** [comment]
fixed in 1.5.4 on experimental branch, hope it stay till public branch
