### ISSUE TITLE
[Bug] Voxscript tagging only works for last Vox() created inside of it

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#52]
### Describe the bug

Build-in Tags like `explosive` or other tags attached to the Voxscript object only apply to the last created `Vox()` inside the voxscript.

![Screenshot from 2021-07-13 01-45-54](https://user-images.githubusercontent.com/1898194/125369533-b8c06b00-e37c-11eb-8bf0-114e9b6d4b53.png)

### Steps to reproduce the behavior

1. Make a voxscript which creates more then one `Vox()` inside
2. Tag the Voxscript Element in the editor (example: "explosive=4")
3. Run the map
4. See only last shape explode
5. Return to editor
3. Put voxscript element in a script element
4. Do `FindShapes(nil)` in script's init()
5. Gets only one (the last) `Vox()` created

### Expected behavior

Tags should be attached to every `Vox()` created inside the voxscript. 

### Environment

TD 0.7.4

**Comment by tuxedolabs** [comment]
This should be fixed in 0.8. It also affects tags on vox shapes, where the vox files include multiple objects. Before 0.8 any tag was only applied to the first object in vox file. No should be applied to all.
