### ISSUE TITLE
[Feature] Unlisted Publishing 

### ISSUE THREAD

**Issue by KevysNotHeavy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#520]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Publishing Unlisted in game avoids having to manually change it with each mod update and makes it less tedious

### Describe the solution you'd like

Add an Unlisted Publish method to the in game publisher

### Describe alternatives you've considered

Having to manually change to unlisted after publishing as private

**Comment by Gregory-Gregory** [comment]
Hi @KevysNotHeavy,

I have shared this request with the development team. Thank you very much!

**Comment by YuLun-bili** [comment]
it's already a feature, click on the button to change visibility until find the unlisted option
