### ISSUE TITLE
[Bug] Game display issue when Task Manager set to "Always on Top" while running the game in "Fullscreen" A.K.A. Exclusive Fullscreen

### ISSUE THREAD

**Issue by ProjectHSI** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#524]
### Describe the bug

Task manager can be set to be always on top of other applications, so you can always see task manager. This appears to cause problems with Teardown's fullscreen, as it will display the last full screen state, and then disappear (but not crash).

### Steps to reproduce the behavior

1. Open task manager.
2. Under "Options" just below the title of the application, check "Always on top".
3. Open Teardown.
4. Optional: Focus Teardown again.

### Expected behavior

The game gains focus and displays the game.

### Environment

- Teardown Version: 1.5.3
- OS: Windows
- GPU: NVIDIA GTX 1080 Ti
- Graphics driver version: 31.0.5.4601 (gathered via Device Manager)
- CPU: Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz.

### Additional context

The CPU has turbo enabled, which does not appear to be it's stock configuration on my machine.
This issue only happens when the always-on-top window is on the window.
This issue also happens when the always-on-top windows is on the window yet on a seperate monitor (more visible if the montiors don't have the same DPI).

**Comment by YuLun-bili** [comment]
Reproduced. Display setting need to be "fullscreen" and both window drawing in same screen (fully or partially).

For me it seems like game and task manager are fighting for display order rather than freeze window to last frame shown.

**Comment by Gregory-Gregory** [comment]
Hi @ProjectHSI, @YuLun-bili,

Thank you for this bug report. I shared the information with the QA team.
If they need any additional details, I will let you know.

**Comment by ProjectHSI** [comment]
> YuLun-bili changed the title ~~[Bug] Teardown doesn't focus correctly in fullscreen with-an-always on top window present~~ [Bug] Game display issue when Task Manager set to "Always on Top"

Name change is accurate. System Informer does not cause this effect. It does hide System Informer though.

**Comment by ProjectHSI** [comment]
Clarified the name a little.

**Comment by Gregory-Gregory** [comment]
@ProjectHSI thank you for this clarification. I have updated the report for the team.

**Comment by YuLun-bili** [comment]
Update: in latest experimental build (updated on Mar 25th), if task manager and game are in same monitor, moving mouse into that monitor area would hide/minimize game rather than freeze last frame drawn

**Comment by YuLun-bili** [comment]
resolved in 1.6.0 with task manager on top of game window in this case
