### ISSUE TITLE
[Bug] built-in slow-motion mod does not slow down time if built-in screen recorder is active

### ISSUE THREAD

**Issue by TeardownDestructionClips** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#525]
### Describe the bug

Using the built-in slow-motion mod works as intended and slows down time as well as applying a slow motion effect to all sounds, however when recording with the built-in screen recorder mod the built-in slow-motion mod will not slow down time at all, it will remain at regular speed but will still apply the slow motion effect to sounds.

### Steps to reproduce the behavior

1. Enable the "slow-motion" and "screen recorder" mods in the built-in mods section
2. Start recording with the screen recorder mod in game
3. hold down "T" to active slow motion and realize it isn't actually slow motion.

### Expected behavior

the built-in slow-motion mod should work the same as it normally does even when the built-in screen recorder mod is recording, it should slow down time and apply the slow motion effect to all sounds.

### Environment

- Teardown Version 1.5.3
- OS: Windows 11
- GPU: RTX 4090
- Graphics driver version: 31.0.15.5152
- CPU: Intel i9-13900k

**Comment by Gregory-Gregory** [comment]
@TeardownDestructionClips hi,

Thank you a lot for the clear description of the bug.
I have reported it to the QA team. If they need any additional details, I will let you know.

**Comment by Gregory-Gregory** [comment]
@TeardownDestructionClips Hi again :)

This issue was already fixed by the team earlier. This fix will be shipped in one of the upcoming patches.
