### ISSUE TITLE
[Bug] Missing assets in experimental built-in maps

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#526]
### Describe the bug

Some of the new built-in maps in the latest experimental release have missing assets inside of them.

- Hollow Rock: (MOD/assets/brush/log/)
![hollow-rock](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/52052170/f55b1fd8-4b40-40da-a865-b3263cb8594c)

### Steps to reproduce the behavior

1. Go on the latest experimental version
2. Open the mod manager
3. Create a local copy of the Hollow Rock built-in mod
4. Open local copy that was just created
5. Press Ctrl + R (reload vox)

### Expected behavior

All the assets used inside of the map should be valid and exist.

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: Windows
- GPU: Radeon RX 6600
- Graphics driver version: Unknown
- CPU: Ryzen 5 5600X

**Comment by YuLun-bili** [comment]
> Create a local copy of the Hollow Rock built-in mod

It's not?

**Comment by Gregory-Gregory** [comment]
@Xless-Qu-dev hi,

Thanks for reporting the issue. 

I've compiled everything you've provided and sent it over to our QA team for review. In case they need more specifics, I'll get in touch with you for further clarification.

**Comment by Gregory-Gregory** [comment]
@Xless-Qu-dev,

The team has looked into this issue, and it should be fixed by the 1.5.4 release as well.
