### ISSUE TITLE
[Bug] [Experimental] `UiTextInput()` always return second parameter as `false`

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#528]
### Describe the bug

As described in title

### Steps to reproduce the behavior

Call (undocumented) function `UiTextInput()` with valid parameters, watch return values

### Expected behavior

Second parameter return `false` only when input box is not in focus, otherwise `true` (same as pre 1.5.4 version)

### Environment

- Teardown Version 1.5.4
- OS: Windows 11

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi,

Thank you for this report. 

I have forwarded this information to the QA team. If they need any additional details, I will let you know.

**Comment by Gregory-Gregory** [comment]
@YuLun-bili,

The team has looked into this issue, and it should be fixed by the 1.5.4 release.

**Comment by YuLun-bili** [comment]
uhhh it's not.

This time it returns `false` as long as user is not inputting, which is different from pre 1.5.4 version either. In pre 1.5.4 (such as 1.5.3), it always returns `true` regardless of user input. As long as the box is in focus it remains `true`.

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/33c9a9e6-50c0-48e1-85db-9b97b6d49bc1)

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/3b929a29-4495-4df4-8123-24febdf511bd

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi!

Thank you for the additional information. I shared it with the team again.
