### ISSUE TITLE
[Question] Removal of node value `game.path`

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#529]
Since version 1.5.0, node `game.path` no longer have game's absolute path as node value. I wonder is this intended or accidental?

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi!

I have asked the team about this and will let you know if I get a response.

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi again,

Here is the answer that the team shared:

> This is intentional. This was done to avoid resource overload in mods. There are also technical reasons related to consoles.
