### ISSUE TITLE
[Bug] Editor tag view shows tags behind camera

### ISSUE THREAD

**Issue by Xless-Qu-dev** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#530]
### Describe the bug

The editor tag view displays tags on the screen even tho they are behind the camera (not visible).
![tag-view](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/52052170/25e38752-3b75-4df8-8de9-726b9808ada2)

### Steps to reproduce the behavior

1. Open any map in the editor
2. Enable the Tag View
3. Move around the camera

### Expected behavior

Tags that are behind the camera shouldn't render.

### Environment

- Teardown Version: Latest Experimental version
- OS: Windows
- GPU: Radeon RX 6600
- Graphics driver version: Unknown
- CPU: Ryzen 5 5600X

**Comment by Gregory-Gregory** [comment]
@Xless-Qu-dev hi, again­

Thank you for detailing this issue. 

I've informed the QA team about this issue. We'll reach out if we require any more details to proceed with the investigation.

**Comment by Gregory-Gregory** [comment]
@Xless-Qu-dev,

The team has looked into this issue, and it should be fixed by the 1.5.4 release.
