### ISSUE TITLE
[Bug?] Calling `DebugPrint()` in main menu scripts outputs nothing on screen

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#531]
### Describe the bug

as described in title

### Steps to reproduce the behavior

call `DebugPrint()` in main menu scripts and watch screen outputs

### Expected behavior

`DebugPrint()` messages got printed if not intended to behave like this I guess? (same as pre 1.5.4 versions)

### Environment

- Teardown Version 1.5.4
- OS: windows 11

### Additional context

Combined with #527 it made life of those changing some main menu scripts (such as me) much harder :(

On the other hand, I'm not sure why `DebugWatch()` still behaves normally if removal of `DebugPrint()` output in main menu is intended.

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi,

Thank you for this bug report.

I have forwarded it to the QA team. If they need any additional details, I will let you know.

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi again,

I have received a response from the team regarding this issue:

> Currently, only errors from local mods are displayed on the screen. If you need to see errors from the game script, you can view them in the logger window.

**Comment by YuLun-bili** [comment]
@Gregory-Gregory  Then should `DebugWatch()` output hidden or not? They currently still shows when called in game scripts

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi!

Regarding your last question, the team replied: 

> The `DebugWatch` doesn't print errors, so we don't hide them.
