### ISSUE TITLE
[Bug] [Experimental] Content Explorer Preview render inconsistent

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#534]
### Describe the bug

Content Explorer Preview render seems to do different things depending on position and if the Scene explorer is open.
 
https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/1bc63507-1569-4d12-8408-5b65bff2ffa5

### Environment

- Teardown Version 1.5.4 (Experimental)
- OS: Linux
- GPU: 3080
- OpenGL
- Windowed 720p

**Comment by Gregory-Gregory** [comment]
@nooitaf hi!

Thank you for this report.

The information has been forwarded to the QA team. If they need any additional details, I will let you know.
