### ISSUE TITLE
[Bug] Some input hints not updating upon keybind changes

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#536]
### Describe the bug

Following hints are not updated after keybind changed
* vehicle move forward/backward
* exit vehicle

**There might be more, these are what I noticed**

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/98fb9418-7e51-4fb7-9197-667dd6faa049

### Steps to reproduce the behavior

clearly demonstrated in attached video

### Expected behavior

keybind got updated

### Environment

- Teardown Version 1.5.4 (experimental)
- OS: windows 11

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi,

Thank you for mentioning this issue. It has been shared with the QA team.

**Comment by YuLun-bili** [comment]
Other keybinds updates but handbrake remains as `space`, I guess this is intended? Could tag as resolved if that's the case.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
