### ISSUE TITLE
[Bug] vox with "prop" set to true not included in FindBodies()

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#537]
### Describe the bug

When calling `FindBodies(nil)`, vox models with "prop" set to true are not included. This seems like unintended behavior as this breaks the expected tree like structure (if the body is a parent of a shape, and the shape is a child of a script, the body *must* be a child of the script, right?)

### Steps to reproduce the behavior

1. Create a script with two shapes underneath it.
2. Set the `prop` property of the first shape to true.
3. Put the second shape in a body with `dynamic` set to true.
4. Call `FindBodies(nil)` in the script, then print the length of the list
5. See error

OR, just use this test scene I set up:
[FindBody Test.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/14593256/FindBody.Test.zip)

### Expected behavior

All bodies underneath the script should be returned, regardless of if they are declared in the editor or if they are created from a shape set to true. Logically, these bodies must be children or nested children of the script.

### Environment

- Teardown Version 1.5.4 (experimental)
- OS: Windows

**Comment by Please-Pick-a-Name** [comment]
id say its the same edge case behavior with [shape] in a [vehicle] thats set to prop true

**Comment by Gregory-Gregory** [comment]
@bingleboy hi,

Thank you for this report. The information has been shared with the QA team.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/0826b186-7c12-4bf6-a568-960e553fdada" width="300px">
