### ISSUE TITLE
[Bug] Game crashes when rerunning/restarting level multiple times because of a script I made with nothing in it that could cause crash

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#538]
### Describe the bug

a script i wrote for my mod causes teardown to crash after 2/3 level re-runs
i gave the mod to someone else to reproduce my problem and for some reason their game doesn't crash at all

### Steps to reproduce the behavior

i'd rather give the actual mod/script in dms (discord username: cioss) but i'll give the steps here
- go on editor
- open xml with the script that crashes
- run level
- return to editor
- rerun level
- repeat until game crashes during loading (or alternatively keep restarting level in pause menu)

### Expected behavior

not crash

### Environment

teardown 1.5.4
OS: windows 11
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
Graphics driver version: Geforce Game Ready 551.76
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

### Additional context

also the editor lag spikes are back

**Comment by MexicanHulkHogan42069** [comment]
another thing i forgot to mention, crashes happen mostly on the second run, and if i exit the editor and reopen it and rerun it still crashes

**Comment by MexicanHulkHogan42069** [comment]
update: it also crashes if you open and run a completely different xml after running the xml with crusty script

**Comment by MexicanHulkHogan42069** [comment]
update: i disabled all of my mods and the script still crashes

**Comment by UwQ-Official** [comment]
Maybe provide the script?

**Comment by MexicanHulkHogan42069** [comment]
so it seems it isn't doing it anymore so i'll close the issue, i'll see in the future if it continues once i get back to working on the mod more often
