### ISSUE TITLE
[Bug] Rockets despawns too fast

### ISSUE THREAD

**Issue by LOKSTED** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#54]
### Describe the bug

When rockets are fired straight up, they despawns right before they hit the ground.

### Steps to reproduce the behavior

1. shoot rockets straight up.
2. Be disappointed that they don't hit the ground

### Expected behavior

Rockets should have enough time to fall and hit the ground

### Environment

- Teardown Version: 0.7.4
- OS: Windows
- GPU: 3060 TI
- Graphics driver version: 471.41
- CPU: I5 11400

**Comment by tuxedolabs** [comment]
Expected. There is a timeout for performance reasons.
