### ISSUE TITLE
[Bug] Major frame drop when entering Level Editor

### ISSUE THREAD

**Issue by MexicanHulkHogan42069** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#540]
### Describe the bug

this was caused while reinstalling teardown in an attempt to fix the other major problems i was having

when i enter the level editor my frames drop tremendously to approx. 6fps, and the low framerate remains even after exiting the editor and going in-game (it doesn't happen on the main menu) (also worth noting the framedrop doesn't occur when going in-game before entering the level editor)

### Steps to reproduce the behavior

- do anything beforehand, like going on a sandbox map & see framerate remain high
- enter level editor
- frame drops to -3 fps
- go anywhere else and the low framerate will remain (except main menu)

### Expected behavior

level editor not dropping my frames

### Environment

teardown 1.5.4
OS: windows 11
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
Graphics driver version: Geforce Game Ready 551.76
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 MHz, 4 cores, 8 processors

**Comment by YuLun-bili** [comment]
We need a more specific way of reproduction if you could find out one. Otherwise it's hard to identify reason(s) for this issue

**Comment by MexicanHulkHogan42069** [comment]
i just have to enter the level editor no matter what way i do it from, as soon as i load up the level editor is drops my frames, so nothing else but opening the level editor causes it

and like i said previously, this is bizzarely only a problem i have, alongside the multitude of other bugs i reported here

**Comment by MexicanHulkHogan42069** [comment]
so it seemingly just fixed itself? i went back on teardown today and the issue is gone, so i figure you just have to restart your computer to fix the framedrop issue, although i did play teardown on windowless mode to try to record the issue but i don't think that was what fixed it
