### ISSUE TITLE
[Bug] Marina not in "built-in" menu

### ISSUE THREAD

**Issue by Squidward1Tentacles** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#545]
### Describe the bug

One of my colleagues is trying to create a map based on marina, but it is not within the built-in menu, nor can I find it anywhere else.

### Steps to reproduce the behavior

1. Go to 'built-in menu'
2. Scroll down to 'marina' (the part that's missing)
3. See error

### Expected behavior

Marina should have been visible in the built-in menu

### Environment

- Teardown Version: 1.5.4
- OS: Windows 11
- GPU: Nvidia GeForce RTX 4060
- Graphics driver version: 536.45
- CPU: AMD Ryzen 9 7000 Series

**Comment by bingleboy** [comment]
Shows up fine for me on 1.5.4. Perhaps try verifying your local files? Should be listed under 'West Point Marina' at the bottom of the built-in mod list.

**Comment by YuLun-bili** [comment]
closing as no response from submitter for a month and the map is indeed in built-in menu
