### ISSUE TITLE
[Bug] Sounds from content browser keep '.tde'

### ISSUE THREAD

**Issue by ExoticGameStudios** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#546]
### Describe the bug

When you drag sounds from the content browser into a light object (or any other, I just did a light) it keeps the '.tde' extension on the end of the filename

### Steps to reproduce the behavior

1. Go to the mod editor
2. Create a light
3. Drag a sound from the content browser into the light's sound property
![image_2024-04-05_191522362](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/57577105/f9d5fc71-6d7f-4c33-ac69-3734bbefa499)

### Expected behavior

It should remove the .tde at the end of the filename

### Environment

- Teardown Version 1.5.3 [Experimental]
- OS: Windows
- GPU: MSI GTX 1660 TI
- Graphics driver version: Latest
- CPU: AMD Ryzen 7 3800X

**Comment by UwQ-Official** [comment]
Ok, but does that really matter? It's the same file after all
Also, you can just delete the `.tde` ig

**Comment by YuLun-bili** [comment]
Experimental is 1.5.4

**Comment by ExoticGameStudios** [comment]
> Experimental is 1.5.4

1.5.3 was a typo

**Comment by Gregory-Gregory** [comment]
@thatonespookymonth hi!

Thank you for the bug report, it has been reported to the team.
If they need any additional details, I will let you know.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
