### ISSUE TITLE
[Bug] IUnable to update mods via experimental

### ISSUE THREAD

**Issue by GeneralShark05** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#547]
### Describe the bug

Unable to update mods via experimental, just responds with "Upload Failed"

### Steps to reproduce the behavior

1. Go to experimental
2. Upload a mod
3. Attempt to update

### Expected behavior

The mod updates

### Environment

- Teardown Version 1.5.4
- OS: Windows
- GPU: RTX 3060
- Graphics driver version: 31.0.15.3752
- CPU: Intel i7-12700K

**Comment by YuLun-bili** [comment]
Fixed I think
https://discord.com/channels/760105076755922996/786232592080437288/1227945856330629191
