### ISSUE TITLE
[Bug] Can't get size of area lights and capsule lights

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#549]
### Describe the bug

using `GetProperty(handle,"size")` on a light with its type set to "area" or "capsule" only returns one value despite the fact that both of these light types have two size measurements. Additionally, on an area light, this function will always return 0.10000000149012 (0.1, but precision errors exist) no matter the actual size of the light. When called on a capsule light, the radius is returned, but not the length.

### Steps to reproduce the behavior

1. Call `GetProperty(handle,"size")` on any valid area/capsule light handle
2. Debug this value
3. See error

### Expected behavior

Both measurements should be (accurately) returned.

### Environment

- Teardown Version 1.5.4
- OS: Windows

**Comment by Gregory-Gregory** [comment]
@bingleboy hi again!

Thank you for reporting this issue. I have forwarded all the information to the team.
If they need any additional details, I will let you know.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0, function would return two variables for size of those lights
