### ISSUE TITLE
[Bug] GetVehicleHealth doesn't updated if the player is not in that vehicle. 

### ISSUE THREAD

**Issue by Allshar** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#55]
### Describe the bug

GetVehicleHealth updates only if player is currently driving said vehicle - otherwise it returns the last value (starting at 1). 

### Steps to reproduce the behavior

1. Open Editor
2. Add script: `function tick(dt) DebugPrint(GetVehicleHealth(FindVehicle("testCar",true))) end`
3. Add a vehicle with a tag "testCar"
4. Play
5. "1" will print
6. Damage the car. 
7. "1" will still print. 
8. Get in the car. 
9. New health value will print.

NOTE: 
In my testing, adding a car as an instance and converting to a group to add a tag causes this issue. 
Adding a new vehicle doesn't cause it, UNTIL you add wheels. 
So the only case in which it works is when you have a vehicle with no wheels. 

### Expected behavior

GetVehicleHealth should always return current health of that vehicle. 

### Environment

- Teardown Version 0.7.4
- OS: Windows 10
- GPU: GTX 1070
- Graphics driver version: 461.09
- CPU: AMD Ryzen 7 1800X

**Comment by tuxedolabs** [comment]
Thanks for the report. This is known behavior. The health is only recomputed when trying to drive the vehicle for performance reasons. Is there a good reason to display health for a vehicle you are not driving. The reason it works on boats is because the health is needed for buoyancy.

**Comment by Allshar** [comment]
I was creating a level where the player had to transport a target vehicle to the specified destination. 
The vehicle could be moved and/or damaged without the player actually driving it (by pushing or dragging it). 

No need to update every vehicle every frame, but a way to manually request an update for a specific vehicle, or to tag a vehicle as important, would be nice. 

I made a workaround by comparing current vehicle body mass to the initial value. That works well enough.

**Comment by tuxedolabs** [comment]
Finally fixed this in 0.9.3. The health gets computed every time it is queried.
