### ISSUE TITLE
[Bug] `hud.notification` incorrectly displaying text outside of bounds on localized lines.

### ISSUE THREAD

**Issue by lazyRares** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#557]
### Describe the bug

When using `hud.notification` the text will not correctly extend the boundaries of the UI box to display all the text. This happens on all languages with any line, it seems the length is either hardcoded based on the line's length or otherwise.

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/33793448/0ba5880e-836c-4764-96e8-84b4e2d731d3)
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/33793448/7c298b92-67d8-4a11-a490-d3d1882e3a38)

**EDIT:** After some testing this seems to be only on localized lines, I hypothesize that it is setting the UI's length to the localization line's length but not accounting and changing the length once the actual line is inputted in, since there's no issues using non-localized lines.

### Steps to reproduce the behavior

1. Create script using `SetString("hud.notification","")`
2. Set the string to be used as any lengthy one, such as `loc@TOOL_DESC_ROUNDS_NITROGLYCERIN`
3. Test

### Expected behavior

The box should wrap it's length across the entire line, and comfortably fit all the words with margins and spacing. 

### Environment

- Teardown Version 1.5.4 
- OS: Windows

**Comment by Gregory-Gregory** [comment]
@lazyRares hi!

Thank you for reporting this issue. It has been forwarded to the team for further investigation.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0

**Comment by UwQ-Official** [comment]
if it's resolved, then why is this issue still open?

**Comment by YuLun-bili** [comment]
would close after 1.6.0 went public rather than being an experimental branch
