### ISSUE TITLE
[Bug] Weird clipping region for `DebugLine()`

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#558]
### Describe the bug

https://discord.com/channels/760105076755922996/768940642767208468/1232829530230755348
(message from Teardown discord server)

Basically there's a clipping region aligned at top left corner of screen for `DebugLine()`, lines outside that region would not be drawn. And the size of the region is related to rendering scale in options.

### Steps to reproduce the behavior

1. Call `DebugLine()` such that it would draw line(s) across entire screen space diagonally.
2. Change rendering scale in game's options
3. Observe debug lines got clipped into a smaller region

### Expected behavior

No clipping, debug lines always drawn in entire screen space

### Environment

- Teardown Version 1.5.4
- OS: Windows 11

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi!

Thank you for reporting this issue. It has been forwarded to the team for further investigation.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
