### ISSUE TITLE
[Bug] Opening map view reset flashlight status

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#559]
### Describe the bug

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/6d73ff77-fe15-4d1e-8546-ed014dfee323

### Steps to reproduce the behavior

turn on flashlight and open then close map view

### Expected behavior

flashlight status remain unchanged

### Environment

- Teardown Version 1.5.4

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi again!

I have forwarded this issue to the team as well. Thank you for reporting it 🤝

**Comment by YuLun-bili** [comment]
resolved in 1.6.0, close after publish release
