### ISSUE TITLE
[Bug] Cannot Get "size" Property of Joints

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#560]
### Describe the bug

Calling `GetProperty(handle,"size")` where `handle` refers to a joint will throw an error in the console ("Error: Unavailable property size"), despite being listed as an available joint property in the documentation.

### Steps to reproduce the behavior

1. Call `GetProperty(handle,"size")`, where `handle` points to a valid joint of any type
2. See error

### Expected behavior

The joint's size property should be accurately returned and an error should not be thrown.

### Environment

- Teardown Version 1.5.4
- OS: Windows

**Comment by Gregory-Gregory** [comment]
@bingleboy hi!

Thank you for reporting this issue. It has been forwarded to the QA team for further investigation.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
