### ISSUE TITLE
Editor shows wrong outline in isometric view

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#565]
### Describe the bug

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/a8d4083e-b9dc-4a32-bb75-74965cf11a8c)

![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/1898194/7b97d95c-6abc-40f5-8341-8972a9ff495f)

### Steps to reproduce the behavior

1. Go to editor
2. Click on isometrc
4. Select something
5. Zoom in a bit
6. Move the camera around

### Expected behavior

Outline around the actual visual object

### Environment

- Teardown Version 1.5.4
- OS: Linux
- GPU: 3080

**Comment by Gregory-Gregory** [comment]
@nooitaf hi!

Thank you for reporting this issue. It has been forwarded to the QA team for further investigation.

**Comment by YuLun-bili** [comment]
persists in 1.6.0

**Comment by YuLun-bili** [comment]
nah it's fixed in 1.6.0 I forgot to check game ver 💀 
gonna close after public release
