### ISSUE TITLE
[Bug] Big destructions cause gpu clock and wattage to go down

### ISSUE THREAD

**Issue by DaMysticRaffy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#57]
### Describe the bug

Whenever you destroy big buildings at once (with a nuke or something else), your gpu clock and wattage go down to basically nothing

### Steps to reproduce the behavior

1. Go to any big building
2. destroy it with a nuke or something alike
3. open performance menu
4. See clock and wattage go down

### Expected behavior

wattage to go up and clock to stay the same

### Environment

- Teardown Version: 0.7.4
- OS: Windows 10
- GPU: Geforce GTX 1660TI
- Graphics driver version: 471.68
- CPU: Intel Core i3-8100

**Comment by DaMysticRaffy** [comment]
> > > I5 10600KF & RTX 2060 super
> > > Followed exact same steps and couldn't reproduce. i agree with roverbot and it may be a bottlenecking issue.
> > > If possible recordings of the issue would help.
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     2021-08-27.09-08-29_Trim.mp4
> 
> What mods do you have installed/enabled?

just the tools you see in the video

**Comment by RoverBot-Dev** [comment]
I noticed that my gpu wattage goes from 30W to 22W when destroying stuff (with megagun), and also gpu usage goes down. I also have a 10% gpu bottleneck

**Comment by tuxedolabs** [comment]
Expected behavior. GPU is waiting for CPU, thus usage goes down.
