### ISSUE TITLE
Mods Not Working

### ISSUE THREAD

**Issue by Eboy09** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#571]
### Describe the bug

I started playing Teardown again a week ago but for some reason my subscribed mods don't show up on the Mods Manager section in-game...

### Steps to reproduce the behavior

1. Click on Mods Manager
2. Go to the Subcribed section
3. See error (No mods show up)

### Expected behavior

When I go to the Subscribed section I should see all the mods I subscribed to.

### Environment

- Teardown Version: 1.5.4
- OS: Windows 10
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Graphics driver version: 31.0.15.5222
- CPU: Intel(R) Core(TM) i7-3770

**Comment by YuLun-bili** [comment]
Make sure you have stable Internet connection with steam workshop (steamcommunity.com). The game would do some checks related to mods after started and no mods subscribed would show up until checks are done.

**Comment by Eboy09** [comment]
I do have stable internet, and also it doesn't say anything about mods subscribed. It just doesn't show anything, but when I go to featured mods and click subscribe, it just says "Downloading..." but never does.

**Comment by Eboy09** [comment]
I figured out the problem myself, I just had to change which disk I had the game stored on
