### ISSUE TITLE
[Bug] Unlabeled hyperlink in mod description activates unexpectedly

### ISSUE THREAD

**Issue by Malar10** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#578]
### Describe the bug

An unlabeled link in a mod description will send the player to it's address when pressing other buttons

video of me performing the bug (link expires in 2 days, please tell me if you need another)
https://streamable.com/qkw504

[Here](https://github.com/user-attachments/files/15874342/_linkreport.zip)is the mod I used in the video

### Steps to reproduce the behavior

1. Aquire mod with a description consisting only of an unlabeled https link
example description in info.txt: `description = [[http://www.example.com]]`

2. Open mod manager and click on the mod
Notice the description looks empty
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/83091887/40c1d246-ef35-4cf8-b5e6-2c472c9353ec)

3. Click out of mod manager 
4. Try to open mod manager again
5. Get sent to the link's address without your consent

### Expected behavior

The link should not do anything if the player doesn't click on it

Also unlabeled links should not be invisible, but instead display the target address
Normally this does happen, but only if there is also other text in the description

`description = a[[http://www.example.com;]]`
![image](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/83091887/55148ed3-5d12-474b-a2c5-238517e75b79)
the above description shows normally and does not unexpectedly send the player to a website

### Environment

- Teardown Version 1.5.4
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 2060
- Graphics driver version: 32.0.15.5585
- CPU: AMD Ryzen 7 2700 Eight-Core Processor

**Comment by nooitaf** [comment]
This should have been communicated privately, as in.. "responsable disclosure".
Why is it even possible to put a link in there at all???

**Comment by Malar10** [comment]
You're right, I may not have thought of all the implications of this bug.

Also links and hyperlinks are a documented feature (for some reason)
https://teardowngame.com/modding/api.html#UiText

**Comment by YuLun-bili** [comment]
we got the new web link format since 1.5.4 (around Mar 4th) when they changed method of handling link to game's modding website in mod manager.

**Comment by Gregory-Gregory** [comment]
@Malar10 hi! 

Thank you for reporting this issue. I have shared the information with the QA team.

Unfortunately, the link is not available anymore. Can you please send it an as attachment or upload it to a Google Drive?

**Comment by Malar10** [comment]
@Gregory-Gregory hi
I've uploaded the video to google drive
Here's the link: https://drive.google.com/file/d/1soVNGpuxmrcw_93VL3la_mwtP7TcNgHM/view?usp=sharing

**Comment by Gregory-Gregory** [comment]
@Malar10 thank you! I have added the video to the investigation.

**Comment by Malar10** [comment]
resolved as all hyperlink functionality was removed in august 7th patch
