### ISSUE TITLE
[Documentation] InputLastPressedKey() is called InputLastPressed() in the provided example.

### ISSUE THREAD

**Issue by EldinZenderink** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#58]
### Document to improve

[https://teardowngame.com/modding/api.html#InputLastPressedKey](https://teardowngame.com/modding/api.html#InputLastPressedKey)

### Enhancement

InputLastPressedKey() is called InputLastPressed() in the provided example.

![image](https://user-images.githubusercontent.com/12187560/132576957-065bec18-d6fc-4c6c-99d4-8dd4afbd7770.png)

**Comment by tuxedolabs** [comment]
Fixed in 0.8. Thanks!
