### ISSUE TITLE
[Bug] Quit any mod's options menu via Esc key crashes game

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#585]
### Describe the bug

as described in title

### Steps to reproduce the behavior

open any mod's options menu and quit by pressing esc key, notice game blackscreens and crashes

### Expected behavior

no crash, back to main menu normally

### Environment

- Teardown Version 1.6.0 (experimental)
- Win 11

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi!

Can you please attach a local CrashDump after the crashing from this? The file may be in some of the following paths:
- `\AppData\Local\CrashDumps`
- `\AppData\Local\Teardown\crash`
- `\Documents\Teardown\crash`

They usually help the team a lot.

Thank you!

**Comment by YuLun-bili** [comment]
@Gregory-Gregory nope there's no crashdump here for this for some reason...

**Comment by YuLun-bili** [comment]
Ok now I got one
[2024-06-24-18-35-29_Steam_692.zip](https://github.com/user-attachments/files/15959406/2024-06-24-18-35-29_Steam_692.zip)

**Comment by YuLun-bili** [comment]
and it's not related to my modifications towards game files as I just retried after verified game files, same result.

**Comment by Gregory-Gregory** [comment]
@YuLun-bili thank you for the archive! I have reported the issue to the QA team.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0 experimental
