### ISSUE TITLE
[Bug] Folkrace Crashing on PS5 on 23 Stars

### ISSUE THREAD

**Issue by DonutEats** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#588]
### Describe the bug

When a certain amount of stars are achieved in the Folkrace DLC, the game crashes and the campaign crashes every time it is opened after the crash. I assume it has something to do with the Möbel Folkrace League (which requires 23 stars to unlock). I have reset the campaign multiple times with the game crashing at the same point each time. The crash doesn't happen until I quit back out to the garage (I was able to continue to the next race in the championship I was in and reached the car select menu, but then I quit to the garage and the game crashed).

### Steps to reproduce the behavior

1. Start the campaign in the Folkrace DLC
2. Play the career
3. Achieve 23 stars
4. The game crashes upon exiting to the garage

### Expected behavior

The game quits to the garage and the Möbel Folkrace League is unlocked.

### Environment

- Teardown Version 1.5.4
- OS: Playstation 5

### Additional context

This might have nothing to do with it, but every time the crash happened, I was in the Almondman's Folkrace Cup.

**Comment by Gregory-Gregory** [comment]
@DonutEats hi!

This issue should be fixed in the upcoming hotfix. At the moment, there is no ETA, but the team hopes to release it as soon as possible.
