### ISSUE TITLE
[Feature] Add Getters for multiple properties that are currently missing them

### ISSUE THREAD

**Issue by enveeed** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#59]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

There are quite a few properties that you can set in scripts using setters like `SetSomething(stuff)`.
However, it should be also possible to obtain the current value, not just set it.

The affected properties are currently *write-only* values for scripts which is very limiting.

### Describe the solution you'd like

The following functions should be added:

- `GetShapeEmissiveScale(handle)`
- `GetLightIntensity(handle)`
- `GetLightColor(handle)`
- `GetCameraFov()`

It's likely that I've missed some, but these are the ones I personally encountered.

### Describe alternatives you've considered

I am not aware of any other ways to get the values returned by the proposed new functions.

**Comment by tuxedolabs** [comment]
I can definitely see the need, but the API would blow up if there were getters and setters for every property. I'm investigating a more unified method of doing this in the future (which is tried on environment and post processing in 0.8). Something like:

r,g,b = GetProperty(light, "color")
SetProperty(light, "scale", 4.0)

**Comment by enveeed** [comment]
I agree, this is a much better approach. Looking forward to this being used for all properties.
