### ISSUE TITLE
[Bug] Unusual movement staggering issue occuring at random on experimental branch

### ISSUE THREAD

**Issue by Ferynix** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#599]
### Describe the bug

Simply put, while attempting to move around on the experimental branch, the character / my movement occassionally staggers.

I suspected it had to do with a mod, so I temporarily deleted my modlist, and confirmed the issue was still present. The recording below only has two mods running (Screen Recorder and my menu mod to access the tools with constantly-resetting savegames)

### Steps to reproduce the behavior

I couldn't find a precise way to recreate the bug besides just playing different maps and using all four movement keys until I hit a spot that would repeatedly cause staggering.

Video of the bug

https://youtu.be/OCRgjXni5u4

Additional video with even more obvious staggering in first person... Reminder Im only holding the W key in this video for the most part... I should be walking straight forward.

https://youtu.be/pwbL0eA0RcE

### Expected behavior

The player is definitely not supposed to stagger trying to walk in a straight line.

### Environment

- Teardown Version: 1.6.0 (Experimental Branch)
- OS: Windows 11
- GPU: Nvidia RTX 2070 Super
- Graphics driver version: RTX Game Ready Driver 556.12
- CPU: AMD Ryzen 7 2700 X

### Additional context

This issue seemingly only appeared recently, hence my suspicion of it being caused by a mod, but even disabling every single one in the game, I still cant seem to rid myself of this bug. It's made testing things on experimental rather tedious

**Comment by Ferynix** [comment]
Other things to note: Happens regardless of any tools Im using, what character is selected, and what map Im in. It seems to be an issue affecting the entire game as a whole, and I didn't experience this initially. It only showed up some time after I started developing in 1.6... I assume a minor patch or update came out, because this issue just didnt occur at all when I had first been testing the new branch.

**Comment by Gregory-Gregory** [comment]
@MisterSirCode hi!

Thank you for reporting this. I have forwarded the issue to the QA team for investigation.

Just in case, please also share a DxDiag file: 
- In Windows, select **Start** and enter **dxdiag** into the search box on the taskbar. Select **dxdiag** from the results.
- In the tool, select **Save All Information** for an easily shared format.

Attach this file to your reply. It usually helps the team a lot.

Thank you!

**Comment by Ferynix** [comment]
Im closing this on my own as it turns out I had unfortunate timing. My keyboard / usb port / pc (or maybe all three, or maybe none of them) seems to be the issue.

Ive managed to reproduce the bug on more then one game, meaning this is not part of teardown.

Unfortunately it seems Ill have to solve this on my own.
