### ISSUE TITLE
[Feature] Add a shape-local space variant of GetShapeMaterialAtPosition(handle, pos)

### ISSUE THREAD

**Issue by enveeed** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#60]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Currently there is no way to *accurately* get a voxels material in a shape if you have the shape-local coordinates of that voxel. You have to convert it into world space to use the current `GetShapeMaterialAtPosition()` which has some issues (see #33).

### Describe the solution you'd like

A function should be added that does the same thing as `GetShapeMaterialAtPosition(handle, pos)` but takes local space coordinates instead of world space ones and does not "scan" for voxels at the position, but simply looks up the position in the current shape.

Example:
```
local type, r, g, b, a = GetShapeMaterialAtLocalPosition(handle, pos)
```

### Describe alternatives you've considered

As mentioned above its possible to *somewhat* achieve the same thing with world space vectors but it is way less accurate.

**Comment by tuxedolabs** [comment]
I have added the integer-based version GetShapeMaterialAtIndex to 0.8
