### ISSUE TITLE
[Bug] [Experimental] DebugCrosses spazzing out if called from draw()

### ISSUE THREAD

**Issue by Malar10** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#606]
### Describe the bug

Only happens on the experimental branch I think
Debug crosses called from the draw() function will occasionally draw colored lines across the screen
The more crosses in view, the more intense the effect, but I have seen it happen even with a single debug cross.

Here is a video example with 10 000 debug crosses

https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/83091887/7cd8fd8a-7773-48af-aaa9-702a07e9217a

and here's the level from the video [!_crossreport.zip](https://github.com/user-attachments/files/16141322/_crossreport.zip)

### Steps to reproduce the behavior

1. Make sure experimental branch is enabled
2. Open the level linked above (or any mod with debug crosses called from draw)
3. See debug crosses go crazy

sometimes moving around or pausing the game can cause the effect to be more visible

### Expected behavior

debug crosses should not do that

### Environment

- Teardown Version 1.6.0 experimental
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 2060
- Graphics driver version: 32.0.15.5585
- CPU: AMD Ryzen 7 2700 Eight-Core Processor

**Comment by Gregory-Gregory** [comment]
@Malar10 hi!

Thank you for reporting this issue. It has been forwarded to the QA team for further investigation.

**Comment by YuLun-bili** [comment]
resolved in 1.6.0
