### ISSUE TITLE
[Bug] Crashes related to multiple Explosions and TriggerEvents

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#607]
### Describe the bug

So while testing the [Synthetic Swarm](https://steamcommunity.com/sharedfiles/filedetails/?id=3289269367) mod I encountered several crashes from unsure origin, here are some of the hypothesis of what may have causes the crash : 

- ~~Explosion or MakeHole called inside of a large shape (200x200x200 vox)~~
- ~~Body/Shape/Script being deleted (maybe deleted twice?)~~
- ~~Explosion called near an unbreakable body~~

EDIT: I made some more tests and pinpointed the exact chain of events leading to the crash which seems to be: simultaneous explosions detected by `handleCommand` calling some `TriggerEvent` back and forth between two scripts.

### Steps to reproduce the behavior

1. Unzip this in your mod folder : [crash TriggerEvent.zip](https://github.com/user-attachments/files/16232426/crash.TriggerEvent.zip)
2. Ingame spawn the object called "crash" which is made of a small and a big cube.
3. Attack the bigger cube it with the Megagun in "Mini nuke" mode.

### Expected behavior

Game does not crash.

### Environment

- Teardown Version: 1.5.4
- OS: Windows
- GPU: NVIDIA GeForce RTX 3070 Ti
- Graphics driver version: 552.44
- CPU: AMD Ryzen 7 6800H with Radeon Graphics

### Additional context

Most of the initial crashes occurred when a Drone Factory was self-imploding as a black hole and some enemy drones were caught into the black hole radius and deleted by it. Sadly I forgot to grab the crash folders and they got deleted for the 3 to 4 crashes I encountered in this situation and they got deleted next time I started the game...

Another crash was produced when the Dragon was being attacked by a Fighter Drone MK3 and launched a fireball back at it. Here is the crash dump for it:  [2024-07-14-16-07-31_Steam_694.zip](https://github.com/user-attachments/files/16227761/2024-07-14-16-07-31_Steam_694.zip)

And finally I encountered another crash when attacking a Fighter Drone MK3 myself with the Megagun weapon in "Mini nuke" mode. Here is the crash dump for it: [2024-07-14-17-42-37_Steam_694.zip](https://github.com/user-attachments/files/16227937/2024-07-14-17-42-37_Steam_694.zip)

**Comment by YuLun-bili** [comment]
@FlorentP42 #596?

**Comment by FlorentP42** [comment]
> @FlorentP42 #596?

That looks like pretty much the same bug, how did I miss it >_< Well I guess we can keep that one open until 1.6.0 become the main branch still ;)

**Comment by YuLun-bili** [comment]
#596 is resolved and both issues are of same type
