### ISSUE TITLE
[Bug] `UiTextInput()` cannot handle text deletion correctly when cursor at middle of string

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#609]
### Describe the bug

as described in title

### Steps to reproduce the behavior

1. Open any menu that using `UiTextInput()` function for input (e.g. Spawn menu)
2. enter any string that's longer than 4 characters (e.g. `1234567890`)
3. use arrow key to move cursor to middle of string (`|` represent cursor, `12345|67890`)
4. press backspace key on keyboard
5. notice result string is not expected (result would be `123406789` in this example)

### Expected behavior

well we know what it should be...

### Environment

- Teardown Version 1.6.0
- Windows 10

### Additional context

this issue may exist since implementation of this function

**Comment by FlorentP42** [comment]
Pretty sure that title should be "text deletion" ;)

**Comment by Gregory-Gregory** [comment]
@YuLun-bili hi,

Thank you for reporting this issue. I have forwarded it to the QA team for further investigation.

**Comment by YuLun-bili** [comment]
closing after 1.6.0 went public
