### ISSUE TITLE
[Bug] Invisible walls and glitched campaign

### ISSUE THREAD

**Issue by strawberrybooba** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#61]
### Describe the bug

I got the game 3 days ago, super excited to start playing after watching many YouTube videos on it. I launch the game the next day and click on campaign excitedly. I spawn in on an invisible, tall platform. I swipe it off as a small glitch when I keep moving forward to the gates. I open them, completely unaware of the invisible gateposts, and stumble upon a building with  the front and back walls completely invisible. I am still unaware of this glitch and only realize when I am smashing an invisible door open with visible barrels. 'Okay,' I think, 'let's just keep waiting and see if the missions are okay," because I really want to play. So, I struggle to fix an invisible generator and click on the computer, clicking on mission 1. It goes on the loading screen for 3 minutes, and then freezes on a black screen and I have to force shutdown. I go to sleep, ready to try again tomorrow. So here I am back again with my invisible building. I had just verified my game files, hoping it might help. I click on mission 1 and after waiting 10 minutes for the mission to appear, it finally does. It's not normal, though, as it freezes. I sigh, determined to keep waiting for it to load up. My computer is severely overheating at this time and the whole screen starts to turn into glitchy cubes. Scared for my computer, I force shut down again, quicker this time. Please help!

### Steps to reproduce the behavior

1. Install 'Teardown' on Steam
2. Launch 'Teardown'
3. Click 'Campaign'
4. Spawn in
5. Stare in horror at the invisible things around you
6. Do the quests needed
7. Access Mission 1
8. Watch as your computer has a seizure

### Expected behavior

I was supposed to have visible walls and working missions, like the youtubers had.

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: Windows 10
- GPU: AMD Radeon(TM) Vega 8 Mobile Graphics
- Graphics driver version: Vega 8 (?)
- CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

### Additional context

Top 2: Invisible Gateposts and Invisible Building
Bottom 1: Glitched Mission 1 Frozen Screen

![image0 (2)](https://user-images.githubusercontent.com/91277366/134589078-b1915764-2dd8-4dfc-99d6-9d125c702940.png)

![image1](https://user-images.githubusercontent.com/91277366/134589081-88134dd6-0e0a-462d-bf48-cdbfa6a47cac.png)

![image2](https://user-images.githubusercontent.com/91277366/134589086-6c0a4125-4dc9-4821-a44e-8e740e7ed672.jpg)

**Comment by RoverBot-Dev** [comment]
You can ask discord.gg/teardown , but you should verify your game files on steam first. Also try to update your gpu drivers.

**Comment by strawberrybooba** [comment]
i literally said in my issue that i verified game files,, also ill try to update my drivers when i get home from school

**Comment by tuxedolabs** [comment]
Hardware is below minimum specs.
