### ISSUE TITLE
[Documentation] Broken link

### ISSUE THREAD

**Issue by UwQ-Official** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#614]
### Document to improve

A [link (the xml version)](https://www.teardowngame.com/modding/api.xml) under the [main modding page](https://teardowngame.com/modding/index.html#teardownlinks) is broken.

### Enhancement

The page is broken and shows that when viewing it:
![image](https://github.com/user-attachments/assets/911aad2e-c3b4-4db3-a56a-4f7f08a9463f)

**Comment by lelanceflamer** [comment]
Yeah, I think it's because they only used **&** and not **`&amp;`** somewhere if I'm not wrong. I don't know why the devs didn't notice this..

**Comment by Marcus-Dawson** [comment]
The website is autogenerated and the script didn't understand the & problem. It has been manually corrected now so it should work.

**Comment by UwQ-Official** [comment]
@YuLun-bili It's broken once again ://
![image](https://github.com/user-attachments/assets/8a4d2dbf-9c39-4381-bbd6-44a1334cc690)

**Comment by Marcus-Dawson** [comment]
It should be fixed now. Sorry about that. I have past on the issue to the team so it should fixed at the source now and not manually fixed in the website.
