### ISSUE TITLE
[Bug] Game crashes when undeclared variables are used without warning (in QueryClosestFire)

### ISSUE THREAD

**Issue by EldinZenderink** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#62]
### Describe the bug

Well, trying to play with the new QueryClosestFire, and as you do, you forgot to actually declare the variable for the position argument... 

### Steps to reproduce the behavior

1. Create a basic mod lua script
2. Add the following to the tick function:
    `QueryClosestFire(notadeclaredvariable, 5.0)`
3. Enable the mod
4. Load a map
5. Poof, teardown gone.

### Expected behavior

I would expect the lua interperter to warn me, and mistakes in lua should not crash the game, or at least should show why the game crashed. This currently is just a silent crash. 

### Environment

- Teardown Version: 0.8.0 
- OS:  Windows
- GPU: RTX 2080 Super
- Graphics driver version: 471.68
- CPU: AMD Ryzen 5 5600X

**Comment by tuxedolabs** [comment]
Can not reproduce. Works as expected (queried position will be world origo)
