### ISSUE TITLE
[Feature] .Tdignore equivalent for gitignore

### ISSUE THREAD

**Issue by DimasVoxel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#620]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Often when we upload mods to workshop we have a lot of junk that we don't want to upload. Git folders and source files(blend, music project files, etc.) that increase the mods download size. Sometimes they take up half of the mod itself. 
Right now we often have a development version and a release version which is stripped of all the junk just to upload.
Ignoring those files would help us to clean up our mods and not to upload anything the players don't need.

### Describe the solution you'd like

A .TDignore file which would be at the root of a mod. 
Working exactly like gitignore specifying absolute and relative paths to ignore certain items.

\*.blend 
MOD/sourceFiles/\* 

### Describe alternatives you've considered

Doing it the long and manual way

**Comment by YuLun-bili** [comment]
#476

**Comment by hotcocoadotcom** [comment]
I pledge allegiance.. to the Dima. of the Teardown Modding Community. And to the Community, for which it stands. One server, under Voxagon, indivisible, with liberty ...And Justice For All

**Comment by lazyRares** [comment]
You’ll need to dig through the filler files and burn through the useless stuff and slam in the back of your workshop mod!

**Comment by nooitaf** [comment]
~~Unpractical.~~ 
`.blend` would not ignore blend files but a hidden folder/file.. 
`*.blend` would ignore blend files, but only in the scope of that directory, not subdirectories. ( _edit: wrong, but it wont ignore files commited before gitignore got added_)
`MOD/sourceFiles/` doesn't make sense, as `MOD` refers to the folder you are already in.

I stand by the best and easiest solution written out here https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/476#issuecomment-1836908190 

Or in other words.. learn to symlink a folder and all of these issues go away.

**Comment by DimasVoxel** [comment]
If git ignore would be unpractical, none would use it.

Yes my example of .blend was a mistake I meant *.blend and Mod/ can just be / to symbolise the root of the folder (I actually had \*.blend but I forgot to escape the \*

**Comment by Thomasims** [comment]
> Unpractical. `.blend` would not ignore blend files but a hidden folder/file.. `*.blend` would ignore blend files, but only in the scope of that directory, not subdirectories. `MOD/sourceFiles/` doesn't make sense, as `MOD` refers to the folder you are already in.
> 
> I stand by the best and easiest solution written out here [#476 (comment)](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/476#issuecomment-1836908190)
> 
> Or in other words.. learn to symlink a folder and all of these issues go away.

That "solution" is much more unpractical than the proposed feature. It might be the simplest workaround to use git with TD mods we currently have but that doesn't make it good.

**Comment by nooitaf** [comment]
Ok.. it would be nice to have.. i agree. 
But in the meantime symlinks is the way to go :P

**Comment by UwQ-Official** [comment]
It was added..?

**Comment by DimasVoxel** [comment]
> It was added..?

Yes

**Comment by YuLun-bili** [comment]
wait what

**Comment by DimasVoxel** [comment]
> wait what

You didn't know?

**Comment by Ferynix** [comment]
> > wait what
> 
> You didn't know?

Is there a documentation on this available somewhere? I had no idea either, no ones mentioned it

That would be supremely handy

**Comment by YuLun-bili** [comment]
https://discord.com/channels/760105076755922996/786232592080437288/1307772648461434993
https://discord.com/channels/760105076755922996/786232592080437288/1308166590877011988
