### ISSUE TITLE
[Bug] Spawning Items freezes Game 

### ISSUE THREAD

**Issue by TacticalCapybara978** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#621]
### Describe the bug

The game freezes when i try to spawn things in, it doesnt happen every time and seems to be a 50/50 chance of crashing. I can get into the spawn menu but when i choose to spawn something it crashes. It started around when update 1.5 released and seems to happen with AMD gpus or maybe even just AMD 5700 gpus.

### Steps to reproduce the behavior

(there isnt really a way i would know how to make it happen but here is what i do to make it crash)
1. Go to the spawn menu
2. Click on an item to spawn
4. Game crashes

### Expected behavior

it should let me spawn in the item.

### Environment

- Teardown Version 1.6.0
- OS: Windows
- GPU: AMD RX 5700
- Graphics driver version:  24.8.1
- CPU: AMD Ryzen 5 3600 6-Core Processor

### Additional context

 It started around when update 1.5 released and seems to happen with AMD gpus or maybe even just AMD 5700 gpus.

**Comment by YuLun-bili** [comment]
@TacticalCapybara978 Does crash happens no matter what is being spawned?
If the object being spawned is large (like a large ship) it's *normal* for game to briefly freeze for a while as game need to load the object.

**Comment by TacticalCapybara978** [comment]
@YuLun-bili 

No, It can be anything from a prop to a whole cargo ship and there's a chance it will crash, also when it crashes, it crashes for ever until the game is closed and relaunched.

I also forgot to mention that it only crashes when spawning things from the default spawn menu, anything from the tabs menu and the dynamic ragdoll 2 menu doesn't seem to crash it.

**Comment by TacticalCapybara978** [comment]
Sorry, hit the wrong button

**Comment by TacticalCapybara978** [comment]
> No, It can be anything from a prop to a whole cargo ship and there's a chance it will crash, also when it crashes, it crashes for ever until the game is closed and relaunched.
> 
> I also forgot to mention that it only crashes when spawning things from the default spawn menu, anything from the tabs menu and the dynamic ragdoll 2 menu doesn't seem to crash it.

@YuLun-bili sorry to disturb you but i wasnt sure if you saw the last message above this, if you have any ideas on what can be causing this issue please let me know.

**Comment by YuLun-bili** [comment]
> @YuLun-bili sorry to disturb you but i wasnt sure if you saw the last message above this, if you have any ideas on what can be causing this issue please let me know.

@TacticalCapybara978 Well I have no experience with such issue and I also have no clue. Better wait for the dev team to investigate, or see if something in public 1.6.0 coming on 10th Oct would fix it.

**Comment by Gregory-Gregory** [comment]
@TacticalCapybara978 hi,

Our team has investigated this issue but has been unable to reproduce it. Can you please recheck it with the latest patch installed?

If the issue persists, please check if you have the **CrashDamp** file. The file can be in one of the folders:
- `C:\Users\<username>\AppData\Local\CrashDumps`
- `C:\Users\<username>\AppData\Local\Teardown\crash`
- `C:\Users\<username>\Documents\Teardown\crash`

Thank you!

**Comment by TacticalCapybara978** [comment]
@Gregory-Gregory  hey, sorry for the late response. I haven’t played teardown in a while so I kind of just forgot about this. In the discord thread that was about this same issue, we got Danny to look at what the issue was and know he says it should be fixed next update, thank you guys for trying to help out!

**Comment by YuLun-bili** [comment]
ref: https://discord.com/channels/760105076755922996/1279589208771657801
