### ISSUE TITLE
[Bug] Raycast ignores solid matter

### ISSUE THREAD

**Issue by TMCAtom** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#627]
### Describe the bug

Raycast sometimes goes through matter (see [video](https://cdn.discordapp.com/attachments/1247977813110161408/1250905526380789812/Recording_2024-06-13_221112.mp4?ex=66fd004e&is=66fbaece&hm=cc1bde3c2ad0bbf50a0184ab53f689aac7849166e7df2f7d7eb6774fd4dbd52b&), sorry too big to embed)
Clarification for video: values in the corner of the screen are irrelevant, observe the DebugLine. It works perfectly up until just after the one minute mark.

### Steps to reproduce the behavior

Create a function that continuously raycasts every frame (does not need the exact same values), this even happens when raycast is called once but calling it every frame makes it easier to visualize.

### Expected behavior

Raycast ignores whatever it hits, setting its distance to its maximum distance, effectively going through solid matter.

### Environment

- Teardown Version 1.6.0 (experimental branch)
- OS: Linux Ubuntu 24.04
- GPU: Nvidia RTX 3060
- Graphics driver version: 550
- CPU: AMD Ryzen 5 3600

### Additional context

Spherecasting does not completely eliminate this behavior, but makes it less likely to happen, but taking up a lot of resources in the meantime.

**Comment by nooitaf** [comment]
Very hard to see what's going on there...
- Is that laser changing the voxels it's hitting?
- What do you mean by "it's maximum distance", i don't see anything specified in the docs. What value are you using?
- With "every frame" you mean in the `tick()` function i assume?
- Can you share that exact Raycast + DebugLine logic?

**Comment by TMCAtom** [comment]
- the laser isnt changing the voxels its hitting
- the maximum distance means the `maxDist` value specified in the `QueryRaycast()` function
- every frame means using the `tick()` function, yes
- basically the DebugLine just goes from the laser origin to wherever the laser is hitting, effectively visualizing it through walls

**Comment by nooitaf** [comment]
So your logic is also doing something when it's not hitting anything? As in `hit` = false/nil

**Comment by TMCAtom** [comment]
that isnt the issue, the issue is that it actively refuses to detect voxels for no apparent reason.

**Comment by nooitaf** [comment]
I made a little test global mod and i can't recreate that issue..

Video: https://streamable.com/8bjm34

```lua
function init()
  POS = Vec()
  TPOS = Vec()
  DIR = Vec(0, -1, 0)
  DIST = 1000
end

function tick(dt)
  POS = VecLerp(POS, TPOS, 0.01)

  -- just to make it move to new point
  if InputPressed("l") then
    local t = GetCameraTransform()
    local dir = TransformToParentVec(t, Vec(0, 0, -1))
    local hit, dist, normal, shape = QueryRaycast(t.pos, dir, 1000)
    if hit then
      local hitpoint = VecAdd(t.pos, VecScale(dir, dist))
      TPOS = hitpoint
    end
  end

  -- the actual line
  local startPoint = VecAdd(POS, Vec(0, 100, 0))
  local hit, dist = QueryRaycast(startPoint, DIR, DIST)
  if hit then
    local hitPoint = VecAdd(startPoint, VecScale(DIR, dist))
    local maxPoint = VecAdd(startPoint, VecScale(DIR, DIST))
    DebugLine(startPoint, hitPoint, 1, 0, 0)
    PointLight(hitPoint, 0, 1, 0, 3.0)
    DebugLine(hitPoint, maxPoint, 0, 1, 0)
  end
end

```

**Comment by YuLun-bili** [comment]
@TMCAtom Viewing your attached video and guess how did you write that part of code cannot make this issue more clear. Send the section of script that's doing this instead would massively help us

**Comment by TMCAtom** [comment]
im guessing it might be related to the laser moving, which doesnt really make sense considering its just changing some of the input variables.
[heres a link to the mod used in the video](https://github.com/user-attachments/files/17234500/Global_Mod_1.zip)

**Comment by nooitaf** [comment]
It's probably some issue with the `laserDir` or `laserorigin` calculation, as it's not happening when you are standing on the ground when appointing a new target position.

**Comment by TMCAtom** [comment]
i do think its weird that it doesnt happen when youre on the ground, it really shoudnt change anything considering it never checks for that

**Comment by Thomasims** [comment]
It seems `laserDir` can get a length of less than 1 in the code you provided. I know for a fact that raycasts don't behave correctly when the length is greater than 1 but seeing as the function expects a normalized vector I wouldn't be surprised if this incorrect behavior also applied to vectors that are too small.

**Comment by TMCAtom** [comment]
so the issue is effectively being caused by the game being unable to properly handle low values?

**Comment by Thomasims** [comment]
No it's caused by improperly using the raycast function. Always make sure to normalize the direction vector.

**Comment by TMCAtom** [comment]
i feel like it should state that in the modding documentation since i dont find it intuitive that you have to sort of go through an unlisted requirement, especially because its not immediately obvious that it doesnt work properly. either way, thanks for helping.

**Comment by Thomasims** [comment]
The documentation does state that it has to be a normalized vector:
> direction (TVec) – **Unit length** raycast direction as world space vector

Anyway I believe this resolves the issue, feel free to reopen otherwise.
