### ISSUE TITLE
[Feature] add a feature so that you can insert scripts into triggers

### ISSUE THREAD

**Issue by ZhylevarYTRUS** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#647]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I think this feature should be added, because its very good for those who want to make a trigger to activate an alarm.

### Describe the solution you'd like

do something like trigger parameters: sound, sound ramp, script file.

### Describe alternatives you've considered

i think to type some big scripts, but im am not a scripter guy.

### Additional context

**Comment by Thomasims** [comment]
There's nothing special you could do with a trigger/script combination that you can't already do with a script wrapping a trigger.
I suggest you learn scripting first before suggesting stuff like this. Read through the #modding-tutorials-and-info channel on the discord, that'll give you at least a basic understanding of how Teardown scripting works.

**Comment by Zhylerchiks** [comment]
sure i guess?
