### ISSUE TITLE
[Bug] Wheels sink into the ground if put in a seperate body from the main vehicle

### ISSUE THREAD

**Issue by DimasVoxel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#65]
### Describe the bug

If you put a wheel into a body which is outside of the main body for the vehicle, it will fall through the ground.
Video showing this phenomenon: https://imgur.com/a/pgq6xbW

Vehicle on red slabs show how it currently behaves, cars on green slab shows the desired result.

Note: cars on the green slab don't have the wheel tag, making the wheel normal shapes

_Watch video before proceeding_
Red slab editor setup: 
![image](https://user-images.githubusercontent.com/62283566/140930799-5b2d0141-db0d-46c5-aa54-18910717fc61.png)

Green slab editor setup: 
![image](https://user-images.githubusercontent.com/62283566/140930861-3491b700-c61c-4fb9-b3ad-6498e55bfcfd.png)

The Level itself: 
[Suspension Test.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/7504961/Suspension.Test.zip)

Why would you even want have wheels to be in a body? 
To make more complicated suspension setups for crawlers for example.

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/62283566/140931153-6b4cfea6-0350-4cf4-af37-6d355d42c568.png)

Have the following setup:
![image](https://user-images.githubusercontent.com/62283566/140931364-bc5dd5f9-8184-42eb-bab1-45e70957e17f.png)

This exact setup is also provided in the suspension test level:
[Suspension Test.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/7504968/Suspension.Test.zip)
 

### Expected behavior

https://imgur.com/a/pgq6xbW

Red: Current behavior

Green: Expected behavior 

### Environment

- Teardown Version 0.8.0
- OS: Windows 10
- GPU: 2060 6GB
- Graphics driver version: 471.41
- CPU: Ryzen 7 3700x

**Comment by tuxedolabs** [comment]
I think the wheels behave correct (a similar setup is used on the semitruck, for instance), but the physics engine in the game is not designed for setups like this, where there complex chains of joints between bodies with large mass ratios. It would require a far more advanced solver to work as expected.
