### ISSUE TITLE
[Bug] Nitroglycerin can attain the indestructible property when placed on SOME indestructible objects

### ISSUE THREAD

**Issue by MisterSirCode** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#66]
### Describe the bug

It seems that occasionally (On Specific Objects) nitroglycerin can stick to indestructible objects and keep the properties of them, making it unable to be destroyed. (it doesn't blow up)

Things like Laser Reflectors and Vault doors in specific missions have this problem

[Video of the issue](https://i.imgur.com/MlnwPLB.mp4)

As you could see in the video, I blew this laser reflector sky high, but the nitroglycerin on it wasn't affected.

![Image](https://i.imgur.com/RQPrkpx.png)

PS: I've noticed this doesn't happen with all indestructible objects, Mostly laser reflectors or vault doors. I tried the unbreakable bunker door in the hub and that one was unaffected.

### Steps to reproduce the behavior

1. Go to "The Droid Abduction" mission.
2. Find the laser reflectors in the lower brick storage building with the droid in it.
3. Try to destroy one with nitroglycerin by directly placing it on it.
4. Voila

### Expected behavior

Even if the object is indestructible, the nitroglycerin should still blow up

### Environment

- Teardown Version: 0.9.0
- OS: Windows 11
- GPU: NVidia RTX 2070 Super
- Graphics driver version: NVIDIA Studio Driver 472.39
- CPU: AMD Ryzen 7 2700 X

### Additional context

Also, possibly unrelated, this issue also existed for the bomb at one point, and now no longer does.

**Comment by tuxedolabs** [comment]
This is a known issue and I'm investigation the best way to solve this. Nitroglycerin is added as a shape to the body it's attached to, and if that body has "unbreakable" tag, it will include the nitro shape as well.  I probably need to add a flag to override unbreakable bodies, or simply convert unbreakable bodies to unbreakble shapes at load time.

**Comment by CoolJWB** [comment]
This was fixed in 0.9.1, thanks for the feedback!
