### ISSUE TITLE
[Bug] Nitroglycerin will lose its emissive property while placed on a vehicle / light and the lights turn off.

### ISSUE THREAD

**Issue by MisterSirCode** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#67]
### Describe the bug

Nitroglycerin will lose its emissive property with a light fixture or vehicle light that is turned off, additionally it also turns back on alongside the light.

[Video of the issue](https://i.imgur.com/JRKXDgP.mp4)

### Steps to reproduce the behavior

1. Go to any vehicle with scripted lights, say, the cars in the campaign hub.
2. Place some nitroglycerin on the vehicle.
3. Drive, then exit the car. The car lights and nitroglycerin will be turned off like a light.

### Expected behavior

It should keep its emissive properties.

### Environment

- Teardown Version: 0.9.0
- OS: Windows 11
- GPU: NVIDIA RTX 2070 Super
- Graphics driver version: 472.47
- CPU: AMD Ryzen 7 2700 X

**Comment by tuxedolabs** [comment]
Thanks, I fixed this for 0.9.1
