### ISSUE TITLE
[Bug] The two width and height arguments from UiImageButton() don't do anything

### ISSUE THREAD

**Issue by CatJet** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#69]
### Describe the bug

I was trying to make an UiImageButton using an image with the size 360x200 and tried to set the optional width and height arguments to 180 and 100, to halve the image in size:

`UiImageButton("img.png", 180, 100)`

Despite that, the button took the size of 360x200 instead of 180x100.
This happened with any other number I've tried, like 0.5 or 2.

### Steps to reproduce the behavior

1. Make a script upon which you can call UI functions
2. Use the UiImageButton() function somewhere with an image set in the first argument and a size that isn't that of the source image set to the two [w] and [h] arguments
(3. Observe how the function denies your demand)

### Expected behavior

The image is supposed to be scaled according to the width and height listed in the arguments

### Environment

- Teardown Version 0.9.0
- OS: Linux
- GPU: Mesa Intel UHD Graphics 630
- Graphics driver version: 05
- CPU: Intel Core i5-10400 CPU @ 2.90GHz

### Additional context

I've also spotted another user (micro#2070) on the official Discord server once asking why this same issue occurred to him in #modding-discussion during May of this year. (I searched for UiImageButton() in #modding-discussion)

**Comment by tuxedolabs** [comment]
Documentation bug, there is only one parameter to that function. Fixed in 0.9.1. Thanks!
