### ISSUE TITLE
[Bug] Water artifacts on medium and low render quality

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#75]
### Describe the bug

Water artifacts on medium and low render quality

Low:
![Screenshot from 2021-12-21 14-27-34](https://user-images.githubusercontent.com/1898194/146938003-f569961b-c9ff-4b6d-b41b-80b1ed333403.png)

High:
![Screenshot from 2021-12-21 14-27-50](https://user-images.githubusercontent.com/1898194/146938047-28572b2c-8c5e-4af2-b1f4-78b86db82b27.png)

---
Low:
![Screenshot from 2021-12-21 14-27-07](https://user-images.githubusercontent.com/1898194/146938093-300de648-3d73-4928-81bc-188a6fe35c7d.png)

Medium:
![Screenshot from 2021-12-21 14-26-43](https://user-images.githubusercontent.com/1898194/146938153-91bcc68f-6360-48cc-b1bd-5dda62c5b56f.png)

High:
![Screenshot from 2021-12-21 14-26-20](https://user-images.githubusercontent.com/1898194/146938174-f92d2cf5-f292-429c-bca1-d08c8bfa4d96.png)

### Steps to reproduce the behavior

1. Go to Marina
2. Look at water (around the bridge)
3. Change Render Quality
4. See artifact

### Expected behavior

No artifact

### Environment

- Teardown Version 0.9.2_1
- OS: Linux
- GPU: gtx970
- Graphics driver version: 470.86
- CPU: i5

**Comment by RoverBot-Dev** [comment]
I think its because the reflections are lower quality on the lower settings

**Comment by tuxedolabs** [comment]
By design. Lower quality -> more artefacts
