### ISSUE TITLE
[Bug] Special characters in register tokens/property names.

### ISSUE THREAD

**Issue by EldinZenderink** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#76]
### Describe the bug

In pre 0.9.x versions I was able to store registers with special characters such as '&' in it's name and retrieve the content after a full restart of the game, but since this version it has changed. Now it is on myself that I used special chars in the first place (stupid, shouldn't have been lazy). But if this is an expected improvement to the API instead of a bug, I would like to see some checking of register names within Lua (e.g. throwing an error) or at least mentioning in the documentation what is and is not allowed in the register names. 

Oddly enough, while in-game, it does remember the values set in the registers with the special character, but it is never stored to the save game. Thus after a full restart, the value is gone.

Demonstration code:

    test = false
    function tick(dt)
        if test == false then
            DebugPrint("special chars register before set: " .. GetString("savegame.mod.special&charsdontwork"))
            SetString("savegame.mod.special&charsdontwork", "This used to work in older versions")
            DebugPrint("special chars register after set: " .. GetString("savegame.mod.special&charsdontwork")) 
        

            DebugPrint("nonspecial chars register before set: " .. GetString("savegame.mod.nonspecialcharswork"))
            SetString("savegame.mod.nonspecialcharswork", "This works as expected")
            DebugPrint("nonspecial chars register after set: " .. GetString("savegame.mod.nonspecialcharswork"))    

            test = true
        end
    end

### Steps to reproduce the behavior

1. Create a basic mod with the mentioned demonstration code.
2. Load a map of choice
3. See the debug messages (first time it will only print the "after set" messages with the expected value.
4. Restart the map (now both before and after set debug messages for BOTH registers print the expected value)
5. Fully close teardown 
6. Start teardown
7. Load a map of choice
8. Now the register with the special character does not contain a value before the set, the register without the special character does show the properly stored value.

### Expected behavior

1. Like previous versions (to allow compatibility within mods) it should work with these kind of characters in the token/property name of a register.
2. Register token/name checking by the SetX functions to raise an error whenever a invalid name is provided for a token/property
3. Clarification in the modding documentation.

### Environment

- Teardown Version [0.9.2 (patch 1)]
- OS: Windows
- GPU: RTX 2080s
- Graphics driver version: 496.49
- CPU: Ryzen 5  5600X

**Comment by CoolJWB** [comment]
I think this was one of the reasons why people's savegame was reset, it has later been patched.
But I agree that an error could be thrown (or a note in API documentation).

**Comment by tuxedolabs** [comment]
Williams comment is correct. Only alphanumeric characters are allowed in savegame registry key names. I will add this to the documentation.
