### ISSUE TITLE
[Feature] Allow more control over lights and shape emissive scale

### ISSUE THREAD

**Issue by Artzert2215** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#77]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

While developing mods, I've ran into a certain issue multiple times now, where I want to manipulate lights / the emissive scale of a shape. (Car alarm / Re-enable destroyed lights)
The game restricts access to vehicle lights and emissive scale, and to lights that are disconnected from a static body / destroyed.
I would want to be able to control these lights and shapes to be able to create mods. (like car alarms and leaving lights on when a player exits the car).

### Describe the solution you'd like

Remove restriction from these lights / shapes. (or stop forcing them to a certain value / state).

### Describe alternatives you've considered

There is no real alternative to this.

**Comment by tuxedolabs** [comment]
Vehicle lights are treated in a special way internally (specific material indices for different function, break lights, etc) that unfortunately conflicts with the generic lua API. There are no plans for more specific lua functions at this point.
