### ISSUE TITLE
[Feature] Render sprites in photo mode

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#78]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Currently all sprites get hidden in photomode. It would be nice if there would be a way to make them visible.
(iirc, there was some communication on discord, just putting this here for reference)

In Game:
![image](https://user-images.githubusercontent.com/1898194/148120388-bffe2cc1-c0c3-43e2-8843-546d24b2d76f.png)

Photo mode:
![image](https://user-images.githubusercontent.com/1898194/148120820-df81e57c-4e5f-42ee-918e-9c2af8ab56c2.png)

### Describe the solution you'd like

It would be nice if there would be a way to make them visible.

### Describe alternatives you've considered

Particles are an alternative, but in lots of cases not practical or (in the case of the flowers for example) impossible.

**Comment by tuxedolabs** [comment]
Fixed in next version. Thanks!
