### ISSUE TITLE
[Feature] Know if MakeHole() succeeded

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#79]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

I want to check if a MakeHole() call actually did destroy something (maybe it had no effect because radius was too small or meterials were too hard).

### Describe the solution you'd like

Make MakeHole() return the number of voxels destroyed by it, and maybe the shapes impacted as well. Only makes sense if this information is already available internally in this function, the point being to avoid having to call query functions after a MakeHolde() to determine if something was destroyed succesfully.

### Describe alternatives you've considered

The alternative way I used so far is to run a QueryClosestPoint() at the location where I will attempt to MakeHole() then run the same QueryClosestPoint() right after to check if the point found is different. This seems pretty sub-optimal, especially if multiple MakeHoles() can happen every tick...

### Additional context

Question originally posted as a [Steam discussion](https://steamcommunity.com/app/1167630/discussions/0/3198117312275464347), before I was made aware of this issue tracker. Use case for it can be found in the [Hungry Slimes](https://steamcommunity.com/sharedfiles/filedetails/?id=2695893023) mod.

**Comment by EldinZenderink** [comment]
As another alternate solution you could use `GetShapeMaterialAtPosition`  on the shape and location of the first queryclosestpoint returned after make hole, which returns an empty string if no material is found, e.g. no voxel was present at the location, which is faster than another queryclosestpoint i believe, correct me if I am wrong.  Just my 2 cents.

**Comment by FlorentP42** [comment]
Sadly that would not be enough: I am making a hole that can touch several shapes and bodies, and I want test if "any" of the items in the area broke, only testing if the "center" broke is not enough because that could be unbreakable material, shile brekable material around it did break. Note that my current solution, still fails to detect that case.

**Comment by tuxedolabs** [comment]
Good suggestion. Added a return value to MakeHole, returning the aggregate number of voxels cut out by this operation. Available in 0.9.3
