### ISSUE TITLE
[Feature] Add option to open mod folder from the mod manager menu

### ISSUE THREAD

**Issue by ss-gnalvesteffer** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#8]
**Is your feature request related to a problem? Please describe.**
When I create a new mod or want to view an existing mod's directory, I have to manually go to that directory myself via Windows' File Explorer. This can be tedious.

**Describe the solution you'd like**
It would be nice to be able to open the mod's folder from within the mod manager menu, perhaps via an "Open Folder" button like so:
![image](https://user-images.githubusercontent.com/25854043/111366213-38555c00-8661-11eb-8c1d-0cab0e88b431.png)

**Comment by tuxedolabs** [comment]
There is actually a link below the details box that does exactly this.
