### ISSUE TITLE
[Feature] Ignore unbreakable bodies/shapes/materials in queries

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#80]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

May have several uses but the most important I see right now would be to find the closest breakable material to a point (and avoid attempting to MakeHole() in unbreakable materials that will obviously fail).

### Describe the solution you'd like

Add a QueryRejectTag() and a QueryRejectMaterial() functions.

### Describe alternatives you've considered

Didn't find any, for now find closest shape and try to MakeHole() in it, but this may fail if it's unbreakable...

### Additional context

Question originally posted as a [Steam discussion](https://steamcommunity.com/app/1167630/discussions/0/3198117312275464347), before I was made aware of this issue tracker. Use case for it can be found in the [Hungry Slimes](https://steamcommunity.com/sharedfiles/filedetails/?id=2695893023) mod.

**Comment by tuxedolabs** [comment]
I can see the problem, but I don't think this should be part of reject. For these special cases, use QueryAabbShapes and go over them manually with GetShapeClosestPoint and GetShapeMaterialAtIndex

**Comment by FlorentP42** [comment]
@tuxedolabs Wait, this would mean for each shape found, go over every single voxel of that shape and find the closest one that does not include the "rejected materials" right?
This sounds like an insanely slow process to do from script, especially if you consider the static shape that is the floor of the whole map for example, or a very large amount of shapes.
Which is why I was thinking this could maybe be achieved way more efficiently through new QueryReject() functions, am I wrong on this assumption?
