### ISSUE TITLE
[Feature] Ability so store/load arrays in the registry

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#81]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Just for convenience, being able to save an complete lua array as one registry value would help, especially for vectors.

### Describe the solution you'd like

Add GetArray()/SetArray() to the registry (would work for vectors too).

### Describe alternatives you've considered

Storing each array element with a different registry key. but that does not feel right for large arrays.

### Additional context

Question originally posted as a [Steam discussion](https://steamcommunity.com/app/1167630/discussions/0/3198117312275464347), before I was made aware of this issue tracker.

**Comment by tuxedolabs** [comment]
You can already do this for a for loop, but the registry is not intended to store large amounts of data.
