### ISSUE TITLE
[Feature] Add a way to detect if one particular voxel of a shape was removed

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#82]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

For some context here is what I am trying to do: I want to stick an object (non physical, just a position represented by a particle effect) to a shape. The shape could be any shape present in the game world, not a predefined one.
In order to do that I use QueryClosestPoint() to find the closest point that will be my attachment point, and store the offset between that point and the shape center to move my object "as if it was sticked to that position".
Problem comes when I have to detect if the voxel I am "attached" to did break. I would like a solution that allow to test for the existence of that voxel without doing any trace, for performance reasons.

### Describe the solution you'd like

Add a vec = GetIndexAtPosition(shape, Vec(x, y, z)) that would take a world coordinate at the time of the call and return the shape-relative coordinate would do the trick.

The idea behind this is: at the instant when the object does stick to the shape, store the index of the voxel we are sticking to (x, y , z in shape-relative coordinates). Then every tick call GetShapeMaterialAtIndex() with this index (that should be instantaneous access to an array element, no trace here) and check if the material does not exist any more (type == ""), if it does, admit the voxel was destroyed, and process in consequence.

### Describe alternatives you've considered

The solution I came up with so far is to check if GetShapeVoxelCount() changed since last tick, and if it did to detach my object and call QueryClosestPoint() again to find a new attachment point. Problem is that this is very ineffective as the voxel count may have lowered but the voxel I stick to still be there.

I also considered the addition of a FindVoxelAt(Vec(x, y, z)) function that would return a handle to a single voxel at the given coordinates or nil if none found. This combined with IsHandleValid() would allow to efficiently detect when a given voxel broke. But after discussion this on the steam discussion below, I came to the conclusion that it would not be reasonable to implement.

### Additional context

Question originally posted as a [Steam discussion](https://steamcommunity.com/app/1167630/discussions/0/3198117312275464347), before I was made aware of this issue tracker. Use case for it can be found in the [Hungry Slimes](https://steamcommunity.com/sharedfiles/filedetails/?id=2695893023) mod.

**Comment by CoolJWB** [comment]
Would [GetShapeMaterialAtIndex](https://teardowngame.com/experimental/api.html#GetShapeMaterialAtIndex) work?

**Comment by FlorentP42** [comment]
That's my point ^^ I can't math hard enough to get the local coordinate value to give to GetShapeMaterialAtIndex() based on a world coordinate point :p
Unless this is what TransformToLocalPoint() does already? But I'm pretty sure that would return a floating vector when GetShapeMaterialAtIndex() expect an integer vector that represent one particular voxel, not a point in space.

**Comment by FlorentP42** [comment]
So yeah, I just tried with TransformToLocalPoint() to get the "index", but as I feared these coordinates seems unrelated :/ It sometimes ends up returning the correct material (probably by luck because some voxel with the same material happen to match those coordinates), but most of the time it just returns empty material -_-

So either these two coordinates systems are completely unrelated, or I am missing some key factor to get the correct "index" coordinates... If this is even achievable with the current API, any help will be appreciated, else hopefully the new function can be added to solve this issue once and for all ;)

**Comment by FlorentP42** [comment]
The discussions on issue #98 led me to a solution for that one as well:
```
function GetVoxelIndex(shape, pos)
    local xsize, ysize, zsize, scale = GetShapeSize(shape)
    local tr = GetShapeWorldTransform(shape)
    local index = TransformToLocalPoint(tr, pos)
    return Vec(math.floor(index[1]/scale), math.floor(index[2]/scale), math.floor(index[3]/scale))
end
```
So yeah, either close this issue or consider adding something similar to the API to make the task of other modders easier ^^
