### ISSUE TITLE
[Feature] Add a way to get true FPS

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#83]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Right now GetTime() and GetTimeStep() are capped at 30 FPS, meaning the delta between two calls will never be more than 1/30, making it impossible to detect from script when the game is running very slow and the actual framerate is lower than 30 FPS. Thus making it impossible to adapt a script accordingly.

### Describe the solution you'd like

Either fix GetTime() and GetTimeStep() to return true FPS, or add another API function that would return actual system time with high enough precision, so that we can compute actual FPS even when the game runs slow.

### Describe alternatives you've considered

No workaround I could find

### Additional context

Question originally posted as a [Steam discussion](https://steamcommunity.com/app/1167630/discussions/0/3198117312275464347), before I was made aware of this issue tracker. Use case for it can be found in the [Hungry Slimes](https://steamcommunity.com/sharedfiles/filedetails/?id=2695893023) mod.

**Comment by tuxedolabs** [comment]
I can see the problem, but it is designed like this for a reason. An uncapped timer would be problematic if the player alt-tabs out of the game, pauses the game, etc. For the example provided I'd say you should use a timer capped to 30 FPS, since it it then aligned with the in-game time.

**Comment by FlorentP42** [comment]
@tuxedolabs I understand that changing the existing way time is distributed to tick() and delay() functions would not be a viable option. Yet could you please consider adding a separate function to get true system time elapsed?
I understand this could be dangerous to use as a time reference for the alt-tab/pause cases you mentioned, and could sometimes throw aberrant values after such events, and it may result in some unwanted behaviour (insane FPS drop) in those cases, being able to accurately detect lag in all other cases seems way more important than those potential failing cases. Plus those aberrant values can probably be filtered out through code.

**Comment by YuLun-bili** [comment]
`GetFps()` since 1.5.4 :P

**Comment by FlorentP42** [comment]
According to the description I fear that this would still rely on `GetTimeStep()` internally, which does not satisfy the above requirements :/

**Comment by YuLun-bili** [comment]
well
<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/f47c0e4c-8bda-453d-9cb9-f5e053869470" width="640px">

**Comment by FlorentP42** [comment]
Awesome, once it's out I will finally be able to patch my very first mod with this XD
