### ISSUE TITLE
[Feature] Prismatic (or other) joint acceleration option for smoother movement

### ISSUE THREAD

**Issue by funpeople** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#84]
### There is currently no way to make smooth movement for prismatic joints (see video) with SetJointMotorTarget (unless you want to code really hard and calculate when the joint must slow down or speed up).

If you wanted to make an elevator, for an example, you wouldn't be able to make it move smoothly (Acceleration=0.5, see video), it would always be sharp when starting/stopping moving (No smoothing). An alternative to that would be setting the strength a lower value, but that would make your elevator weak and it would still be sharp when stopping, which isn't perfect.

https://user-images.githubusercontent.com/97744205/149540436-8a78cbaf-e757-4bae-820a-55ec1ac3ec12.mp4

### A solution for that would be a new argument for function SetJointMotorTarget():

`acceleration (number, optional)`

This is pretty much self-explanatory: the default is infinite; when set to a lower value, the prismatic joint will slowly speed up when it starts it's movement, and slow down when it is about to stop. 

See the video attachment above where the maxVel for all variants is 1 and the distance between stops is 2.

### Describe alternatives you've considered

None

**Comment by CoolJWB** [comment]
Just remembered, would [SetValue](https://teardowngame.com/modding/api.html#SetValue) maybe work for this or did I misunderstand the issue?

**Comment by funpeople** [comment]
> Just remembered, would [SetValue](https://teardowngame.com/modding/api.html#SetValue) maybe work for this or did I misunderstand the issue?

It would still be very complicated at the stopping part, as it would require you to calculate when the joint is about to stop for it to work.

**Comment by tuxedolabs** [comment]
I think this is better implemented in script since it's not entirely clear what the api should look like.
