### ISSUE TITLE
[Bug] Weird Vehicle Camera Behavior

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#85]
### Describe the bug

when the camera location and the player location for a vehicle is placed far enough, it is obvious to notice that the third person camera will spin very weirdly, as the camera do not move at a consistent rate

### Steps to reproduce the behavior

1. Go to any vehicle inside the editor (or the US semi, which already have a camera location)
2. add a new location like how a player location is added
3. put tag camera in there
4. and place it far away from the player location
5. now load the level, and get on said vehicle
6. spin the camera, carefully observe the oddness when spinning the camera (maybe easier to tell with a controller), and zooms in and out even when not touching the scroll wheel 

### Expected behavior

act normal i guess

### Environment

- Version: 0.9.2 (patch 1)
- OS: Windows 10
- GPU: 
- Graphics driver version:
- CPU:

### Additional context

re-submit from discord since its archived

**Comment by tuxedolabs** [comment]
Not intended to be placed far from player location, just minor adjustment

**Comment by Please-Pick-a-Name** [comment]
> Not intended to be placed far from player location, just minor adjustment

I'd imagine having this fixed would be a good idea... I can immediately think of one thing that this will be heavily used at: buses. it would really be awkward having the camera be focused at the corner of the bus, or having the camera go in and out when spinning the camera for some perhaps cinematic views

**Comment by Please-Pick-a-Name** [comment]
nvm, u guys straight up removed it

**Comment by Please-Pick-a-Name** [comment]
bruh, now the camera location doesnt work at all
