### ISSUE TITLE
[Bug] Broken PlayMusic in Woonder Land

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#86]
### Describe the bug

PlayMusic doenst work as intended in Woonder Land, the music doesnt play unless in the pause menu, and very occasionally glitch into reality during normal gameplay, but just sounds like the audio is dieing

### Steps to reproduce the behavior

1. Make new global mod that uses PlayMusic (any music, i tested the issue with music located in the game file)
2. Go to any map except Woonder Land (i didnt test in every map)
3. Hear music
4. Go to Woonder Land in campaign (but enough to know that woonderland is funny)
5. No music

### Expected behavior

Hear music

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU: 

### Additional context

again, recycled from discord

**Comment by tuxedolabs** [comment]
This level mutes level music by design
