### ISSUE TITLE
[Bug] Incorrect Tank Light Placement

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#88]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/149582462-d543c659-6843-41d5-9334-957b1f568e61.png)
misplaced tank lights, seems to be off by 3, 4 voxel for all of them

### Steps to reproduce the behavior

1. Go to any map with tank
2. Get in
3. Light does not shine from the light voxel, nor reacting to the on/off of the light voxel, and shuts off even if the lights are fine when vehicle is slightly damaged, which will also cause it to play the broken light sound effects every time when you get into the tank

### Expected behavior

proper light placement

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

### Additional context

Recycled from discord, again, and note, i did check it in the newest available verison that it still exists, for all the error i have reported

**Comment by tuxedolabs** [comment]
Fixed in 0.9.3
