### ISSUE TITLE
[Bug] Unable to set FOV to certain values

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#89]
### Describe the bug

when trying to set the fov in options to certain value, it will drop down by 1, sometimes 2

### Steps to reproduce the behavior

1. Go to Options-graphics
2. Try to set FOV to 89, 86, 83, 80, 79, 76, 73, 70... and a lot more value
3. Does not stay

### Expected behavior

stay

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

### Additional context

recycled from discord, ancient

**Comment by tuxedolabs** [comment]
Too minor to fix (value is truncated by design)

**Comment by Please-Pick-a-Name** [comment]
> Too minor to fix (value is truncated by design)

I mean i know that it is supposed to be rounded to the nearest integer, but I dont think by design you are not supposed to use like over one third of the possible integer numbers
Plus all you need is to add a 0.5 inside the math.floor line, so like:
`function optionsSlider(setting, def, mi, ma)
	UiColor(1,1,0.5)
	UiPush()
		UiTranslate(0, -8)
		local val = GetInt(setting)
		val = (val-mi) / (ma-mi)
		local w = 100
		UiRect(w, 3)
		UiAlign("center middle")
		val = UiSlider("common/dot.png", "x", val*w, 0, w) / w
		_val = math.floor(val*(ma-mi)+mi+**0.5**)_
		SetInt(setting, val)
	UiPop()
	return val
end`
and it will now work
