### ISSUE TITLE
[Feature] Change log of updated mods you are subscribed to.

### ISSUE THREAD

**Issue by ghost** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#9]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem.

**Describe the solution you'd like**
To have a small notification area in teardown where it will pull data from the change log area from any mods/maps that you are subscribed to. It will have like a little white dot meaning there are new notifications. This is very useful as you will be able to know what new updates were released, for which mods, what date/time, and what is new in the update.
**Describe alternatives you've considered**
A notification area in the workshop page.
**Additional context**
None

**Comment by CoolJWB** [comment]
I would say this is sort of similar to the bold text now visible over mods.
