### ISSUE TITLE
[Feature] Add a way to make particle go precisely from point A to point B

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#90]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Right now the only thing you cannot do with a particle is to set a precise end location for its motion.

### Describe the solution you'd like

Add a ParticleTarget(target, [v1], [interpolation], [fadein], [fadeout]) function
That would ensure the particle aims for "target" location after being spawned, dissapearing when either target or lifetime is reached.
The "v1" and other optionnal parameters would also make it possible to interpolate on the velocity along the trajectory.

### Describe alternatives you've considered

Right now the only way to achieve that is to attempt to give the particle the perfect initial velocity + lifetime to make it dissapear right at the target location, which is somehow manageable with a constant speed, but would certainly be a nightmare with variable velocity...

Here is a code sample for fixed speed:
```
local targetPos = Vec(1, 2, 3)
local spawnPos = Vec(4, 5, 6)
local trajectory = VecSub(targetPos, spawnPos)
local speed = 42
local velocity = VecScale(VecNormalize(trajectory), speed)
local lifetime = VecLength(trajectory) * 1 / speed
SpawnParticle(spawnPos, velocity, lifetime)
```

**Comment by tuxedolabs** [comment]
Not sure about the use case. Can be solved with math!
