### ISSUE TITLE
[Bug] Sounds longer than 2 minutes crash on Linux

### ISSUE THREAD

**Issue by Thomasims** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#91]
### Describe the bug

Calling `LoadSound` or `LoadLoop` on a sound file longer than 2 minutes crashes the game under Linux.

### Steps to reproduce the behavior

1. Download and install: [loadsoundcrash.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/7876199/loadsoundcrash.zip)
2. Play the level.

### Expected behavior

The game should load the sound correctly.

### Environment

- Teardown Version 0.9.2
- OS: Linux (Manjaro 5.10.89-1, KDE Plasma 5.23.4)
- Proton Version: Experimental
- GPU: NVIDIA GeForce GTX 960
- Graphics driver version: 495.44
- CPU: Intel i7-6700K

### Additional context

This does not happen with `PlayMusic`

**Comment by tuxedolabs** [comment]
Linux not supported (and those functions are not designed to handle that long sound files)

**Comment by Thomasims** [comment]
I understand Linux is not supported now, but aren't you trying to get the game at least stable for the Steam Deck?
I made the `type/linux` label specifically for that purpose, to track issues that cause repeatable instability under Proton if that compatibility became relevant at some point.
