### ISSUE TITLE
[Bug] High Preassure Boiler

### ISSUE THREAD

**Issue by leosefcik** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#92]
### Describe the bug

When looking at the high pressure boiler, it has a typo saying "High preassure boiler - Target"

https://cdn.discordapp.com/attachments/337661151816974348/932688244326432878/IMG_1941.jpg (couldn't get a screenshot sorry for the bad quality)

### Steps to reproduce the behavior

1. Play the mission where you have to destroy the targets on the tropical islands with the helicopter attacking you
2. Go to the target that is closest to the escape ship
3. Look at the target

### Expected behavior

Read "High pressure boiler - Target"

### Environment

- Teardown Version 0.9.2 (patch 1)
- OS: Windows

**Comment by tuxedolabs** [comment]
Already fixed. Thanks!
