### ISSUE TITLE
[Bug] Broken Alarm Box on Marina Hunted Challenge

### ISSUE THREAD

**Issue by bingleboy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#93]
### Describe the bug

While in the Hunted challenge for the Marina, on the west side of the map in the container labeled "Bob's Construction Company" there is an unused alarm box that blinks but has nothing attached to it
![2022-01-17-14-10-19](https://user-images.githubusercontent.com/85895661/149826572-24401153-c898-406b-a90c-71c0ecc1a05a.png)
.

### Steps to reproduce the behavior

1. Go to the Hunted challenge for the Marina
2. Travel to the blue container labeled "Bob's Construction Company" and go inside
3. See error
![image](https://user-images.githubusercontent.com/85895661/149826932-d4074d2b-472d-4000-b0ee-bac39b991e71.png)

### Expected behavior

There should not be an alarm box inside the container

### Environment

- Teardown Version 0.9.2 (patch 1)
- OS: Windows
Hardware info doesn't seem important as it is an issue with the level

**Comment by Hallonduell** [comment]
Fixed in next release.
