### ISSUE TITLE
[Bug] Misplaced Vehicle lights, again

### ISSUE THREAD

**Issue by 349767970** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#94]
### Describe the bug

![image](https://user-images.githubusercontent.com/92796946/149863656-94a79b97-2230-435a-b886-05a22e8185d6.png)
it seems that all the rear lights are shifted a couple voxel upward again, but only for the rear lights

### Steps to reproduce the behavior

1. Go to hub
2. Get in the new LTS van
3. See error

### Expected behavior

Proper Light placement and action

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by Hallonduell** [comment]
Fixed in next release.
