### ISSUE TITLE
[Bug] Misplaced wheel

### ISSUE THREAD

**Issue by 349767970** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#95]
### Describe the bug

![image](https://user-images.githubusercontent.com/92796946/149864540-a5ee2987-3c80-448d-97eb-96d341289152.png)
well this is obvious enough

### Steps to reproduce the behavior

1. Find monster truck
2. See misplaced wheel

### Expected behavior

not misplaced wheel

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Fixed. Thanks!
