### ISSUE TITLE
[Bug] ANOTHER misplaced wheel

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#96]
### Describe the bug

![image](https://user-images.githubusercontent.com/81009804/149865281-62320850-000f-428e-bfa4-0efbb42c9785.png)
![image](https://user-images.githubusercontent.com/81009804/149865300-2d48ebb2-edd5-4796-a17d-65e84ede46a8.png)
(i was on the wrong account reeeeee)

### Steps to reproduce the behavior

1. Go to heavy mobile industrial crane
2. See error on wheels

### Expected behavior

correct wheel placement

### Environment

- Teardown Version: 0.9.2 (patch 1)
- OS: Windows
- GPU:
- Graphics driver version:
- CPU:

**Comment by tuxedolabs** [comment]
Too minor to fix
