### ISSUE TITLE
[Feature] Add a way to get non axis-aligned bounding box

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#98]
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

When computing collisions manually, most of the time the regular axis-aligned bounding box returned by GetBodyBounds() / GetShapeBounds() is all you need. But in some cases getting a non axis-aligned bounding box would give more precise results (eg: to test if bbox is contained inside a sphere).

White: What I have
Green: What I want
![image](https://user-images.githubusercontent.com/45787476/150631823-bc90a564-5a7c-468e-ac07-ad1e80cd144a.png)

### Describe the solution you'd like

Add GetBodyLocalBounds() / GetShapeLocalBounds() functions that would return a list containing the 8 corners of the non axis-aligned bounding box: {Vec(), Vec(), Vec(), Vec(), Vec(), Vec(), Vec(), Vec()}

Unless there is some more synthetic way to convey this information? Using a center point, rotation and one corner should be enough, but I'm not sure how to compute the position of the 7 other corners from there...

### Describe alternatives you've considered

So far the only alternative is to use regular bounding boxes.

If there is a way to compute the corners position of this non axis-aligned bbox with the current API, please let me know :)

**Comment by Thomasims** [comment]
I'm not entirely sure what purpose this would serve that's not already done better using other methods?

Neither the AABB nor a new OBB would be suited to detect final collision since you can still have massive gaps in the shape, their only use here is as a first filter pass and in that domain I would typically pick the AABB since it's easier and faster to check against.

If you still want the OBB of a shape, you can simply use a combination of `GetShapeWorldTransform` and `GetShapeSize`, it's fairly straight-forward though not very useful beyond simple visualization.

**Comment by FlorentP42** [comment]
Well my use case is indeed pretty limited and it's the one I described up there: I want to test if a bbox is fully contained in a sphere, so I do 8 point in sphere checks with the 8 corners :)

My point is that this check would return way more accurate results if I used the OBB corners instead of the AABB corners, mainly for long and thin or large and flat items, the AABB gets really oversized in those cases.

I am not sure how to combine GetShapeWorldTransform() and GetShapeSize() to obtain that though... GetShapeSize() returns a result in voxel number, right? Not in world coordinate. Also do you know what is the reference point of GetShapeSize(), is it not relative the the voxel model itself? And if so I don't think I can deduce how to convert this "box" where the reference point could be anywhere into actual corners of a box in world space coordinates (I am talking about any objects in the world, not a specific one I built).

**Comment by Thomasims** [comment]
GetShapeSize indeed returns the size in voxels, voxels are conveniently always the same size so the conversion is not an issue. The corner of the shape transform is always the same relative to the shape dimensions, there's no guessing game here. You should look into Transforms and how to use them, specifically local/global coordinate conversion.

I'm not going to pretend I understand why your use case requires this very specific condition but my gut feeling is that you're over thinking this and there's a much better approach to the problem you're attempting to solve.

**Comment by FlorentP42** [comment]
Oh, that's great news then :) I will have to do more testing using those functions and figure out how to get the results I am looking for, thanks for the precisions!

About doing it wrong that might be the case... What I want is just to know if an object is visually fully inside a sphere and delete it if it is (for more context the sphere is a black hole). I want to know when all the shape is "inside" the sphere to avoid deleting it when it's still visible for the user. And I notices that for several long or flat shapes, the AABB prevented the object from being detected as fully inside when in fact it was, resulting in the object poping out on the other side of the black hole :/

**Comment by FlorentP42** [comment]
Well I managed to get what I was looking for with the following code, so yeah I was probably overthinking the complexity of the task ^^ Anyway it would always be nice to have those kind of functions integrated in the modding API imho.
```
    function GetShapeObb(shape)
        local xsize, ysize, zsize, scale = GetShapeSize(shape)
        local min = Vec(0, 0, 0)
        local max = Vec(xsize * scale, ysize * scale, zsize * scale)
        local tr = GetShapeWorldTransform(shape)
        return tr, min, max
    end
    function GetBodyObb(body)
        local shapes = GetBodyShapes(body)
        local min = Vec(0, 0, 0)
        local max = Vec(0, 0, 0)
        local tr =  GetBodyTransform(body)
        for i=1,#shapes do
            local shape = shapes[i]
            local shapeTr, shapeMin, shapeMax = GetShapeObb(shape)
            local shapeLocalTr = GetShapeLocalTransform(shape)
            local shapeLocalMin = TransformToParentPoint(shapeLocalTr, shapeMin)
            local shapeLocalMax = TransformToParentPoint(shapeLocalTr, shapeMax)
            min = Vec(
                math.min(min[1], shapeLocalMin[1], shapeLocalMax[1]),
                math.min(min[2], shapeLocalMin[2], shapeLocalMax[2]),
                math.min(min[3], shapeLocalMin[3], shapeLocalMax[3])
            )
            max = Vec(
                math.max(max[1], shapeLocalMin[1], shapeLocalMax[1]),
                math.max(max[2], shapeLocalMin[2], shapeLocalMax[2]),
                math.max(max[3], shapeLocalMin[3], shapeLocalMax[3])
            )
        end
        return tr, min, max
    end
    function GetObbCorners(tr, min, max)
        local corners = {}
        local localCorners = {
            Vec(min[1], min[2], min[3]),
            Vec(max[1], min[2], min[3]),
            Vec(max[1], min[2], max[3]),
            Vec(min[1], min[2], max[3]),
            Vec(min[1], max[2], min[3]),
            Vec(max[1], max[2], min[3]),
            Vec(max[1], max[2], max[3]),
            Vec(min[1], max[2], max[3]),
        }
        for i=1,#localCorners do
            corners[#corners+1] = TransformToParentPoint(tr, localCorners[i])
        end
        return corners
    end
    function ObbDraw(c, r, g, b, a)
        r = r or 1
        g = g or 1
        b = b or 1
        a = a or 1
        -- bottom square
        DebugLine(c[1], c[2], r, g, b, a)
        DebugLine(c[2], c[3], r, g, b, a)
        DebugLine(c[3], c[4], r, g, b, a)
        DebugLine(c[4], c[1], r, g, b, a)
        -- top square
        DebugLine(c[5], c[6], r, g, b, a)
        DebugLine(c[6], c[7], r, g, b, a)
        DebugLine(c[7], c[8], r, g, b, a)
        DebugLine(c[8], c[5], r, g, b, a)
        -- vertical segments
        DebugLine(c[1], c[5], r, g, b, a)
        DebugLine(c[2], c[6], r, g, b, a)
        DebugLine(c[3], c[7], r, g, b, a)
        DebugLine(c[4], c[8], r, g, b, a)
    end
```
